project_id = "hkyircuwbfwncdhhzapp"

[functions.ai-process]
verify_jwt = false

[functions.ai-universal]
verify_jwt = false

[functions.manage-api-keys]
verify_jwt = false

[functions.generate-seo-articles]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.seo-report-store]
verify_jwt = false