import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Shield, FileText, AlertCircle, ScrollText, Cookie, BookOpen } from "lucide-react";

const createServices = (lang: string) => {
  const t: Record<string, Record<string, string>> = {
    cs: { badge: "Naše služby", title: "Základní právní dokumenty", desc: "Pro affiliate stránky jsou nezbytné následující právní dokumenty. Náš balíček obsahuje vše potřebné.", s1t: "Zásady ochrany osobních údajů", s1d: "Kompletní zásady v souladu s GDPR", s2t: "Prohlášení", s2d: "Právní ochrana proti nárokům na odpovědnost", s3t: "Affiliate prohlášení", s3d: "Transparentní prohlášení v souladu s FTC", s4t: "Obchodní podmínky", s4d: "Upravuje vztah mezi vaším webem a uživateli", s5t: "Zásady cookies", s5d: "Úplný soulad se zásadami cookies a souhlasem", s6t: "Průvodce implementací", s6d: "Podrobné pokyny pro implementaci", c1t: "Ideální pro všechny affiliate", c1d: "S tisíci affiliate webů jsou naše přizpůsobitelné dokumenty vhodné pro každé affiliate podnikání. Soustřeďte se na vydělávání provizí — právní soulad jsme zjednodušili!", c2t: "Pro VŠECHNY vaše stránky", c2d: "Základní právní dokumenty pro všechny vaše affiliate stránky. Ano, můžete je používat pro VŠECHNY weby bez nutnosti kupovat samostatné licence!", c3t: "Minimalizujte rizika", c3d: "Žádný dokument nenabízí 100% ochranu, ale dobré právní dokumenty výrazně minimalizují vaše rizika a ukazují, že jednáte odpovědně." },
    hu: { badge: "Szolgáltatásaink", title: "Alapvető jogi dokumentumok", desc: "Az affiliate weboldalakhoz a következő jogi dokumentumok szükségesek. Csomagunk mindent tartalmaz.", s1t: "Adatvédelmi irányelvek", s1d: "GDPR-nak megfelelő adatvédelmi szabályzat", s2t: "Nyilatkozat", s2d: "Jogi védelem felelősségi igények ellen", s3t: "Affiliate nyilatkozat", s3d: "FTC irányelveknek megfelelő átlátható nyilatkozat", s4t: "Általános feltételek", s4d: "Az Ön weboldala és a felhasználók közötti viszonyt szabályozza", s5t: "Cookie szabályzat", s5d: "Teljes cookie megfelelőség és hozzájárulás", s6t: "Megvalósítási útmutató", s6d: "Lépésről lépésre szóló utasítások", c1t: "Tökéletes minden affiliate-nek", c1d: "Testreszabható dokumentumaink minden affiliate vállalkozáshoz alkalmasak. Összpontosítson a jutalékokra — a jogi megfelelést egyszerűvé tettük!", c2t: "MINDEN weboldalához", c2d: "Az alapvető jogi dokumentumok minden affiliate oldalához. Igen, MINDEN weboldalon használhatja külön licensz nélkül!", c3t: "Minimalizálja a kockázatokat", c3d: "Egyetlen dokumentum sem kínál 100%-os védelmet, de a jó jogi dokumentumok jelentősen minimalizálják kockázatait." },
    uk: { badge: "Наші послуги", title: "Основні юридичні документи", desc: "Для affiliate сайту необхідні наступні юридичні документи. Наш пакет містить все необхідне.", s1t: "Політика конфіденційності", s1d: "Повна відповідність GDPR", s2t: "Застереження", s2d: "Юридичний захист від претензій", s3t: "Affiliate розкриття", s3d: "Прозоре розкриття відповідно до FTC", s4t: "Умови використання", s4d: "Регулює відносини між сайтом та користувачами", s5t: "Політика cookies", s5d: "Повна відповідність щодо cookies та згоди", s6t: "Посібник з впровадження", s6d: "Покрокові інструкції для впровадження", c1t: "Ідеально для всіх affiliate", c1d: "Наші документи підходять для будь-якого affiliate бізнесу. Зосередьтеся на заробітку — ми спростили юридичну відповідність!", c2t: "Для ВСІХ ваших сайтів", c2d: "Основні юридичні документи для всіх ваших affiliate сайтів. Так, можна використовувати для ВСІХ сайтів без окремих ліцензій!", c3t: "Мінімізуйте ризики", c3d: "Жоден документ не дає 100% захисту, але хороші юридичні документи значно мінімізують ваші ризики." },
    sk: { badge: "Naše služby", title: "Základné právne dokumenty", desc: "Pre affiliate stránky sú nevyhnutné nasledovné právne dokumenty. Náš balíček obsahuje všetko potrebné.", s1t: "Zásady ochrany osobných údajov", s1d: "Kompletné zásady v súlade s GDPR", s2t: "Vyhlásenie", s2d: "Právna ochrana proti nárokom na zodpovednosť", s3t: "Affiliate vyhlásenie", s3d: "Transparentné vyhlásenie v súlade s FTC", s4t: "Obchodné podmienky", s4d: "Upravuje vzťah medzi vaším webom a používateľmi", s5t: "Zásady cookies", s5d: "Úplný súlad so zásadami cookies a súhlasom", s6t: "Sprievodca implementáciou", s6d: "Podrobné pokyny pre implementáciu", c1t: "Ideálne pre všetkých affiliate", c1d: "Naše prispôsobiteľné dokumenty sú vhodné pre každé affiliate podnikanie!", c2t: "Pre VŠETKY vaše stránky", c2d: "Základné právne dokumenty pre všetky vaše affiliate stránky bez ďalších licencií!", c3t: "Minimalizujte riziká", c3d: "Dobré právne dokumenty výrazne minimalizujú vaše riziká a ukazujú, že konáte zodpovedne." },
    hr: { badge: "Naše usluge", title: "Osnovni pravni dokumenti", desc: "Za affiliate web stranicu potrebni su sljedeći pravni dokumenti. Naš paket sadrži sve potrebno.", s1t: "Politika privatnosti", s1d: "Potpuno usklađena s GDPR zakonodavstvom", s2t: "Izjava o odricanju", s2d: "Pravna zaštita od odštetnih zahtjeva", s3t: "Affiliate izjava", s3d: "Transparentna izjava u skladu s FTC smjernicama", s4t: "Uvjeti korištenja", s4d: "Uređuje odnos između vaše stranice i korisnika", s5t: "Politika kolačića", s5d: "Potpuna usklađenost s politikom kolačića i pristankom", s6t: "Vodič za implementaciju", s6d: "Korak-po-korak upute za implementaciju", c1t: "Savršeno za sve affiliate", c1d: "Naši prilagodljivi dokumenti su pogodni za svako affiliate poslovanje!", c2t: "Za SVE vaše stranice", c2d: "Osnovni pravni dokumenti za sve vaše affiliate stranice bez zasebnih licenci!", c3t: "Minimizirajte rizike", c3d: "Dobri pravni dokumenti značajno minimiziraju vaše rizike." },
    sr: { badge: "Наше услуге", title: "Основни правни документи", desc: "За affiliate сајт потребни су следећи правни документи. Наш пакет садржи све потребно.", s1t: "Политика приватности", s1d: "Потпуно усклађена са GDPR законодавством", s2t: "Изјава о одрицању", s2d: "Правна заштита од одштетних захтева", s3t: "Affiliate изјава", s3d: "Транспарентна изјава у складу са FTC", s4t: "Услови коришћења", s4d: "Уређује однос између вашег сајта и корисника", s5t: "Политика колачића", s5d: "Потпуна усклађеност са политиком колачића", s6t: "Водич за имплементацију", s6d: "Корак-по-корак упутства", c1t: "Савршено за све affiliate", c1d: "Наши прилагодљиви документи су погодни за свако affiliate пословање!", c2t: "За СВЕ ваше сајтове", c2d: "Основни правни документи за све ваше affiliate сајтове без засебних лиценци!", c3t: "Минимизирајте ризике", c3d: "Добри правни документи значајно минимизују ваше ризике." },
    sl: { badge: "Naše storitve", title: "Bistveni pravni dokumenti", desc: "Za affiliate spletno stran so potrebni naslednji pravni dokumenti. Naš paket vsebuje vse potrebno.", s1t: "Pravilnik o zasebnosti", s1d: "Popolnoma skladen z GDPR zakonodajo", s2t: "Izjava o omejitvi odgovornosti", s2d: "Pravna zaščita pred odškodninskimi zahtevki", s3t: "Affiliate razkritje", s3d: "Pregledno razkritje v skladu s FTC", s4t: "Splošni pogoji", s4d: "Ureja razmerje med vašo stranjo in uporabniki", s5t: "Pravilnik o piškotkih", s5d: "Popolna skladnost s pravilnikom o piškotkih in soglasjem", s6t: "Vodnik za implementacijo", s6d: "Navodila po korakih za implementacijo", c1t: "Popolno za vse affiliate", c1d: "Naši prilagodljivi dokumenti so primerni za vsako affiliate poslovanje!", c2t: "Za VSE vaše strani", c2d: "Bistveni pravni dokumenti za vse vaše affiliate strani brez ločenih licenc!", c3t: "Zmanjšajte tveganja", c3d: "Dobri pravni dokumenti bistveno zmanjšajo vaša tveganja." },
  };
  return t[lang];
};

export { createServices };
