import { useState } from "react";
import { Helmet } from "react-helmet";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Crown, Shield, Globe, ArrowRight, Star, Link, BarChart3, Mail, User, MessageSquare, ArrowUp } from "lucide-react";
import { Link as RouterLink } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";
import LanguageSwitcher from "@/components/premium-domains/LanguageSwitcher";
import HiddenInternalLinks from "@/components/HiddenInternalLinks";
import { validateContactForm, buildSafeMailtoUrl } from "@/lib/formValidation";
import { premiumDomains } from "./PremiumDomainsEN";
import { getTranslatedDomains } from "@/data/domainTranslations";
import SeoRedirectsSection from "@/components/premium-domains/shared/SeoRedirectsSection";
import TrusteeServiceSection from "@/components/premium-domains/shared/TrusteeServiceSection";
import NordVPNSection from "@/components/premium-domains/shared/NordVPNSection";
import EuDomainValueSection from "@/components/premium-domains/shared/EuDomainValueSection";
import InternalLanguageLinks from "@/components/premium-domains/shared/InternalLanguageLinks";

const translatedDomains = getTranslatedDomains(premiumDomains, 'ro');

const HREFLANG_URLS: Record<string, string> = {
  nl: "https://www.iaee.eu/expireddomainnames/nl/premium-domeinnamen-kopen-hoge-autoriteit-seo-waarde",
  en: "https://www.iaee.eu/expireddomainnames/en/buy-premium-domains-high-authority-seo-value",
  de: "https://www.iaee.eu/expireddomainnames/de/premium-domains-kaufen-hohe-autoritaet-seo-wert",
  fr: "https://www.iaee.eu/expireddomainnames/fr/acheter-domaines-premium-haute-autorite-valeur-seo",
  es: "https://www.iaee.eu/expireddomainnames/es/comprar-dominios-premium-alta-autoridad-valor-seo",
  it: "https://www.iaee.eu/expireddomainnames/it/acquista-domini-premium-alta-autorita-valore-seo",
  pt: "https://www.iaee.eu/expireddomainnames/pt/comprar-dominios-premium-alta-autoridade-valor-seo",
  pl: "https://www.iaee.eu/expireddomainnames/pl/kup-domeny-premium-wysoki-autorytet-wartosc-seo",
  ja: "https://www.iaee.eu/expireddomainnames/ja/puremiamudomein-kounyuu-seo-kachi",
  zh: "https://www.iaee.eu/expireddomainnames/zh/gou-mai-gao-quan-zhong-you-zhi-yu-ming-seo-jia-zhi",
  ar: "https://www.iaee.eu/expireddomainnames/ar/shira-asma-nitaqat-mumayaza-sulta-aliya-qima-seo",
  tr: "https://www.iaee.eu/expireddomainnames/tr/premium-alan-adlari-yuksek-otorite-seo-degeri",
  hi: "https://www.iaee.eu/expireddomainnames/hi/premium-domain-kharidein-uchch-authority-seo-mulya",
  sv: "https://www.iaee.eu/expireddomainnames/sv/kop-premiumdomaner-hog-auktoritet-seo-varde",
  no: "https://www.iaee.eu/expireddomainnames/no/kjop-premiumdomener-hoy-autoritet-seo-verdi",
  da: "https://www.iaee.eu/expireddomainnames/da/kob-premium-domaener-hoj-autoritet-seo-vaerdi",
  fi: "https://www.iaee.eu/expireddomainnames/fi/osta-premium-verkkotunnukset-korkea-auktoriteetti-seo-arvo",
  cs: "https://www.iaee.eu/expireddomainnames/cs/koupit-premium-domeny-vysoka-autorita-seo-hodnota",
  el: "https://www.iaee.eu/expireddomainnames/el/agoraste-premium-domains-ypsili-afthentia-seo-axia",
  ru: "https://www.iaee.eu/expireddomainnames/ru/kupit-premium-domeny-vysokij-avtoritet-seo-cennost",
  ro: "https://www.iaee.eu/expireddomainnames/ro/cumpara-domenii-premium-autoritate-inalta-valoare-seo",
  bg: "https://www.iaee.eu/expireddomainnames/bg/kupete-premium-domeyni-visok-avtoritet-seo-stoynost",
  uk: "https://www.iaee.eu/expireddomainnames/uk/kupyty-premium-domeny-vysokyj-avtorytet-seo-tsinnist",
};

const PremiumDomainsRO = () => {
  const { toast } = useToast();
  const [formData, setFormData] = useState({ name: "", email: "", domain: "", message: "" });
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const scrollToSection = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault(); setFormErrors({});
    const validation = validateContactForm(formData);
    if (!validation.success) { const er = validation as { success: false; errors: Record<string, string> }; setFormErrors(er.errors); toast({ title: "Corectați erorile din formular", description: Object.values(er.errors)[0], variant: "destructive" }); return; }
    const { data } = validation;
    window.location.href = buildSafeMailtoUrl("support@iaee.eu", `Domeniu Premium: ${data.domain}`, `Nume: ${data.name}\nEmail: ${data.email}\nDomeniu: ${data.domain}\n\nMesaj:\n${data.message || ""}`);
    toast({ title: "Cererea se trimite" });
  };
  const handleDomainInquiry = (domainName: string) => { setFormData(prev => ({ ...prev, domain: domainName })); scrollToSection("contact"); };

  return (
    <>
      <Helmet>
        <html lang="ro" />
        <title>Cumpără Domenii Premium Expirate cu Backlink-uri | Autoritate Înaltă & Valoare SEO</title>
        <meta name="description" content="Cumpără domenii expirate cu backlink-uri? Domenii expirate de încredere cu autoritate înaltă și valoare SEO. Cumpără domenii premium pentru clasare mai rapidă în Google. Disponibile imediat." />
        <meta name="keywords" content="cumpără domeniu expirat, domenii expirate cu backlink-uri, domeniu cu autoritate, domenii expirate de încredere, cumpără domenii premium, domenii cu valoare SEO" />
        <link rel="canonical" href={HREFLANG_URLS.ro} />
        <meta name="robots" content="index, follow" />
        {Object.entries(HREFLANG_URLS).map(([lang, url]) => (<link key={lang} rel="alternate" hrefLang={lang} href={url} />))}
        <link rel="alternate" hrefLang="x-default" href={HREFLANG_URLS.en} />
        <meta property="og:type" content="website" /><meta property="og:title" content="Cumpără Domenii Premium Expirate cu Backlink-uri | Autoritate Înaltă & Valoare SEO" /><meta property="og:description" content="Domenii expirate de încredere cu autoritate înaltă și valoare SEO." /><meta property="og:url" content={HREFLANG_URLS.ro} /><meta property="og:locale" content="ro_RO" /><meta property="og:site_name" content="IAEE Premium Domains" /><meta property="og:image" content="https://www.iaee.eu/images/premium-domains-og.jpg" />
        <script type="application/ld+json">{`{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://iaee.eu/#organization","name":"IAEE Premium Domains","url":"https://iaee.eu","logo":"https://iaee.eu/images/premium-domains-og.jpg","description":"Specialist în domenii premium expirate cu autoritate înaltă și valoare SEO"},{"@type":"WebPage","url":"${HREFLANG_URLS.ro}","name":"Cumpără Domenii Premium Expirate cu Backlink-uri","inLanguage":"ro"},{"@type":"ItemList","name":"Domenii Premium Expirate","numberOfItems":${premiumDomains.length},"itemListElement":${JSON.stringify(premiumDomains.slice(0,10).map((d,i)=>({"@type":"ListItem","position":i+1,"item":{"@type":"Product","name":d.name,"description":d.description,"image":"https://www.iaee.eu/images/premium-domains-logo.png","sku":d.name,"brand":{"@type":"Brand","name":"IAEE Premium Domains"},"offers":{"@type":"Offer","price":d.price.replace(/[^0-9]/g,""),"priceCurrency":"EUR","availability":"https://schema.org/InStock","seller":{"@type":"Organization","name":"IAEE Premium Domains"}}}})))}}]}`}</script>
      </Helmet>
      <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
        <LanguageSwitcher currentLanguage="ro" />
        <header className="sticky top-0 z-50 backdrop-blur-xl bg-slate-950/80 border-b border-amber-500/20"><div className="container mx-auto px-3 sm:px-4 py-3 sm:py-4 flex items-center justify-between"><RouterLink to="/expireddomainnames/ro/cumpara-domenii-premium-autoritate-inalta-valoare-seo" className="flex items-center gap-2 sm:gap-3 min-w-0 flex-shrink-0"><Crown className="h-6 w-6 sm:h-8 sm:w-8 text-amber-400 flex-shrink-0" /><span className="text-base sm:text-xl font-bold bg-gradient-to-r from-amber-200 to-amber-400 bg-clip-text text-transparent truncate">Domenii Premium</span></RouterLink><nav className="hidden md:flex items-center gap-4 lg:gap-6"><button onClick={() => scrollToSection("domains")} className="text-slate-300 hover:text-amber-400 transition-colors text-sm font-medium">Domenii</button><button onClick={() => scrollToSection("why-premium")} className="text-slate-300 hover:text-amber-400 transition-colors text-sm font-medium">De Ce Premium?</button><button onClick={() => scrollToSection("faq")} className="text-slate-300 hover:text-amber-400 transition-colors text-sm font-medium">FAQ</button><Button onClick={() => scrollToSection("contact")} className="bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-semibold">Contact</Button></nav><Button onClick={() => scrollToSection("domains")} className="md:hidden bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 font-semibold text-xs px-3 py-2">Domenii</Button></div></header>

        <section className="relative py-12 sm:py-16 md:py-24 lg:py-32 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-amber-900/20 via-transparent to-transparent" /><div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] sm:w-[600px] md:w-[800px] h-[400px] sm:h-[600px] md:h-[800px] bg-amber-500/5 rounded-full blur-3xl" /><div className="container mx-auto px-3 sm:px-4 relative z-10"><div className="max-w-4xl mx-auto text-center"><Badge className="mb-4 sm:mb-6 bg-amber-500/10 text-amber-400 border-amber-500/30 px-3 sm:px-4 py-1.5 sm:py-2 text-xs sm:text-sm"><Star className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2 inline" />Colecție Exclusivă de Domenii Premium</Badge><h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl xl:text-5xl font-bold mb-4 sm:mb-6 leading-tight px-2"><span className="bg-gradient-to-r from-amber-300 via-amber-400 to-amber-500 bg-clip-text text-transparent">Cumpără Domenii Premium Expirate cu Backlink-uri Autoritate Înaltă & Valoare SEO</span></h1><p className="text-sm sm:text-base md:text-lg lg:text-xl text-slate-400 mb-6 sm:mb-8 md:mb-10 max-w-2xl mx-auto leading-relaxed px-2">Consolidează-ți prezența online cu domenii care au construit autoritate de-a lungul anilor. Ideal pentru clasare mai rapidă, backlink-uri puternice și beneficii SEO directe.</p>
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center px-4"><Button size="lg" onClick={() => scrollToSection("domains")} className="bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-bold text-sm sm:text-base md:text-lg px-4 sm:px-6 md:px-8 py-4 sm:py-5 md:py-6 shadow-lg shadow-amber-500/25">Vezi Domeniile <ArrowRight className="ml-2 h-4 w-4 sm:h-5 sm:w-5" /></Button><Button size="lg" variant="outline" onClick={() => scrollToSection("why-premium")} className="bg-slate-800 border-slate-600 text-slate-200 hover:bg-slate-700 hover:text-white text-sm sm:text-base md:text-lg px-4 sm:px-6 md:px-8 py-4 sm:py-5 md:py-6">Mai Multe Informații</Button></div>
          <div className="mt-8 sm:mt-12 md:mt-16 grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4 md:gap-6 px-2">{[{label:"Scor MOZ Mediu",value:"29+"},{label:"Domenii Premium",value:"110+"},{label:"Ani Experiență",value:"10+"},{label:"Clienți Mulțumiți",value:"500+"}].map((s,i)=>(<div key={i} className="p-3 sm:p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 backdrop-blur"><div className="text-xl sm:text-2xl md:text-3xl font-bold text-amber-400">{s.value}</div><div className="text-xs sm:text-sm text-slate-400 mt-1">{s.label}</div></div>))}</div></div></div></section>

        <section id="domains" className="py-20 relative"><div className="absolute inset-0 bg-gradient-to-b from-transparent via-slate-900/50 to-transparent" /><div className="container mx-auto px-4 relative z-10"><div className="text-center mb-12"><Badge className="mb-4 bg-slate-800 text-amber-400 border-slate-700"><Globe className="w-4 h-4 mr-2 inline" />Domenii Disponibile</Badge><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Domenii Premium de Vânzare</h2><p className="text-slate-400 max-w-3xl mx-auto">Fiecare domeniu este selectat cu grijă pe baza autorității MOZ, profilului de backlink-uri și potențialului SEO.</p></div>
          <div className="max-w-5xl mx-auto mb-8 bg-slate-800/30 border border-slate-700/50 rounded-2xl p-8"><p className="text-slate-300 leading-relaxed mb-4"><strong className="text-white">Cauți un domeniu cu valoare SEO reală?</strong> La noi cumperi <strong className="text-amber-400">domenii expirate cu backlink-uri</strong> și autoritate înaltă, verificate cu atenție pentru calitate și istoric.</p><p className="text-slate-300 leading-relaxed mb-4"><strong className="text-amber-400">Ne specializăm în .EU și alte extensii europene</strong> și ne distingem clar în segmentul numelor web europene.</p><p className="text-slate-300 leading-relaxed mb-4">Aceste domenii expirate au backlink-uri existente de la <strong className="text-amber-400">companii de renume, instituții media și organizații guvernamentale</strong> — linkuri importante care sunt foarte dificil sau imposibil de obținut pentru site-uri obișnuite.</p></div>
          <div className="max-w-5xl mx-auto mb-10 text-center"><p className="text-sm text-slate-300 font-medium bg-slate-800/40 border border-slate-700/40 rounded-lg px-4 py-3 inline-block"><span className="text-amber-400 font-semibold">Informații TVA:</span> Prețurile sunt fără TVA pentru clienți privați din UE. Clienții business din UE pot aplica taxare inversă.</p></div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5 md:gap-6">{translatedDomains.map((domain, index) => (<Card key={index} className="h-full flex flex-col bg-gradient-to-br from-slate-800/80 to-slate-900/80 border-slate-700/50 backdrop-blur hover:border-amber-500/50 transition-all duration-300 hover:shadow-lg hover:shadow-amber-500/10 group"><CardHeader className="pb-2 sm:pb-3 p-3 sm:p-4 md:p-6"><div className="mt-1 mb-2 flex justify-center"><img src="/images/premium-domains-logo-en.png" alt={`Cumpără ${domain.name} - Domeniu Premium Expirat cu Autoritate MOZ Înaltă & Valoare SEO`} className="w-20 h-auto object-contain" /></div><div className="flex items-center justify-between gap-2"><Badge variant="outline" className="text-[10px] sm:text-xs border-slate-600 text-slate-400 flex-shrink-0">{domain.category}</Badge><div className="flex items-center gap-1 bg-amber-500/10 px-1.5 sm:px-2 py-0.5 sm:py-1 rounded-full flex-shrink-0"><BarChart3 className="w-2.5 h-2.5 sm:w-3 sm:h-3 text-amber-400" /><span className="text-[10px] sm:text-xs font-semibold text-amber-400">MOZ {domain.mozScore}</span></div></div><CardTitle className="text-lg sm:text-xl md:text-2xl text-white group-hover:text-amber-400 transition-colors mt-2 sm:mt-3 break-all"><RouterLink to={`/domains/${domain.name.replace(/\./g, '-')}`} className="hover:underline">{domain.name}</RouterLink></CardTitle><CardDescription className="text-sm sm:text-base text-slate-300">{domain.description}<RouterLink to={`/domains/${domain.name.replace(/\./g, '-')}`} className="block mt-1 text-xs text-amber-400 hover:text-amber-300 underline">Vezi detalii →</RouterLink></CardDescription></CardHeader>
            <CardContent className="flex flex-col flex-grow p-3 sm:p-4 md:p-6 pt-0"><div className="space-y-2 sm:space-y-3 mb-3 sm:mb-4"><div className="flex items-center justify-between text-xs sm:text-sm"><div className="flex items-center gap-1.5 sm:gap-2 text-slate-400"><Link className="w-3 h-3 sm:w-4 sm:h-4 flex-shrink-0" /><span>Backlink-uri: {domain.backlinks}</span></div></div>{domain.pageAuthority && (<div className="grid grid-cols-2 gap-1.5 sm:gap-2 text-[10px] sm:text-xs"><div className="bg-slate-800/50 rounded px-1.5 sm:px-2 py-0.5 sm:py-1"><span className="text-slate-500">Aut. Pagină:</span><span className="text-white ml-1 font-medium">{domain.pageAuthority}</span></div><div className="bg-slate-800/50 rounded px-1.5 sm:px-2 py-0.5 sm:py-1"><span className="text-slate-500">Domenii Linkate:</span><span className="text-white ml-1 font-medium">{domain.linkingDomains}</span></div><div className="bg-slate-800/50 rounded px-1.5 sm:px-2 py-0.5 sm:py-1"><span className="text-slate-500">Link-uri Intrare:</span><span className="text-white ml-1 font-medium">{domain.inboundLinks}</span></div><div className="bg-slate-800/50 rounded px-1.5 sm:px-2 py-0.5 sm:py-1"><span className="text-slate-500">Link-uri Followed:</span><span className="text-white ml-1 font-medium">{domain.followedLinks}</span></div></div>)}{domain.topBacklinks && domain.topBacklinks.length > 0 && (<div className="text-[10px] sm:text-xs"><span className="text-slate-500 block mb-1">Top Backlink-uri:</span><div className="flex flex-wrap gap-0.5 sm:gap-1">{domain.topBacklinks.slice(0, 5).map((link, i) => (<Badge key={i} variant="outline" className="text-[8px] sm:text-[10px] border-amber-500/30 text-amber-400/80 bg-amber-500/5 px-1 sm:px-1.5 py-0">{link}</Badge>))}</div></div>)}</div>
              <div className="mt-auto pt-3 sm:pt-4 border-t border-slate-700/50"><div className="flex items-center justify-between mb-2 sm:mb-3 bg-slate-800/60 rounded-lg px-2 sm:px-3 py-1.5 sm:py-2"><span className="text-xs sm:text-sm font-medium text-slate-300">Preț</span><span className="text-base sm:text-lg font-bold text-amber-400">{domain.price}</span></div>{domain.stripePaymentLink ? (<a href={domain.stripePaymentLink} target="_blank" rel="noopener noreferrer" className="w-full inline-flex items-center justify-center gap-2 px-4 sm:px-6 py-3 sm:py-4 bg-[#F59E0B] text-slate-950 font-bold rounded-md shadow-md hover:bg-[#D97706] transition-colors text-sm sm:text-base md:text-lg">Cumpără Acum</a>) : (<button onClick={() => handleDomainInquiry(domain.name)} className="w-full inline-flex items-center justify-center gap-2 px-4 sm:px-6 py-3 sm:py-4 bg-slate-700 text-white font-bold rounded-md hover:bg-slate-600 transition-colors text-sm sm:text-base">Solicitare</button>)}</div></CardContent></Card>))}</div></div></section>

        <section id="why-premium" className="py-20 bg-gradient-to-b from-slate-900 to-slate-950"><div className="container mx-auto px-4"><div className="text-center mb-16"><Badge className="mb-4 bg-slate-800 text-amber-400 border-slate-700">De Ce Domenii Premium?</Badge><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Avantajele Domeniilor Premium Expirate</h2><p className="text-slate-400 max-w-2xl mx-auto">Descoperă de ce domeniile expirate cu autoritate înaltă sunt cea mai inteligentă investiție pentru strategia ta SEO.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-5xl mx-auto">{[{icon:Shield,title:"Istoric Curat",desc:"Fără spam sau istoric de penalizări"},{icon:Link,title:"Backlink-uri de Calitate",desc:"Din surse de încredere"},{icon:BarChart3,title:"Scor DA Ridicat",desc:"Minimum DA 20+"},{icon:Globe,title:"TLD-uri EU/Globale",desc:".eu, .nl, .be, .de, .co.uk"}].map((item,index)=>(<div key={index} className="text-center p-6 rounded-xl bg-slate-800/30 border border-slate-700/50"><div className="w-12 h-12 rounded-full bg-amber-500/20 flex items-center justify-center mx-auto mb-4"><item.icon className="h-6 w-6 text-amber-400" /></div><h4 className="text-white font-semibold mb-1">{item.title}</h4><p className="text-slate-400 text-sm">{item.desc}</p></div>))}</div></div></section>

        <section id="faq" className="py-20 bg-gradient-to-b from-slate-950 to-slate-900"><div className="container mx-auto px-4"><div className="text-center mb-16"><Badge className="mb-4 bg-slate-800 text-amber-400 border-slate-700">Întrebări Frecvente</Badge><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">FAQ despre Domenii Premium & SEO</h2></div><div className="max-w-3xl mx-auto"><Accordion type="single" collapsible className="space-y-4">{[{q:"Ce este un domeniu expirat?",a:"Un domeniu expirat este un nume de domeniu care nu a fost reînnoit de proprietarul anterior și este acum disponibil pentru înregistrare. Aceste domenii păstrează adesea backlink-urile și autoritatea acumulate."},{q:"De ce sunt importante backlink-urile?",a:"Backlink-urile sunt unul dintre cei mai importanți factori de clasare pentru Google. Domeniile cu backlink-uri de calitate de pe site-uri autoritare au un avantaj în rezultatele căutării."},{q:"Cum funcționează redirecționarea 301 pentru SEO?",a:"O redirecționare 301 direcționează permanent vizitatorii și motoarele de căutare de la domeniul vechi la noul tău site, transferând valoarea linkurilor pentru o clasare mai bună."},{q:"Este legal să cumperi domenii expirate?",a:"Da, este complet legal. Când un domeniu expiră și nu este reînnoit de proprietar, devine disponibil pentru oricine să îl înregistreze."},{q:"Cât de repede voi vedea rezultate SEO?",a:"Rezultatele variază, dar mulți clienți văd îmbunătățiri în 2-4 săptămâni după configurarea unei redirecționări 301 sau construirea unui site pe domeniu."},{q:"Pot folosi domeniul pentru orice site web?",a:"Da, poți folosi domeniul pentru orice scop legal - site web, blog, magazin online, portofoliu sau ca redirecționare 301 către site-ul tău existent."},{q:"Ce este MOZ Domain Authority?",a:"MOZ Domain Authority (DA) este un scor de la 1 la 100 care prezice cât de bine se va clasa un site web în rezultatele căutării. Un DA mai mare înseamnă o autoritate mai puternică."},{q:"Cum transfer domeniul la registrarul meu?",a:"După achiziție vei primi un cod de transfer (EPP/Auth code) prin email. Cu acest cod poți transfera ușor domeniul la propriul tău registrar."},{q:"Oferiți suport după achiziție?",a:"Da, oferim suport complet la support@iaee.eu. Răspundem în 24 de ore la toate întrebările despre transferul domeniului și configurarea tehnică."},{q:"De ce să cumpăr de la un vânzător specializat?",a:"Pentru că obții calitate pre-verificată, eviți riscurile, ai transparență despre fiecare domeniu și economisești timp și bani pe cercetare proprie."}].map((faq,index)=>(<AccordionItem key={index} value={`faq-${index}`} className="bg-slate-800/40 border-slate-700/50 rounded-xl px-6"><AccordionTrigger className="text-left text-white hover:text-amber-400 hover:no-underline">{faq.q}</AccordionTrigger><AccordionContent className="text-slate-400">{faq.a}</AccordionContent></AccordionItem>))}</Accordion></div></div></section>

        <section id="contact" className="py-20 bg-slate-900"><div className="container mx-auto px-4"><div className="max-w-2xl mx-auto"><div className="text-center mb-12"><Badge className="mb-4 bg-amber-500/10 text-amber-400 border-amber-500/30"><Mail className="w-4 h-4 mr-2 inline" />Contactează-ne</Badge><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Solicită Informații sau Fă o Ofertă</h2><p className="text-slate-400">Interesat de unul dintre domeniile noastre premium? Completează formularul și te contactăm cât mai curând posibil.</p></div><Card className="bg-gradient-to-br from-slate-800/80 to-slate-900/80 border-slate-700/50"><CardContent className="p-8"><form onSubmit={handleSubmit} className="space-y-6"><div className="grid sm:grid-cols-2 gap-6"><div><label className="block text-sm font-medium text-slate-300 mb-2"><User className="w-4 h-4 inline mr-2" />Nume *</label><Input type="text" value={formData.name} onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))} placeholder="Numele tău" className="bg-slate-900/50 border-slate-700 text-white placeholder:text-slate-500 focus:border-amber-500" required /></div><div><label className="block text-sm font-medium text-slate-300 mb-2"><Mail className="w-4 h-4 inline mr-2" />Email *</label><Input type="email" value={formData.email} onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))} placeholder="al-tau@email.ro" className="bg-slate-900/50 border-slate-700 text-white placeholder:text-slate-500 focus:border-amber-500" required /></div></div><div><label className="block text-sm font-medium text-slate-300 mb-2"><Globe className="w-4 h-4 inline mr-2" />Nume Domeniu *</label><Input type="text" value={formData.domain} onChange={(e) => setFormData(prev => ({ ...prev, domain: e.target.value }))} placeholder="ex. ExempluDomeniu.eu" className="bg-slate-900/50 border-slate-700 text-white placeholder:text-slate-500 focus:border-amber-500" required /></div><div><label className="block text-sm font-medium text-slate-300 mb-2"><MessageSquare className="w-4 h-4 inline mr-2" />Mesaj</label><Textarea value={formData.message} onChange={(e) => setFormData(prev => ({ ...prev, message: e.target.value }))} placeholder="Spune-ne mai multe despre interesul tău..." rows={5} className="bg-slate-900/50 border-slate-700 text-white placeholder:text-slate-500 focus:border-amber-500 resize-none" /></div><Button type="submit" size="lg" className="w-full bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-bold text-lg py-6 shadow-lg shadow-amber-500/25">Trimite Cererea <ArrowRight className="ml-2 h-5 w-5" /></Button></form></CardContent></Card></div></div></section>

        <SeoRedirectsSection lang="ro" />
        <TrusteeServiceSection lang="ro" />
        <EuDomainValueSection lang="ro" />

        <section className="py-16 bg-slate-950"><div className="container mx-auto px-4"><div className="max-w-2xl mx-auto text-center"><h2 className="text-2xl md:text-3xl font-bold text-white mb-4">Contactează-ne</h2><p className="text-slate-300 mb-8">Ai întrebări despre un domeniu specific sau vrei sfaturi despre care domeniu expirat se potrivește cel mai bine proiectului tău?</p><div className="bg-slate-800/50 border border-slate-700 rounded-xl p-8"><div className="flex flex-col gap-4"><div className="flex items-center justify-center gap-3"><Mail className="h-5 w-5 text-amber-400" /><a href="mailto:support@iaee.eu" className="text-amber-400 hover:text-amber-300 transition-colors text-lg font-medium">support@iaee.eu</a></div><p className="text-slate-400 text-sm">Răspundem la mesajul tău în 24 de ore.</p></div></div></div></div></section>

        <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="fixed bottom-6 right-6 z-50 p-3 bg-amber-500 hover:bg-amber-600 text-slate-950 rounded-full shadow-lg transition-all duration-200 hover:shadow-xl" aria-label="Înapoi sus"><ArrowUp className="w-6 h-6" /></button><HiddenInternalLinks />
        <InternalLanguageLinks lang="ro" currentLang="ro" />
        <section className="py-12 bg-slate-900"><div className="container mx-auto px-4"><h3 className="text-2xl font-semibold text-white mb-6 text-center">Informații Legale</h3><div className="flex flex-wrap justify-center gap-4"><RouterLink to="/expireddomainnames/en/premium-domains-legal-documents" className="text-slate-300 hover:text-amber-400 transition-colors text-sm underline underline-offset-2">Termeni și Condiții</RouterLink><span className="text-slate-600">|</span><RouterLink to="/expireddomainnames/en/premium-domains-legal-documents" className="text-slate-300 hover:text-amber-400 transition-colors text-sm underline underline-offset-2">Politica de Confidențialitate</RouterLink><span className="text-slate-600">|</span><RouterLink to="/expireddomainnames/en/premium-domains-legal-documents" className="text-slate-300 hover:text-amber-400 transition-colors text-sm underline underline-offset-2">Disclaimer</RouterLink></div></div></section>
        <footer className="py-12 bg-slate-950 border-t border-slate-800"><div className="container mx-auto px-4"><div className="flex flex-col md:flex-row items-center justify-between gap-4 border-t border-slate-800 pt-8"><div className="flex items-center gap-3"><Crown className="h-5 w-5 text-amber-400" /><span className="text-sm font-medium text-white">Domenii Premium</span></div><p className="text-slate-500 text-sm text-center md:text-right">© {new Date().getFullYear()} IAEE. Toate drepturile rezervate.</p></div></div></footer>
      </div>
    </>
  );
};

export default PremiumDomainsRO;
