import { useState } from "react";
import { Helmet } from "react-helmet";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Crown, Shield, Globe, ArrowRight, Star, Link, BarChart3, Mail, User, MessageSquare, ArrowUp } from "lucide-react";
import { Link as RouterLink } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";
import LanguageSwitcher from "@/components/premium-domains/LanguageSwitcher";
import HiddenInternalLinks from "@/components/HiddenInternalLinks";
import { validateContactForm, buildSafeMailtoUrl } from "@/lib/formValidation";
import { premiumDomains } from "./PremiumDomainsEN";
const CANONICAL = "https://www.iaee.eu/expireddomainnames/da/kob-premium-domaener-hoj-autoritet-seo-vaerdi";
const PremiumDomainsDA = () => {
  const { toast } = useToast();
  const [formData, setFormData] = useState({ name: "", email: "", domain: "", message: "" });
  const scrollToSection = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); const v = validateContactForm(formData); if (!v.success) { toast({ title: "Ret venligst fejlene", variant: "destructive" }); return; } const { data } = v; window.location.href = buildSafeMailtoUrl("support@iaee.eu", `Premium Domæne Forespørgsel: ${data.domain}`, `Navn: ${data.name}\nE-mail: ${data.email}\nDomæne: ${data.domain}\n\nBesked:\n${data.message || ""}`); toast({ title: "Forespørgsel sendes" }); };
  return (<><Helmet><html lang="da" /><title>Køb Premium Udløbne Domænenavne med Backlinks | Høj Autoritet & SEO-Værdi</title><meta name="description" content="Køb udløbne domænenavne med backlinks? Pålidelige udløbne domæner med høj autoritet og SEO-værdi." /><link rel="canonical" href={CANONICAL} /><meta name="robots" content="index, follow" /><link rel="alternate" hrefLang="en" href="https://www.iaee.eu/expireddomainnames/en/buy-premium-domains-high-authority-seo-value" /><link rel="alternate" hrefLang="da" href={CANONICAL} /><link rel="alternate" hrefLang="x-default" href="https://www.iaee.eu/expireddomainnames/en/buy-premium-domains-high-authority-seo-value" /><meta property="og:title" content="Køb Premium Udløbne Domænenavne" /><meta property="og:url" content={CANONICAL} /><meta property="og:locale" content="da_DK" /></Helmet>
  <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
    <LanguageSwitcher currentLanguage="da" />
    <header className="sticky top-0 z-50 backdrop-blur-xl bg-slate-950/80 border-b border-amber-500/20"><div className="container mx-auto px-3 py-3 flex items-center justify-between"><RouterLink to="/expireddomainnames/da/kob-premium-domaener-hoj-autoritet-seo-vaerdi" className="flex items-center gap-2"><Crown className="h-6 w-6 sm:h-8 sm:w-8 text-amber-400" /><span className="text-base sm:text-xl font-bold bg-gradient-to-r from-amber-200 to-amber-400 bg-clip-text text-transparent">Premium Domæner</span></RouterLink><nav className="hidden md:flex items-center gap-4"><button onClick={() => scrollToSection("domains")} className="text-slate-300 hover:text-amber-400 text-sm">Domæner</button><button onClick={() => scrollToSection("faq")} className="text-slate-300 hover:text-amber-400 text-sm">FAQ</button><Button onClick={() => scrollToSection("contact")} className="bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 font-semibold">Kontakt</Button></nav></div></header>
    <section className="relative py-12 sm:py-16 md:py-24 lg:py-32 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-amber-900/20 via-transparent to-transparent" /><div className="container mx-auto px-3 relative z-10"><div className="max-w-4xl mx-auto text-center"><Badge className="mb-4 bg-amber-500/10 text-amber-400 border-amber-500/30 px-3 py-1.5 text-xs sm:text-sm"><Star className="w-3 h-3 mr-1 inline" />Eksklusiv Samling af Premium Domæner</Badge><h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl xl:text-5xl font-bold mb-4 leading-tight"><span className="bg-gradient-to-r from-amber-300 via-amber-400 to-amber-500 bg-clip-text text-transparent">Køb Premium Udløbne Domænenavne med Backlinks Høj Autoritet & SEO-Værdi</span></h1><p className="text-sm sm:text-base md:text-lg text-slate-400 mb-6 max-w-2xl mx-auto">Styrk din online tilstedeværelse med domænenavne, der har opbygget autoritet gennem årene.</p><Button size="lg" onClick={() => scrollToSection("domains")} className="bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 font-bold px-6 py-5 shadow-lg">Vis Domæner <ArrowRight className="ml-2 h-5 w-5" /></Button><div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-3 px-2">{[{l:"Gns. MOZ",v:"29+"},{l:"Premium Domæner",v:"110+"},{l:"Års Erfaring",v:"10+"},{l:"Tilfredse Kunder",v:"500+"}].map((s,i)=>(<div key={i} className="p-3 rounded-xl bg-slate-800/50 border border-slate-700/50"><div className="text-xl font-bold text-amber-400">{s.v}</div><div className="text-xs text-slate-400 mt-1">{s.l}</div></div>))}</div></div></div></section>
    <section id="domains" className="py-20 relative"><div className="container mx-auto px-4 relative z-10"><div className="text-center mb-12"><Badge className="mb-4 bg-slate-800 text-amber-400 border-slate-700"><Globe className="w-4 h-4 mr-2 inline" />Tilgængelige Domæner</Badge><h2 className="text-3xl font-bold text-white mb-4">Premium Domænenavne Til Salg</h2></div><div className="max-w-5xl mx-auto mb-8 bg-slate-800/30 border border-slate-700/50 rounded-2xl p-8"><p className="text-slate-300 leading-relaxed"><strong className="text-white">Leder du efter et domænenavn med reel SEO-værdi?</strong> Hos os køber du pålidelige <strong className="text-amber-400">udløbne domænenavne med backlinks</strong> og høj autoritet.</p></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5 md:gap-6">{premiumDomains.map((domain, index) => (<Card key={index} className="h-full flex flex-col bg-gradient-to-br from-slate-800/80 to-slate-900/80 border-slate-700/50 hover:border-amber-500/50 transition-all group"><CardHeader className="pb-2 p-3 sm:p-4 md:p-6"><div className="mt-1 mb-2 flex justify-center"><img src="/images/premium-domains-logo-en.png" alt={`Køb ${domain.name} - Premium Domæne med Høj MOZ Autoritet`} className="w-20 h-auto object-contain" /></div><div className="flex items-center justify-between gap-2"><Badge variant="outline" className="text-[10px] border-slate-600 text-slate-400">{domain.category}</Badge><div className="flex items-center gap-1 bg-amber-500/10 px-1.5 py-0.5 rounded-full"><BarChart3 className="w-2.5 h-2.5 text-amber-400" /><span className="text-[10px] font-semibold text-amber-400">MOZ {domain.mozScore}</span></div></div><CardTitle className="text-lg sm:text-xl text-white group-hover:text-amber-400 mt-2 break-all"><RouterLink to={`/domains/${domain.name.replace(/\./g,'-')}`} className="hover:underline">{domain.name}</RouterLink></CardTitle><CardDescription className="text-sm text-slate-300">{domain.description}<RouterLink to={`/domains/${domain.name.replace(/\./g,'-')}`} className="block mt-1 text-xs text-amber-400 underline">Se alle detaljer →</RouterLink></CardDescription></CardHeader><CardContent className="flex flex-col flex-grow p-3 sm:p-4 md:p-6 pt-0"><div className="space-y-2 mb-3"><div className="flex items-center text-xs text-slate-400"><Link className="w-3 h-3 mr-1.5" />Backlinks: {domain.backlinks}</div>{domain.topBacklinks?.length>0&&(<div className="text-[10px]"><span className="text-slate-500 block mb-1">Top Backlinks:</span><div className="flex flex-wrap gap-0.5">{domain.topBacklinks.slice(0,5).map((l,i)=>(<Badge key={i} variant="outline" className="text-[8px] border-amber-500/30 text-amber-400/80 bg-amber-500/5 px-1 py-0">{l}</Badge>))}</div></div>)}</div><div className="mt-auto pt-3 border-t border-slate-700/50"><div className="flex items-center justify-between mb-2 bg-slate-800/60 rounded-lg px-2 py-1.5"><span className="text-xs text-slate-300">Pris</span><span className="text-base font-bold text-amber-400">{domain.price}</span></div>{domain.stripePaymentLink?(<a href={domain.stripePaymentLink} target="_blank" rel="noopener noreferrer" className="w-full inline-flex items-center justify-center px-4 py-3 bg-[#F59E0B] text-slate-950 font-bold rounded-md hover:bg-[#D97706] text-sm">Køb Nu</a>):(<button onClick={()=>{setFormData(p=>({...p,domain:domain.name}));scrollToSection("contact")}} className="w-full inline-flex items-center justify-center px-4 py-3 bg-slate-700 text-white font-bold rounded-md hover:bg-slate-600 text-sm">Forespørgsel</button>)}</div></CardContent></Card>))}</div></div></section>
    <section id="faq" className="py-20 bg-gradient-to-b from-slate-950 to-slate-900"><div className="container mx-auto px-4"><div className="text-center mb-16"><h2 className="text-3xl font-bold text-white">Ofte Stillede Spørgsmål</h2></div><div className="max-w-3xl mx-auto"><Accordion type="single" collapsible className="space-y-4">{[{q:"Hvad er et udløbt domænenavn?",a:"Et udløbt domænenavn er et domæne, der ikke blev fornyet af den tidligere ejer."},{q:"Hvorfor er backlinks vigtige?",a:"Backlinks er en af de vigtigste rangfaktorer for Google."},{q:"Hvad er MOZ Domain Authority?",a:"MOZ DA er en score fra 1-100, der forudsiger, hvor godt en hjemmeside rangerer."}].map((f,i)=>(<AccordionItem key={i} value={`f-${i}`} className="bg-slate-800/40 border-slate-700/50 rounded-xl px-6"><AccordionTrigger className="text-left text-white hover:text-amber-400 hover:no-underline">{f.q}</AccordionTrigger><AccordionContent className="text-slate-400">{f.a}</AccordionContent></AccordionItem>))}</Accordion></div></div></section>
    <section id="contact" className="py-20 bg-slate-900"><div className="container mx-auto px-4"><div className="max-w-2xl mx-auto"><div className="text-center mb-12"><h2 className="text-3xl font-bold text-white mb-4">Anmod om Information</h2></div><Card className="bg-gradient-to-br from-slate-800/80 to-slate-900/80 border-slate-700/50"><CardContent className="p-8"><form onSubmit={handleSubmit} className="space-y-6"><div className="grid sm:grid-cols-2 gap-6"><div><label className="block text-sm text-slate-300 mb-2">Navn *</label><Input type="text" value={formData.name} onChange={e=>setFormData(p=>({...p,name:e.target.value}))} className="bg-slate-900/50 border-slate-700 text-white" required /></div><div><label className="block text-sm text-slate-300 mb-2">E-mail *</label><Input type="email" value={formData.email} onChange={e=>setFormData(p=>({...p,email:e.target.value}))} className="bg-slate-900/50 border-slate-700 text-white" required /></div></div><div><label className="block text-sm text-slate-300 mb-2">Domænenavn *</label><Input type="text" value={formData.domain} onChange={e=>setFormData(p=>({...p,domain:e.target.value}))} className="bg-slate-900/50 border-slate-700 text-white" required /></div><div><label className="block text-sm text-slate-300 mb-2">Besked</label><Textarea value={formData.message} onChange={e=>setFormData(p=>({...p,message:e.target.value}))} rows={5} className="bg-slate-900/50 border-slate-700 text-white resize-none" /></div><Button type="submit" size="lg" className="w-full bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 font-bold text-lg py-6">Send Forespørgsel <ArrowRight className="ml-2 h-5 w-5" /></Button></form></CardContent></Card></div></div></section>
    <section className="py-16 bg-slate-950"><div className="container mx-auto px-4"><div className="max-w-2xl mx-auto text-center"><div className="bg-slate-800/50 border border-slate-700 rounded-xl p-8"><div className="flex items-center justify-center gap-3"><Mail className="h-5 w-5 text-amber-400" /><a href="mailto:support@iaee.eu" className="text-amber-400 text-lg font-medium">support@iaee.eu</a></div><p className="text-slate-400 text-sm mt-4">Vi svarer inden for 24 timer.</p></div></div></div></section>
    <button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className="fixed bottom-6 right-6 z-50 p-3 bg-amber-500 hover:bg-amber-600 text-slate-950 rounded-full shadow-lg"><ArrowUp className="w-6 h-6" /></button>
    <HiddenInternalLinks />
    <footer className="py-12 bg-slate-950 border-t border-slate-800"><div className="container mx-auto px-4"><div className="flex flex-col md:flex-row items-center justify-between gap-4"><div className="flex items-center gap-3"><Crown className="h-5 w-5 text-amber-400" /><span className="text-sm text-white">Premium Domæner</span></div><p className="text-slate-500 text-sm">© {new Date().getFullYear()} IAEE. Alle rettigheder forbeholdes.</p></div></div></footer>
  </div></>);
};
export default PremiumDomainsDA;
