import { Globe } from "lucide-react";

type Lang = 'en' | 'nl' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'pl' | 'tr' | 'ar' | 'hi' | 'ja' | 'zh' | 'sv' | 'no' | 'da' | 'fi' | 'cs' | 'el' | 'ru' | 'ro' | 'bg' | 'uk' | 'hr' | 'sk' | 'sr' | 'sl' | 'ko' | 'hu' | 'th' | 'vi' | 'id' | 'et' | 'lv' | 'lt' | 'is' | 'sq' | 'mk' | 'bs' | 'lb' | 'bn' | 'ms';

const t: Record<Lang, {
  title: string; intro: string;
  stepsTitle: string;
  steps: { title: string; desc: string }[];
  contactNote: string;
}> = {
  en: { title: "How do you transfer your domain with the transfer token (EPP/Auth code)?", intro: "After your purchase, you will receive a transfer token (also called EPP code or Auth code) within 24 hours at the email address you provided during payment. With this code you can easily transfer the domain to your own domain registrar or hosting provider.", stepsTitle: "Step-by-step instructions:", steps: [{ title: "Receive the transfer token", desc: "Check your inbox (and spam folder) for the email with the transfer token. You will receive this within 24 hours after payment." }, { title: "Log in to your domain registrar or hosting provider", desc: "Go to the domain management of your provider (e.g. GoDaddy, Namecheap, Google Domains, OVH, etc.)." }, { title: "Start the domain transfer", desc: "Look for the option 'Transfer domain', 'Domain transfer' or 'Import domain'. Enter the domain name you want to transfer." }, { title: "Enter the transfer token", desc: "Paste the transfer token (EPP/Auth code) you received from us in the designated field." }, { title: "Confirm the transfer", desc: "Enter the purchased domain name at your provider and confirm the transfer." }, { title: "Wait for completion", desc: "The transfer usually takes 1-5 business days, depending on the domain extension (.nl, .be, .eu, .com, etc.)." }, { title: "Use your domain", desc: "After completion you can use the domain immediately: use it as a 301 redirect for extra SEO value, or link it to hosting to build a new website." }], contactNote: "Do you have questions about the domain transfer? Feel free to contact us at" },
  nl: { title: "Hoe zet u uw domein over met de transfertoken (EPP/Auth-code)?", intro: "Na uw aankoop ontvangt u binnen 24 uur een transfertoken (ook wel EPP-code of Auth-code genoemd) op het e-mailadres dat u bij de betaling heeft opgegeven. Met deze code kunt u het domein eenvoudig overzetten naar uw eigen domeinregistrar of hostingprovider.", stepsTitle: "Stap-voor-stap instructies:", steps: [{ title: "Ontvang de transfertoken", desc: "Controleer uw inbox (en spammap) voor de e-mail met de transfertoken. U ontvangt deze binnen 24 uur na betaling." }, { title: "Log in bij uw domeinregistrar of hostingprovider", desc: "Ga naar het domeinbeheer van uw provider (bijv. GoDaddy, Namecheap, Google Domains, OVH, etc.)." }, { title: "Start de domeinoverdracht", desc: "Zoek de optie 'Domein overzetten', 'Domein transfer' of 'Domein importeren'. Voer de domeinnaam in die u wilt overzetten." }, { title: "Voer de transfertoken in", desc: "Plak de transfertoken (EPP/Auth-code) die u van ons heeft ontvangen in het daarvoor bestemde veld." }, { title: "Bevestig de overdracht", desc: "Voer de gekochte domeinnaam in bij uw provider en bevestig de overdracht." }, { title: "Wacht op voltooiing", desc: "De overdracht duurt meestal 1-5 werkdagen, afhankelijk van de domeinextensie (.nl, .be, .eu, .com, etc.)." }, { title: "Gebruik uw domein", desc: "Na voltooiing kunt u het domein direct gebruiken: als 301 redirect voor extra SEO-waarde, of koppel het aan hosting voor een nieuwe website." }], contactNote: "Heeft u vragen over de domeinoverdracht? Neem gerust contact met ons op via" },
  de: { title: "Wie übertragen Sie Ihre Domain mit dem Transfer-Token (EPP/Auth-Code)?", intro: "Nach Ihrem Kauf erhalten Sie innerhalb von 24 Stunden einen Transfer-Token (auch EPP-Code oder Auth-Code genannt) an die bei der Zahlung angegebene E-Mail-Adresse.", stepsTitle: "Schritt-für-Schritt-Anleitung:", steps: [{ title: "Transfer-Token empfangen", desc: "Prüfen Sie Ihren Posteingang (und Spam-Ordner) auf die E-Mail mit dem Transfer-Token." }, { title: "Bei Ihrem Domain-Registrar einloggen", desc: "Gehen Sie zur Domainverwaltung Ihres Anbieters (z.B. GoDaddy, Namecheap, etc.)." }, { title: "Domain-Transfer starten", desc: "Suchen Sie die Option 'Domain transferieren' oder 'Domain importieren'." }, { title: "Transfer-Token eingeben", desc: "Fügen Sie den erhaltenen Transfer-Token (EPP/Auth-Code) in das dafür vorgesehene Feld ein." }, { title: "Transfer bestätigen", desc: "Geben Sie den gekauften Domainnamen ein und bestätigen Sie den Transfer." }, { title: "Auf Abschluss warten", desc: "Der Transfer dauert in der Regel 1-5 Werktage." }, { title: "Domain nutzen", desc: "Nach Abschluss können Sie die Domain sofort nutzen: als 301-Weiterleitung oder für eine neue Website." }], contactNote: "Haben Sie Fragen zum Domain-Transfer? Kontaktieren Sie uns unter" },
  fr: { title: "Comment transférer votre domaine avec le jeton de transfert (code EPP/Auth)?", intro: "Après votre achat, vous recevrez un jeton de transfert (également appelé code EPP ou code Auth) dans les 24 heures à l'adresse e-mail fournie lors du paiement.", stepsTitle: "Instructions étape par étape:", steps: [{ title: "Recevoir le jeton de transfert", desc: "Vérifiez votre boîte de réception (et dossier spam) pour l'e-mail avec le jeton de transfert." }, { title: "Connectez-vous à votre registraire", desc: "Accédez à la gestion de domaine de votre fournisseur." }, { title: "Démarrer le transfert", desc: "Recherchez l'option 'Transférer un domaine' ou 'Importer un domaine'." }, { title: "Entrer le jeton de transfert", desc: "Collez le jeton de transfert (code EPP/Auth) reçu dans le champ désigné." }, { title: "Confirmer le transfert", desc: "Entrez le nom de domaine acheté et confirmez le transfert." }, { title: "Attendre la finalisation", desc: "Le transfert prend généralement 1 à 5 jours ouvrables." }, { title: "Utiliser votre domaine", desc: "Après finalisation, utilisez le domaine immédiatement: redirection 301 ou nouveau site web." }], contactNote: "Des questions sur le transfert? Contactez-nous à" },
  es: { title: "¿Cómo transferir su dominio con el token de transferencia (código EPP/Auth)?", intro: "Después de su compra, recibirá un token de transferencia (también llamado código EPP o código Auth) en 24 horas en el correo electrónico proporcionado durante el pago.", stepsTitle: "Instrucciones paso a paso:", steps: [{ title: "Recibir el token de transferencia", desc: "Revise su bandeja de entrada (y carpeta de spam) para el correo con el token." }, { title: "Iniciar sesión en su registrador", desc: "Vaya a la gestión de dominios de su proveedor." }, { title: "Iniciar la transferencia", desc: "Busque la opción 'Transferir dominio' o 'Importar dominio'." }, { title: "Ingresar el token de transferencia", desc: "Pegue el token de transferencia (código EPP/Auth) recibido." }, { title: "Confirmar la transferencia", desc: "Ingrese el nombre de dominio comprado y confirme la transferencia." }, { title: "Esperar la finalización", desc: "La transferencia suele tardar 1-5 días hábiles." }, { title: "Usar su dominio", desc: "Después de completarse, use el dominio inmediatamente: redirección 301 o nuevo sitio web." }], contactNote: "¿Preguntas sobre la transferencia? Contáctenos en" },
  it: { title: "Come trasferire il dominio con il token di trasferimento (codice EPP/Auth)?", intro: "Dopo l'acquisto, riceverai un token di trasferimento (chiamato anche codice EPP o Auth) entro 24 ore all'indirizzo email fornito durante il pagamento.", stepsTitle: "Istruzioni passo per passo:", steps: [{ title: "Ricevere il token di trasferimento", desc: "Controlla la tua casella di posta (e la cartella spam) per l'email con il token." }, { title: "Accedi al tuo registrar", desc: "Vai alla gestione domini del tuo provider." }, { title: "Avviare il trasferimento", desc: "Cerca l'opzione 'Trasferisci dominio' o 'Importa dominio'." }, { title: "Inserire il token di trasferimento", desc: "Incolla il token di trasferimento (codice EPP/Auth) ricevuto nel campo designato." }, { title: "Confermare il trasferimento", desc: "Inserisci il nome di dominio acquistato e conferma il trasferimento." }, { title: "Attendere il completamento", desc: "Il trasferimento richiede solitamente 1-5 giorni lavorativi." }, { title: "Usare il dominio", desc: "Dopo il completamento, usa il dominio immediatamente: redirect 301 o nuovo sito web." }], contactNote: "Domande sul trasferimento? Contattaci a" },
  pt: { title: "Como transferir seu domínio com o token de transferência (código EPP/Auth)?", intro: "Após a compra, você receberá um token de transferência (também chamado de código EPP ou Auth) em 24 horas no e-mail fornecido durante o pagamento.", stepsTitle: "Instruções passo a passo:", steps: [{ title: "Receber o token de transferência", desc: "Verifique sua caixa de entrada (e pasta de spam) para o e-mail com o token." }, { title: "Faça login no seu registrador", desc: "Acesse o gerenciamento de domínio do seu provedor." }, { title: "Iniciar a transferência", desc: "Procure a opção 'Transferir domínio' ou 'Importar domínio'." }, { title: "Inserir o token de transferência", desc: "Cole o token de transferência (código EPP/Auth) recebido no campo designado." }, { title: "Confirmar a transferência", desc: "Insira o nome de domínio comprado e confirme a transferência." }, { title: "Aguardar a conclusão", desc: "A transferência geralmente leva 1-5 dias úteis." }, { title: "Usar seu domínio", desc: "Após a conclusão, use o domínio imediatamente: redirecionamento 301 ou novo site." }], contactNote: "Dúvidas sobre a transferência? Entre em contato conosco em" },
  pl: { title: "Jak przenieść domenę za pomocą tokenu transferu (kodu EPP/Auth)?", intro: "Po zakupie otrzymasz token transferu (zwany również kodem EPP lub Auth) w ciągu 24 godzin na adres e-mail podany podczas płatności.", stepsTitle: "Instrukcja krok po kroku:", steps: [{ title: "Odbierz token transferu", desc: "Sprawdź skrzynkę odbiorczą (i folder spam) w poszukiwaniu e-maila z tokenem." }, { title: "Zaloguj się u swojego rejestratora", desc: "Przejdź do zarządzania domenami swojego dostawcy." }, { title: "Rozpocznij transfer domeny", desc: "Poszukaj opcji 'Przenieś domenę' lub 'Importuj domenę'." }, { title: "Wprowadź token transferu", desc: "Wklej otrzymany token transferu (kod EPP/Auth) w wyznaczonym polu." }, { title: "Potwierdź transfer", desc: "Wprowadź zakupioną nazwę domeny i potwierdź transfer." }, { title: "Poczekaj na zakończenie", desc: "Transfer trwa zazwyczaj 1-5 dni roboczych." }, { title: "Użyj swojej domeny", desc: "Po zakończeniu możesz natychmiast używać domeny: przekierowanie 301 lub nowa strona." }], contactNote: "Masz pytania dotyczące transferu domeny? Skontaktuj się z nami pod adresem" },
  tr: { title: "Transfer tokenı (EPP/Auth kodu) ile alan adınızı nasıl aktarırsınız?", intro: "Satın alma işleminizden sonra, ödeme sırasında verdiğiniz e-posta adresine 24 saat içinde bir transfer tokenı (EPP kodu veya Auth kodu olarak da bilinir) alacaksınız.", stepsTitle: "Adım adım talimatlar:", steps: [{ title: "Transfer tokenını alın", desc: "Gelen kutunuzu (ve spam klasörünü) transfer tokenı içeren e-posta için kontrol edin." }, { title: "Domain kayıt şirketinize giriş yapın", desc: "Sağlayıcınızın alan adı yönetimine gidin." }, { title: "Domain transferini başlatın", desc: "'Domain transfer' veya 'Domain içe aktar' seçeneğini arayın." }, { title: "Transfer tokenını girin", desc: "Aldığınız transfer tokenını (EPP/Auth kodu) belirtilen alana yapıştırın." }, { title: "Transferi onaylayın", desc: "Satın aldığınız alan adını girin ve transferi onaylayın." }, { title: "Tamamlanmasını bekleyin", desc: "Transfer genellikle 1-5 iş günü sürer." }, { title: "Alan adınızı kullanın", desc: "Tamamlandıktan sonra alan adını hemen kullanabilirsiniz." }], contactNote: "Transfer hakkında sorularınız mı var? Bize ulaşın:" },
  ar: { title: "كيف تنقل نطاقك باستخدام رمز النقل (EPP/Auth)؟", intro: "بعد الشراء، ستتلقى رمز نقل (يُعرف أيضًا بكود EPP أو Auth) خلال 24 ساعة على البريد الإلكتروني المقدم أثناء الدفع.", stepsTitle: "تعليمات خطوة بخطوة:", steps: [{ title: "استلام رمز النقل", desc: "تحقق من صندوق الوارد (ومجلد البريد العشوائي) للبريد الإلكتروني مع رمز النقل." }, { title: "سجل الدخول إلى مسجل النطاقات", desc: "انتقل إلى إدارة النطاقات لدى مزودك." }, { title: "ابدأ نقل النطاق", desc: "ابحث عن خيار 'نقل النطاق' أو 'استيراد النطاق'." }, { title: "أدخل رمز النقل", desc: "الصق رمز النقل (كود EPP/Auth) المستلم في الحقل المخصص." }, { title: "تأكيد النقل", desc: "أدخل اسم النطاق المشترى وأكد النقل." }, { title: "انتظر الاكتمال", desc: "يستغرق النقل عادة 1-5 أيام عمل." }, { title: "استخدم نطاقك", desc: "بعد الاكتمال يمكنك استخدام النطاق فورًا." }], contactNote: "هل لديك أسئلة حول نقل النطاق؟ تواصل معنا على" },
  hi: { title: "ट्रांसफर टोकन (EPP/Auth कोड) से अपना डोमेन कैसे ट्रांसफर करें?", intro: "खरीद के बाद, आपको भुगतान के दौरान दिए गए ईमेल पर 24 घंटे के भीतर ट्रांसफर टोकन (EPP कोड या Auth कोड) प्राप्त होगा।", stepsTitle: "चरण-दर-चरण निर्देश:", steps: [{ title: "ट्रांसफर टोकन प्राप्त करें", desc: "टोकन वाले ईमेल के लिए अपना इनबॉक्स (और स्पैम फ़ोल्डर) जांचें।" }, { title: "अपने डोमेन रजिस्ट्रार में लॉगिन करें", desc: "अपने प्रदाता के डोमेन प्रबंधन पर जाएं।" }, { title: "डोमेन ट्रांसफर शुरू करें", desc: "'डोमेन ट्रांसफर' या 'डोमेन आयात' विकल्प खोजें।" }, { title: "ट्रांसफर टोकन दर्ज करें", desc: "प्राप्त ट्रांसफर टोकन (EPP/Auth कोड) निर्दिष्ट फ़ील्ड में पेस्ट करें।" }, { title: "ट्रांसफर की पुष्टि करें", desc: "खरीदा गया डोमेन नाम दर्ज करें और ट्रांसफर की पुष्टि करें।" }, { title: "पूर्ण होने की प्रतीक्षा करें", desc: "ट्रांसफर आमतौर पर 1-5 कार्य दिवस लेता है।" }, { title: "अपना डोमेन उपयोग करें", desc: "पूर्ण होने के बाद, डोमेन तुरंत उपयोग करें।" }], contactNote: "डोमेन ट्रांसफर के बारे में प्रश्न? हमसे संपर्क करें:" },
  ja: { title: "転送トークン（EPP/Authコード）でドメインを移管する方法", intro: "購入後、お支払い時に提供されたメールアドレスに24時間以内に転送トークン（EPPコードまたはAuthコード）が届きます。", stepsTitle: "ステップバイステップの手順:", steps: [{ title: "転送トークンを受け取る", desc: "受信トレイ（迷惑メールフォルダ）でトークン付きメールを確認してください。" }, { title: "ドメインレジストラにログイン", desc: "プロバイダーのドメイン管理にアクセスしてください。" }, { title: "ドメイン移管を開始", desc: "「ドメイン移管」または「ドメインインポート」オプションを探してください。" }, { title: "転送トークンを入力", desc: "受け取った転送トークン（EPP/Authコード）を指定フィールドに貼り付けてください。" }, { title: "移管を確認", desc: "購入したドメイン名を入力して移管を確認してください。" }, { title: "完了を待つ", desc: "移管は通常1-5営業日かかります。" }, { title: "ドメインを使用", desc: "完了後、すぐにドメインを使用できます。" }], contactNote: "ドメイン移管についてご質問がありますか？お問い合わせ：" },
  zh: { title: "如何使用转移令牌（EPP/Auth代码）转移域名？", intro: "购买后，您将在24小时内收到转移令牌（也称为EPP代码或Auth代码），发送到您在付款时提供的电子邮件地址。", stepsTitle: "分步说明：", steps: [{ title: "接收转移令牌", desc: "检查您的收件箱（和垃圾邮件文件夹）中包含令牌的电子邮件。" }, { title: "登录您的域名注册商", desc: "转到您提供商的域名管理页面。" }, { title: "开始域名转移", desc: "寻找"转移域名"或"导入域名"选项。" }, { title: "输入转移令牌", desc: "将收到的转移令牌（EPP/Auth代码）粘贴到指定字段中。" }, { title: "确认转移", desc: "输入购买的域名并确认转移。" }, { title: "等待完成", desc: "转移通常需要1-5个工作日。" }, { title: "使用您的域名", desc: "完成后，您可以立即使用域名。" }], contactNote: "对域名转移有疑问？联系我们：" },
  sv: { title: "Hur överför du din domän med överföringstoken (EPP/Auth-kod)?", intro: "Efter ditt köp får du en överföringstoken (EPP-kod eller Auth-kod) inom 24 timmar till den e-postadress du angav vid betalning.", stepsTitle: "Steg-för-steg-instruktioner:", steps: [{ title: "Ta emot överföringstoken", desc: "Kontrollera din inkorg (och skräppostmapp) för e-posten med token." }, { title: "Logga in hos din domänregistrar", desc: "Gå till domänhantering hos din leverantör." }, { title: "Starta domänöverföring", desc: "Leta efter alternativet 'Överför domän' eller 'Importera domän'." }, { title: "Ange överföringstoken", desc: "Klistra in den mottagna token (EPP/Auth-koden) i det avsedda fältet." }, { title: "Bekräfta överföringen", desc: "Ange det köpta domännamnet och bekräfta överföringen." }, { title: "Vänta på slutförande", desc: "Överföringen tar vanligtvis 1-5 arbetsdagar." }, { title: "Använd din domän", desc: "Efter slutförande kan du använda domänen omedelbart." }], contactNote: "Frågor om domänöverföring? Kontakta oss på" },
  no: { title: "Hvordan overfører du domenet med overføringstoken (EPP/Auth-kode)?", intro: "Etter kjøpet mottar du en overføringstoken (EPP-kode eller Auth-kode) innen 24 timer til e-postadressen du oppga ved betaling.", stepsTitle: "Trinn-for-trinn-instruksjoner:", steps: [{ title: "Motta overføringstoken", desc: "Sjekk innboksen din (og spammappen) for e-posten med tokenet." }, { title: "Logg inn hos din domeneregistrar", desc: "Gå til domeneadministrasjon hos din leverandør." }, { title: "Start domeneoverføring", desc: "Se etter alternativet 'Overfør domene' eller 'Importer domene'." }, { title: "Skriv inn overføringstoken", desc: "Lim inn mottatt token (EPP/Auth-kode) i det angitte feltet." }, { title: "Bekreft overføringen", desc: "Skriv inn det kjøpte domenenavnet og bekreft overføringen." }, { title: "Vent på fullføring", desc: "Overføringen tar vanligvis 1-5 virkedager." }, { title: "Bruk domenet ditt", desc: "Etter fullføring kan du bruke domenet umiddelbart." }], contactNote: "Spørsmål om domeneoverføring? Kontakt oss på" },
  da: { title: "Hvordan overfører du dit domæne med overførselstoken (EPP/Auth-kode)?", intro: "Efter dit køb modtager du en overførselstoken (EPP-kode eller Auth-kode) inden for 24 timer på den e-mailadresse, du angav ved betaling.", stepsTitle: "Trin-for-trin-vejledning:", steps: [{ title: "Modtag overførselstoken", desc: "Tjek din indbakke (og spammappe) for e-mailen med tokenet." }, { title: "Log ind hos din domæneregistrar", desc: "Gå til domæneadministration hos din udbyder." }, { title: "Start domæneoverførsel", desc: "Se efter muligheden 'Overfør domæne' eller 'Importer domæne'." }, { title: "Indtast overførselstoken", desc: "Indsæt det modtagne token (EPP/Auth-kode) i det angivne felt." }, { title: "Bekræft overførslen", desc: "Indtast det købte domænenavn og bekræft overførslen." }, { title: "Vent på fuldførelse", desc: "Overførslen tager normalt 1-5 hverdage." }, { title: "Brug dit domæne", desc: "Efter fuldførelse kan du bruge domænet med det samme." }], contactNote: "Spørgsmål om domæneoverførsel? Kontakt os på" },
  fi: { title: "Miten siirrät verkkotunnuksesi siirtotunnuksella (EPP/Auth-koodi)?", intro: "Ostoksen jälkeen saat siirtotunnuksen (EPP-koodi tai Auth-koodi) 24 tunnin kuluessa maksun yhteydessä antamaasi sähköpostiosoitteeseen.", stepsTitle: "Vaiheittaiset ohjeet:", steps: [{ title: "Vastaanota siirtotunnus", desc: "Tarkista postilaatikkosi (ja roskapostikansio) tunnuksen sisältävän sähköpostin varalta." }, { title: "Kirjaudu verkkotunnusrekisteröijääsi", desc: "Siirry palveluntarjoajasi verkkotunnushallintaan." }, { title: "Aloita verkkotunnussiirto", desc: "Etsi vaihtoehto 'Siirrä verkkotunnus' tai 'Tuo verkkotunnus'." }, { title: "Syötä siirtotunnus", desc: "Liitä vastaanotettu tunnus (EPP/Auth-koodi) osoitettuun kenttään." }, { title: "Vahvista siirto", desc: "Syötä ostettu verkkotunnusnimi ja vahvista siirto." }, { title: "Odota valmistumista", desc: "Siirto kestää yleensä 1-5 arkipäivää." }, { title: "Käytä verkkotunnustasi", desc: "Valmistumisen jälkeen voit käyttää verkkotunnusta välittömästi." }], contactNote: "Kysyttävää verkkotunnussiirrosta? Ota yhteyttä osoitteeseen" },
  cs: { title: "Jak přenést doménu pomocí přenosového tokenu (EPP/Auth kód)?", intro: "Po nákupu obdržíte přenosový token (EPP kód nebo Auth kód) do 24 hodin na e-mailovou adresu uvedenou při platbě.", stepsTitle: "Návod krok za krokem:", steps: [{ title: "Přijměte přenosový token", desc: "Zkontrolujte doručenou poštu (a složku spam) pro e-mail s tokenem." }, { title: "Přihlaste se u svého registrátora", desc: "Přejděte do správy domén u vašeho poskytovatele." }, { title: "Zahajte přenos domény", desc: "Hledejte možnost 'Přenést doménu' nebo 'Importovat doménu'." }, { title: "Zadejte přenosový token", desc: "Vložte přijatý token (EPP/Auth kód) do určeného pole." }, { title: "Potvrďte přenos", desc: "Zadejte zakoupenou doménu a potvrďte přenos." }, { title: "Čekejte na dokončení", desc: "Přenos obvykle trvá 1-5 pracovních dnů." }, { title: "Použijte svou doménu", desc: "Po dokončení můžete doménu okamžitě použít." }], contactNote: "Dotazy k přenosu domény? Kontaktujte nás na" },
  el: { title: "Πώς μεταφέρετε το domain σας με το token μεταφοράς (κωδικός EPP/Auth);", intro: "Μετά την αγορά σας, θα λάβετε ένα token μεταφοράς εντός 24 ωρών στο email που δώσατε κατά την πληρωμή.", stepsTitle: "Οδηγίες βήμα προς βήμα:", steps: [{ title: "Λάβετε το token μεταφοράς", desc: "Ελέγξτε τα εισερχόμενα (και τον φάκελο spam) για το email με το token." }, { title: "Συνδεθείτε στον καταχωρητή σας", desc: "Μεταβείτε στη διαχείριση domain του παρόχου σας." }, { title: "Ξεκινήστε τη μεταφορά", desc: "Αναζητήστε την επιλογή 'Μεταφορά domain'." }, { title: "Εισάγετε το token", desc: "Επικολλήστε το token (κωδικός EPP/Auth) στο κατάλληλο πεδίο." }, { title: "Επιβεβαιώστε τη μεταφορά", desc: "Εισάγετε το αγορασμένο domain και επιβεβαιώστε." }, { title: "Περιμένετε ολοκλήρωση", desc: "Η μεταφορά διαρκεί συνήθως 1-5 εργάσιμες ημέρες." }, { title: "Χρησιμοποιήστε το domain", desc: "Μετά την ολοκλήρωση μπορείτε να χρησιμοποιήσετε το domain αμέσως." }], contactNote: "Ερωτήσεις σχετικά με τη μεταφορά; Επικοινωνήστε μαζί μας στο" },
  ru: { title: "Как перенести домен с помощью токена переноса (EPP/Auth код)?", intro: "После покупки вы получите токен переноса (EPP код или Auth код) в течение 24 часов на указанный при оплате email.", stepsTitle: "Пошаговая инструкция:", steps: [{ title: "Получите токен переноса", desc: "Проверьте почту (и папку спам) на наличие письма с токеном." }, { title: "Войдите в аккаунт регистратора", desc: "Перейдите в управление доменами вашего провайдера." }, { title: "Начните перенос домена", desc: "Найдите опцию 'Перенести домен' или 'Импортировать домен'." }, { title: "Введите токен переноса", desc: "Вставьте полученный токен (EPP/Auth код) в соответствующее поле." }, { title: "Подтвердите перенос", desc: "Введите купленное доменное имя и подтвердите перенос." }, { title: "Дождитесь завершения", desc: "Перенос обычно занимает 1-5 рабочих дней." }, { title: "Используйте домен", desc: "После завершения вы можете сразу использовать домен." }], contactNote: "Вопросы о переносе домена? Свяжитесь с нами:" },
  ro: { title: "Cum transferați domeniul cu tokenul de transfer (cod EPP/Auth)?", intro: "După achiziție, veți primi un token de transfer în 24 de ore la adresa de email furnizată la plată.", stepsTitle: "Instrucțiuni pas cu pas:", steps: [{ title: "Primiți tokenul de transfer", desc: "Verificați inbox-ul (și folderul spam) pentru emailul cu tokenul." }, { title: "Conectați-vă la registrar", desc: "Accesați managementul domeniilor la furnizorul dvs." }, { title: "Începeți transferul", desc: "Căutați opțiunea 'Transferă domeniu' sau 'Importă domeniu'." }, { title: "Introduceți tokenul", desc: "Lipiți tokenul primit (cod EPP/Auth) în câmpul desemnat." }, { title: "Confirmați transferul", desc: "Introduceți domeniul achiziționat și confirmați transferul." }, { title: "Așteptați finalizarea", desc: "Transferul durează de obicei 1-5 zile lucrătoare." }, { title: "Utilizați domeniul", desc: "După finalizare, puteți utiliza domeniul imediat." }], contactNote: "Întrebări despre transfer? Contactați-ne la" },
  bg: { title: "Как да прехвърлите домейна си с токен за трансфер (EPP/Auth код)?", intro: "След покупката ще получите токен за трансфер в рамките на 24 часа на имейла, предоставен при плащането.", stepsTitle: "Инструкции стъпка по стъпка:", steps: [{ title: "Получете токена за трансфер", desc: "Проверете входящата поща (и папка спам) за имейла с токена." }, { title: "Влезте в акаунта на регистратора", desc: "Отидете в управлението на домейни при вашия доставчик." }, { title: "Започнете трансфера", desc: "Потърсете опцията 'Прехвърли домейн' или 'Импортирай домейн'." }, { title: "Въведете токена", desc: "Поставете получения токен (EPP/Auth код) в определеното поле." }, { title: "Потвърдете трансфера", desc: "Въведете закупеното домейн име и потвърдете трансфера." }, { title: "Изчакайте завършване", desc: "Трансферът обикновено отнема 1-5 работни дни." }, { title: "Използвайте домейна", desc: "След завършване можете да използвате домейна незабавно." }], contactNote: "Въпроси за трансфера? Свържете се с нас на" },
  uk: { title: "Як перенести домен за допомогою токена переносу (EPP/Auth код)?", intro: "Після покупки ви отримаєте токен переносу протягом 24 годин на email, вказаний при оплаті.", stepsTitle: "Покрокова інструкція:", steps: [{ title: "Отримайте токен переносу", desc: "Перевірте пошту (та папку спам) на лист з токеном." }, { title: "Увійдіть до реєстратора", desc: "Перейдіть до управління доменами вашого провайдера." }, { title: "Розпочніть перенос", desc: "Знайдіть опцію 'Перенести домен' або 'Імпортувати домен'." }, { title: "Введіть токен", desc: "Вставте отриманий токен (EPP/Auth код) у відповідне поле." }, { title: "Підтвердіть перенос", desc: "Введіть придбане доменне ім'я та підтвердіть перенос." }, { title: "Дочекайтеся завершення", desc: "Перенос зазвичай займає 1-5 робочих днів." }, { title: "Використовуйте домен", desc: "Після завершення можете відразу використовувати домен." }], contactNote: "Запитання про перенос домену? Зв'яжіться з нами:" },
  hr: { title: "Kako prenijeti domenu s tokenom za prijenos (EPP/Auth kod)?", intro: "Nakon kupnje, primit ćete token za prijenos u roku od 24 sata na e-mail adresu navedenu pri plaćanju.", stepsTitle: "Upute korak po korak:", steps: [{ title: "Primite token za prijenos", desc: "Provjerite inbox (i spam mapu) za e-mail s tokenom." }, { title: "Prijavite se kod registrara", desc: "Idite na upravljanje domenama kod vašeg pružatelja." }, { title: "Pokrenite prijenos", desc: "Potražite opciju 'Prenesi domenu' ili 'Uvezi domenu'." }, { title: "Unesite token", desc: "Zalijepite primljeni token (EPP/Auth kod) u predviđeno polje." }, { title: "Potvrdite prijenos", desc: "Unesite kupljeno ime domene i potvrdite prijenos." }, { title: "Pričekajte završetak", desc: "Prijenos obično traje 1-5 radnih dana." }, { title: "Koristite domenu", desc: "Nakon završetka možete odmah koristiti domenu." }], contactNote: "Pitanja o prijenosu? Kontaktirajte nas na" },
  sk: { title: "Ako preniesť doménu pomocou prenosového tokenu (EPP/Auth kód)?", intro: "Po nákupe obdržíte prenosový token do 24 hodín na e-mailovú adresu uvedenú pri platbe.", stepsTitle: "Návod krok za krokom:", steps: [{ title: "Prijmite prenosový token", desc: "Skontrolujte doručenú poštu (a priečinok spam) na e-mail s tokenom." }, { title: "Prihláste sa u registrátora", desc: "Prejdite do správy domén u vášho poskytovateľa." }, { title: "Spustite prenos", desc: "Hľadajte možnosť 'Preniesť doménu' alebo 'Importovať doménu'." }, { title: "Zadajte token", desc: "Vložte prijatý token (EPP/Auth kód) do určeného poľa." }, { title: "Potvrďte prenos", desc: "Zadajte zakúpenú doménu a potvrďte prenos." }, { title: "Počkajte na dokončenie", desc: "Prenos zvyčajne trvá 1-5 pracovných dní." }, { title: "Použite svoju doménu", desc: "Po dokončení môžete doménu okamžite použiť." }], contactNote: "Otázky k prenosu domény? Kontaktujte nás na" },
  sr: { title: "Како пренети домен помоћу токена за пренос (EPP/Auth код)?", intro: "Након куповине, примићете токен за пренос у року од 24 сата на е-маил адресу наведену при плаћању.", stepsTitle: "Упутства корак по корак:", steps: [{ title: "Примите токен за пренос", desc: "Проверите пријемно сандуче (и спам фасциклу) за е-маил са токеном." }, { title: "Пријавите се код регистратора", desc: "Идите на управљање доменима код вашег провајдера." }, { title: "Покрените пренос", desc: "Потражите опцију 'Пренеси домен' или 'Увези домен'." }, { title: "Унесите токен", desc: "Налепите примљени токен (EPP/Auth код) у предвиђено поље." }, { title: "Потврдите пренос", desc: "Унесите купљено име домена и потврдите пренос." }, { title: "Сачекајте завршетак", desc: "Пренос обично траје 1-5 радних дана." }, { title: "Користите домен", desc: "Након завршетка можете одмах користити домен." }], contactNote: "Питања о преносу? Контактирајте нас на" },
  sl: { title: "Kako prenesti domeno s prenosnim žetonom (EPP/Auth koda)?", intro: "Po nakupu boste prejeli prenosni žeton v 24 urah na e-naslov, naveden pri plačilu.", stepsTitle: "Navodila korak za korakom:", steps: [{ title: "Prejmite prenosni žeton", desc: "Preverite nabiralnik (in mapo z neželeno pošto) za e-pošto z žetonom." }, { title: "Prijavite se pri registrarju", desc: "Pojdite na upravljanje domen pri vašem ponudniku." }, { title: "Začnite prenos", desc: "Poiščite možnost 'Prenesi domeno' ali 'Uvozi domeno'." }, { title: "Vnesite žeton", desc: "Prilepite prejeti žeton (EPP/Auth kodo) v ustrezno polje." }, { title: "Potrdite prenos", desc: "Vnesite kupljeno domeno in potrdite prenos." }, { title: "Počakajte na dokončanje", desc: "Prenos običajno traja 1-5 delovnih dni." }, { title: "Uporabite domeno", desc: "Po dokončanju lahko takoj uporabite domeno." }], contactNote: "Vprašanja o prenosu? Kontaktirajte nas na" },
  ko: { title: "이전 토큰(EPP/Auth 코드)으로 도메인을 이전하는 방법", intro: "구매 후 결제 시 제공한 이메일 주소로 24시간 이내에 이전 토큰(EPP 코드 또는 Auth 코드)을 받게 됩니다.", stepsTitle: "단계별 안내:", steps: [{ title: "이전 토큰 수신", desc: "받은편지함(및 스팸 폴더)에서 토큰이 포함된 이메일을 확인하세요." }, { title: "도메인 등록기관에 로그인", desc: "제공업체의 도메인 관리로 이동하세요." }, { title: "도메인 이전 시작", desc: "'도메인 이전' 또는 '도메인 가져오기' 옵션을 찾으세요." }, { title: "이전 토큰 입력", desc: "받은 이전 토큰(EPP/Auth 코드)을 지정된 필드에 붙여넣으세요." }, { title: "이전 확인", desc: "구매한 도메인 이름을 입력하고 이전을 확인하세요." }, { title: "완료 대기", desc: "이전은 보통 1-5 영업일 소요됩니다." }, { title: "도메인 사용", desc: "완료 후 즉시 도메인을 사용할 수 있습니다." }], contactNote: "도메인 이전에 대한 질문이 있으신가요? 연락처:" },
  hu: { title: "Hogyan vigye át domainjét az átviteli tokennel (EPP/Auth kód)?", intro: "Vásárlás után 24 órán belül megkapja az átviteli tokent (EPP kód vagy Auth kód) a fizetésnél megadott e-mail címre.", stepsTitle: "Lépésről lépésre:", steps: [{ title: "Fogadja az átviteli tokent", desc: "Ellenőrizze postaládáját (és spam mappáját) a tokent tartalmazó e-mailért." }, { title: "Jelentkezzen be a regisztrátornál", desc: "Lépjen a szolgáltatója domainkezelésébe." }, { title: "Indítsa el az átvitelt", desc: "Keresse a 'Domain átvitel' vagy 'Domain importálás' lehetőséget." }, { title: "Adja meg a tokent", desc: "Illessze be a kapott tokent (EPP/Auth kód) a kijelölt mezőbe." }, { title: "Erősítse meg az átvitelt", desc: "Adja meg a vásárolt domainnevet és erősítse meg az átvitelt." }, { title: "Várjon a befejezésre", desc: "Az átvitel általában 1-5 munkanapot vesz igénybe." }, { title: "Használja domainját", desc: "Befejezés után azonnal használhatja a domaint." }], contactNote: "Kérdése van az átvitelről? Lépjen kapcsolatba velünk:" },
  th: { title: "วิธีโอนโดเมนด้วยโทเค็นการโอน (รหัส EPP/Auth)", intro: "หลังจากการซื้อ คุณจะได้รับโทเค็นการโอน (รหัส EPP หรือ Auth) ภายใน 24 ชั่วโมงทางอีเมลที่ระบุตอนชำระเงิน", stepsTitle: "คำแนะนำทีละขั้นตอน:", steps: [{ title: "รับโทเค็นการโอน", desc: "ตรวจสอบกล่องจดหมาย (และโฟลเดอร์สแปม) สำหรับอีเมลที่มีโทเค็น" }, { title: "ล็อกอินที่ผู้จดทะเบียนโดเมน", desc: "ไปที่การจัดการโดเมนของผู้ให้บริการ" }, { title: "เริ่มการโอนโดเมน", desc: "ค้นหาตัวเลือก 'โอนโดเมน' หรือ 'นำเข้าโดเมน'" }, { title: "ป้อนโทเค็นการโอน", desc: "วางโทเค็น (รหัส EPP/Auth) ที่ได้รับในช่องที่กำหนด" }, { title: "ยืนยันการโอน", desc: "ป้อนชื่อโดเมนที่ซื้อและยืนยันการโอน" }, { title: "รอการดำเนินการเสร็จสิ้น", desc: "การโอนใช้เวลา 1-5 วันทำการ" }, { title: "ใช้โดเมนของคุณ", desc: "หลังจากเสร็จสิ้นคุณสามารถใช้โดเมนได้ทันที" }], contactNote: "มีคำถามเกี่ยวกับการโอน? ติดต่อเราที่" },
  vi: { title: "Cách chuyển tên miền bằng mã chuyển nhượng (EPP/Auth)?", intro: "Sau khi mua, bạn sẽ nhận được mã chuyển nhượng (mã EPP hoặc Auth) trong vòng 24 giờ qua email đã cung cấp khi thanh toán.", stepsTitle: "Hướng dẫn từng bước:", steps: [{ title: "Nhận mã chuyển nhượng", desc: "Kiểm tra hộp thư đến (và thư rác) để tìm email chứa mã." }, { title: "Đăng nhập vào nhà đăng ký", desc: "Truy cập quản lý tên miền của nhà cung cấp." }, { title: "Bắt đầu chuyển", desc: "Tìm tùy chọn 'Chuyển tên miền' hoặc 'Nhập tên miền'." }, { title: "Nhập mã chuyển nhượng", desc: "Dán mã nhận được (EPP/Auth) vào trường được chỉ định." }, { title: "Xác nhận chuyển nhượng", desc: "Nhập tên miền đã mua và xác nhận chuyển nhượng." }, { title: "Chờ hoàn tất", desc: "Quá trình chuyển thường mất 1-5 ngày làm việc." }, { title: "Sử dụng tên miền", desc: "Sau khi hoàn tất, bạn có thể sử dụng tên miền ngay lập tức." }], contactNote: "Câu hỏi về chuyển nhượng? Liên hệ chúng tôi tại" },
  id: { title: "Cara mentransfer domain Anda dengan token transfer (kode EPP/Auth)?", intro: "Setelah pembelian, Anda akan menerima token transfer (kode EPP atau Auth) dalam 24 jam di email yang diberikan saat pembayaran.", stepsTitle: "Petunjuk langkah demi langkah:", steps: [{ title: "Terima token transfer", desc: "Periksa kotak masuk (dan folder spam) untuk email dengan token." }, { title: "Login ke registrar domain", desc: "Buka manajemen domain di penyedia Anda." }, { title: "Mulai transfer domain", desc: "Cari opsi 'Transfer domain' atau 'Impor domain'." }, { title: "Masukkan token transfer", desc: "Tempel token yang diterima (kode EPP/Auth) di kolom yang ditentukan." }, { title: "Konfirmasi transfer", desc: "Masukkan nama domain yang dibeli dan konfirmasi transfer." }, { title: "Tunggu penyelesaian", desc: "Transfer biasanya memakan waktu 1-5 hari kerja." }, { title: "Gunakan domain Anda", desc: "Setelah selesai, Anda dapat menggunakan domain segera." }], contactNote: "Pertanyaan tentang transfer? Hubungi kami di" },
  et: { title: "Kuidas domeeni ülekande tokeniga (EPP/Auth kood) üle kanda?", intro: "Pärast ostu saate ülekande tokeni (EPP koodi või Auth koodi) 24 tunni jooksul maksmise ajal esitatud e-posti aadressile.", stepsTitle: "Samm-sammult juhised:", steps: [{ title: "Võtke ülekande token vastu", desc: "Kontrollige postkasti (ja rämpsposti kausta) tokeniga e-kirja osas." }, { title: "Logige sisse oma registripidajasse", desc: "Minge oma teenusepakkuja domeenihaldusesse." }, { title: "Alustage domeeni ülekandmist", desc: "Otsige valikut 'Kanna domeen üle' või 'Impordi domeen'." }, { title: "Sisestage token", desc: "Kleepige saadud token (EPP/Auth kood) määratud väljale." }, { title: "Kinnitage ülekanne", desc: "Sisestage ostetud domeeninimi ja kinnitage ülekanne." }, { title: "Oodake lõpetamist", desc: "Ülekanne võtab tavaliselt 1-5 tööpäeva." }, { title: "Kasutage oma domeeni", desc: "Pärast lõpetamist saate domeeni kohe kasutada." }], contactNote: "Küsimusi ülekande kohta? Võtke meiega ühendust:" },
  lv: { title: "Kā pārsūtīt domēnu ar pārsūtīšanas tokenu (EPP/Auth kods)?", intro: "Pēc pirkuma jūs saņemsiet pārsūtīšanas tokenu 24 stundu laikā uz maksājuma laikā norādīto e-pastu.", stepsTitle: "Pakāpeniskas instrukcijas:", steps: [{ title: "Saņemiet tokenu", desc: "Pārbaudiet iesūtni (un surogātpasta mapi) attiecībā uz e-pastu ar tokenu." }, { title: "Piesakieties reģistratūrā", desc: "Dodieties uz domēnu pārvaldību pie sava pakalpojumu sniedzēja." }, { title: "Sāciet pārsūtīšanu", desc: "Meklējiet opciju 'Pārsūtīt domēnu' vai 'Importēt domēnu'." }, { title: "Ievadiet tokenu", desc: "Ielīmējiet saņemto tokenu (EPP/Auth kods) norādītajā laukā." }, { title: "Apstipriniet pārsūtīšanu", desc: "Ievadiet iegādāto domēna nosaukumu un apstipriniet." }, { title: "Gaidiet pabeigšanu", desc: "Pārsūtīšana parasti aizņem 1-5 darba dienas." }, { title: "Izmantojiet domēnu", desc: "Pēc pabeigšanas varat uzreiz izmantot domēnu." }], contactNote: "Jautājumi par pārsūtīšanu? Sazinieties ar mums:" },
  lt: { title: "Kaip perkelti domeną naudojant perdavimo ženklą (EPP/Auth kodas)?", intro: "Po pirkimo gausite perdavimo ženklą per 24 valandas nurodytu el. pašto adresu.", stepsTitle: "Žingsnis po žingsnio:", steps: [{ title: "Gaukite perdavimo ženklą", desc: "Patikrinkite gautųjų dėžutę (ir šlamšto aplanką) dėl el. laiško su ženklu." }, { title: "Prisijunkite prie registratoriaus", desc: "Eikite į domenų valdymą pas savo tiekėją." }, { title: "Pradėkite perkėlimą", desc: "Ieškokite parinkties 'Perkelti domeną' arba 'Importuoti domeną'." }, { title: "Įveskite ženklą", desc: "Įklijuokite gautą ženklą (EPP/Auth kodą) į nurodytą laukelį." }, { title: "Patvirtinkite perkėlimą", desc: "Įveskite įsigytą domeno pavadinimą ir patvirtinkite." }, { title: "Palaukite užbaigimo", desc: "Perkėlimas paprastai trunka 1-5 darbo dienas." }, { title: "Naudokite domeną", desc: "Po užbaigimo galite iš karto naudoti domeną." }], contactNote: "Klausimai apie perkėlimą? Susisiekite su mumis:" },
  is: { title: "Hvernig flytja lén með flutningsmerki (EPP/Auth kóða)?", intro: "Eftir kaup færðu flutningsmerki innan 24 klukkustunda á netfangið sem þú gafst upp við greiðslu.", stepsTitle: "Skref-fyrir-skref leiðbeiningar:", steps: [{ title: "Fáðu flutningsmerki", desc: "Athugaðu innhólf (og ruslpóstmöppu) fyrir tölvupóstinn með merkinu." }, { title: "Skráðu þig inn hjá skráningaraðila", desc: "Farðu í lénastjórnun hjá þjónustuveitanda þínum." }, { title: "Byrjaðu flutning", desc: "Leitaðu að valkostinum 'Flytja lén' eða 'Flytja inn lén'." }, { title: "Sláðu inn merkið", desc: "Límdu móttekið merki (EPP/Auth kóða) í viðeigandi reit." }, { title: "Staðfestu flutninginn", desc: "Sláðu inn keypt lénsnafn og staðfestu flutninginn." }, { title: "Bíddu eftir lokum", desc: "Flutningurinn tekur venjulega 1-5 virka daga." }, { title: "Notaðu lénið þitt", desc: "Eftir lok geturðu notað lénið strax." }], contactNote: "Spurningar um flutning? Hafðu samband:" },
  sq: { title: "Si ta transferoni domenin me tokenin e transferimit (kodi EPP/Auth)?", intro: "Pas blerjes, do të merrni një token transferimi brenda 24 orëve në emailin e dhënë gjatë pagesës.", stepsTitle: "Udhëzime hap pas hapi:", steps: [{ title: "Merrni tokenin", desc: "Kontrolloni kutinë postare (dhe dosjen spam) për emailin me tokenin." }, { title: "Identifikohuni tek regjistruesi", desc: "Shkoni te menaxhimi i domeneve tek ofruesi juaj." }, { title: "Filloni transferimin", desc: "Kërkoni opsionin 'Transfero domenin' ose 'Importo domenin'." }, { title: "Vendosni tokenin", desc: "Ngjisni tokenin e marrë (kodin EPP/Auth) në fushën e caktuar." }, { title: "Konfirmoni transferimin", desc: "Vendosni emrin e domenit të blerë dhe konfirmoni." }, { title: "Prisni përfundimin", desc: "Transferimi zakonisht zgjat 1-5 ditë pune." }, { title: "Përdorni domenin", desc: "Pas përfundimit mund ta përdorni domenin menjëherë." }], contactNote: "Pyetje rreth transferimit? Na kontaktoni në" },
  mk: { title: "Како да го пренесете доменот со токен за пренос (EPP/Auth код)?", intro: "По купувањето, ќе добиете токен за пренос во рок од 24 часа на е-поштата наведена при плаќањето.", stepsTitle: "Упатства чекор по чекор:", steps: [{ title: "Примете го токенот", desc: "Проверете го inbox-от (и spam папката) за е-поштата со токенот." }, { title: "Најавете се кај регистрарот", desc: "Одете во управувањето со домени кај вашиот провајдер." }, { title: "Започнете пренос", desc: "Побарајте ја опцијата 'Пренеси домен' или 'Увези домен'." }, { title: "Внесете го токенот", desc: "Залепете го примениот токен (EPP/Auth код) во определеното поле." }, { title: "Потврдете го преносот", desc: "Внесете го купеното домен име и потврдете." }, { title: "Почекајте завршување", desc: "Преносот обично трае 1-5 работни дена." }, { title: "Користете го доменот", desc: "По завршувањето можете веднаш да го користите доменот." }], contactNote: "Прашања за преносот? Контактирајте не на" },
  bs: { title: "Kako prenijeti domenu s tokenom za prijenos (EPP/Auth kod)?", intro: "Nakon kupovine, primit ćete token za prijenos u roku od 24 sata na e-mail adresu navedenu pri plaćanju.", stepsTitle: "Upute korak po korak:", steps: [{ title: "Primite token", desc: "Provjerite inbox (i spam folder) za e-mail s tokenom." }, { title: "Prijavite se kod registrara", desc: "Idite na upravljanje domenama kod vašeg pružatelja." }, { title: "Pokrenite prijenos", desc: "Potražite opciju 'Prenesi domenu' ili 'Uvezi domenu'." }, { title: "Unesite token", desc: "Zalijepite primljeni token (EPP/Auth kod) u predviđeno polje." }, { title: "Potvrdite prijenos", desc: "Unesite kupljeno ime domene i potvrdite." }, { title: "Sačekajte završetak", desc: "Prijenos obično traje 1-5 radnih dana." }, { title: "Koristite domenu", desc: "Nakon završetka možete odmah koristiti domenu." }], contactNote: "Pitanja o prijenosu? Kontaktirajte nas na" },
  lb: { title: "Wéi Dir Ären Domain mat dem Transfertoken (EPP/Auth Code) transferéiert?", intro: "No Ärem Kaf kritt Dir den Transfertoken bannent 24 Stonnen op d'E-Mail Adress déi Dir bei der Bezuelung uginn hutt.", stepsTitle: "Schrëtt-fir-Schrëtt Instruktioune:", steps: [{ title: "Transfertoken empfänken", desc: "Kuckt Ären Inbox (an Spam-Dossier) fir d'E-Mail mam Token." }, { title: "Loggt Iech an bei Ärem Registrar", desc: "Gitt op d'Domainverwaltung vun Ärem Provider." }, { title: "Start den Transfer", desc: "Sicht d'Optioun 'Domain transferéieren' oder 'Domain importéieren'." }, { title: "Gitt den Token an", desc: "Paste den empfaangenen Token (EPP/Auth Code) am virgesinnene Feld." }, { title: "Bestätegt den Transfer", desc: "Gitt den kaaften Domainnumm an a bestätegt den Transfer." }, { title: "Waart op d'Ofschloss", desc: "Den Transfer dauert normalerweis 1-5 Aarbechtsdéeg." }, { title: "Benotzt Ären Domain", desc: "No der Ofschloss kënnt Dir den Domain direkt benotzen." }], contactNote: "Froen zum Transfer? Kontaktéiert eis op" },
  bn: { title: "ট্রান্সফার টোকেন (EPP/Auth কোড) দিয়ে ডোমেইন কীভাবে ট্রান্সফার করবেন?", intro: "কেনার পরে, আপনি পেমেন্টের সময় দেওয়া ইমেইলে 24 ঘণ্টার মধ্যে ট্রান্সফার টোকেন (EPP কোড বা Auth কোড) পাবেন।", stepsTitle: "ধাপে ধাপে নির্দেশনা:", steps: [{ title: "ট্রান্সফার টোকেন গ্রহণ করুন", desc: "টোকেন সহ ইমেইলের জন্য ইনবক্স (এবং স্প্যাম ফোল্ডার) চেক করুন।" }, { title: "রেজিস্ট্রারে লগইন করুন", desc: "আপনার প্রদানকারীর ডোমেইন ব্যবস্থাপনায় যান।" }, { title: "ডোমেইন ট্রান্সফার শুরু করুন", desc: "'ডোমেইন ট্রান্সফার' বা 'ডোমেইন ইম্পোর্ট' অপশন খুঁজুন।" }, { title: "টোকেন প্রবেশ করান", desc: "প্রাপ্ত টোকেন (EPP/Auth কোড) নির্দিষ্ট ক্ষেত্রে পেস্ট করুন।" }, { title: "ট্রান্সফার নিশ্চিত করুন", desc: "কেনা ডোমেইন নাম লিখুন এবং ট্রান্সফার নিশ্চিত করুন।" }, { title: "সম্পূর্ণ হওয়ার অপেক্ষা করুন", desc: "ট্রান্সফার সাধারণত ১-৫ কার্যদিবস সময় নেয়।" }, { title: "আপনার ডোমেইন ব্যবহার করুন", desc: "সম্পূর্ণ হওয়ার পর, আপনি অবিলম্বে ডোমেইন ব্যবহার করতে পারবেন।" }], contactNote: "ট্রান্সফার সম্পর্কে প্রশ্ন? যোগাযোগ করুন:" },
  ms: { title: "Bagaimana memindahkan domain anda dengan token pemindahan (kod EPP/Auth)?", intro: "Selepas pembelian, anda akan menerima token pemindahan dalam masa 24 jam pada alamat e-mel yang diberikan semasa pembayaran.", stepsTitle: "Arahan langkah demi langkah:", steps: [{ title: "Terima token pemindahan", desc: "Semak peti masuk (dan folder spam) untuk e-mel dengan token." }, { title: "Log masuk ke pendaftar domain", desc: "Pergi ke pengurusan domain di pembekal anda." }, { title: "Mulakan pemindahan", desc: "Cari pilihan 'Pindah domain' atau 'Import domain'." }, { title: "Masukkan token", desc: "Tampal token yang diterima (kod EPP/Auth) dalam medan yang ditetapkan." }, { title: "Sahkan pemindahan", desc: "Masukkan nama domain yang dibeli dan sahkan pemindahan." }, { title: "Tunggu penyelesaian", desc: "Pemindahan biasanya mengambil masa 1-5 hari bekerja." }, { title: "Gunakan domain anda", desc: "Selepas selesai, anda boleh menggunakan domain dengan segera." }], contactNote: "Soalan tentang pemindahan? Hubungi kami di" },
};

const DomainTransferSection = ({ lang }: { lang: string }) => {
  const l = t[lang as Lang] || t.en;
  return (
    <section id="domain-transfer" className="py-16 bg-slate-900">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <div className="border border-amber-500/30 rounded-xl bg-slate-800/50">
            <div className="px-6 py-4">
              <h2 className="text-xl font-bold text-white">
                <div className="flex items-center gap-3">
                  <Globe className="w-6 h-6 text-amber-400" />
                  <span>{l.title}</span>
                </div>
              </h2>
            </div>
            <div className="px-6 pb-6">
              <div className="space-y-6 text-slate-300">
                <p className="text-lg">{l.intro}</p>
                <div className="bg-slate-900/50 rounded-lg p-6 border border-slate-700">
                  <h3 className="text-lg font-semibold text-white mb-4">{l.stepsTitle}</h3>
                  <ol className="space-y-4">
                    {l.steps.map((step, i) => (
                      <li key={i} className="flex gap-3">
                        <span className="flex-shrink-0 w-8 h-8 rounded-full bg-amber-500 text-slate-950 font-bold flex items-center justify-center">{i + 1}</span>
                        <div>
                          <strong className="text-white">{step.title}</strong>
                          <p className="text-slate-400 mt-1">{step.desc}</p>
                        </div>
                      </li>
                    ))}
                  </ol>
                </div>
                <p className="text-slate-400 text-sm">
                  {l.contactNote} <a href="mailto:support@iaee.eu" className="text-amber-400 hover:text-amber-300">support@iaee.eu</a>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DomainTransferSection;
