interface FaqItem { question: string; answer: string; }
interface FaqData { sectionTitle: string; faqs: FaqItem[]; }

const mk35 = (qs: string[], as: string[]): FaqItem[] => qs.map((q, i) => ({ question: `${i+1}. ${q}`, answer: as[i] }));

export const faqTranslationsRemaining: Record<string, { title: string; qs: string[]; as: string[] }> = {
  fi: {
    title: "Täydellinen opas: 35 kysymystä vanhentuneista verkkotunnuksista ja SEO:sta",
    qs: [
      "Mikä verkkotunnus minun pitäisi ostaa aloittelijana?", "Mitä eroa on uudella ja vanhentuneella verkkotunnuksella?", "Onko parempi ostaa uusi vai vanhentunut verkkotunnus?", "Miksi uusi verkkosivustoni sijoittuu niin huonosti Googlessa?", "Onko vanhentuneen verkkotunnuksen ostaminen turvallista?", "Mitä tarkoittaa verkkotunnus, jolla on hyviä käänteisiä linkkejä?", "Miksi käänteiset linkit ovat tärkeitä verkkotunnusta ostettaessa?", "Mistä tiedän, onko vanhentunut verkkotunnus luotettava?", "Voinko käyttää vanhentunutta verkkotunnusta uudelle verkkosivustolle?", "Sopiiko vanhentunut verkkotunnus aloittelijoille?", "Miksi jotkut verkkotunnukset ovat kalliimpia kuin toiset?", "Voinko myydä vanhentuneen verkkotunnuksen myöhemmin?", "Voiko vanhentunut verkkotunnus olla huono SEO:lle?", "Mihin minun tulisi kiinnittää huomiota vanhentunutta verkkotunnusta ostettaessa?", "Kuinka nopeasti voin aloittaa verkkotunnuksen ostamisen jälkeen?", "Tarvitsenko teknistä osaamista vanhentuneen verkkotunnuksen käyttämiseen?", "Sopiiko vanhentunut verkkotunnus verkkokauppaan?", "Mitä verkkotunnuksen auktoriteetti tarkoittaa verkkotunnusta ostettaessa?", "Onko vanhentunut verkkotunnus parempi kuin linkkien rakentaminen?", "Kuinka paljon hyvä vanhentunut verkkotunnus maksaa?", "Onko verkkotunnukseni avainsana tärkeä SEO:lle?", "Voinko käyttää vanhentunutta verkkotunnusta kumppanuusverkkosivustolle?", "Entä jos Google on rangaissut vanhentunutta verkkotunnusta?", "Kuinka siirrän ostetun verkkotunnuksen omaan webhotelliini?", "Onko .fi tai .eu verkkotunnus parempi kuin .com?", "Voinko ohjata vanhentuneen verkkotunnuksen olemassa olevalle verkkosivustolleni?", "Kuinka kauan kestää, ennen kuin vanhentunut verkkotunnus sijoittuu Googlessa?", "Mitkä ovat vanhentuneen verkkotunnuksen edut uuteen verkkotunnukseen verrattuna?", "Voinko luottaa satunnaisen markkinapaikan vanhentuneeseen verkkotunnukseen?", "Mistä tiedän, onko verkkotunnuksella arvokkaita käänteisiä linkkejä?", "Onko vanhentuneeseen verkkotunnukseen sijoittaminen hyvä idea?", "Mitä tapahtuu vanhoille käänteisille linkeille, kun rakennan uuden verkkosivuston?", "Voinko käyttää vanhentunutta verkkotunnusta paikalliseen liiketoimintaan?", "Liittyykö vanhentuneen verkkotunnuksen ostamiseen riskejä?", "Miksi ostaa erikoistuneelta vanhentuneiden verkkotunnusten myyjältä?"
    ],
    as: [
      "Aloittelijana kannattaa valita verkkotunnus, joka on helppo muistaa ja herättää luottamusta. Luotettavalla vanhentuneella verkkotunnuksella on usein jo vakiintunut auktoriteetti.", "Uudella verkkotunnuksella ei ole historiaa. Vanhentunut verkkotunnus on rekisteröity aiemmin, ja sillä voi edelleen olla käänteisiä linkkejä ja Googlen luottamus.", "Brändäyksessä uusi nimi voi toimia, mutta Googlessa nopeammin löytymiseksi hyvä vanhentunut verkkotunnus tarjoaa selvän edun.", "Uusien sivustojen on rakennettava luotettavuutensa. Ilman käänteisiä linkkejä tämä kestää kuukausia.", "Kyllä, kunhan se on tarkistettu ja luotettava.", "Sillä on viittauksia todellisilta, asiaankuuluvilta verkkosivustoilta, jotka varmistavat auktoriteetin.", "Käänteiset linkit ovat yksi Googlen tärkeimmistä sijoitustekijöistä.", "Tarkistamme sivuston historian, käänteisten linkkien laadun ja roskapostin puuttumisen.", "Kyllä. Sisältö on uutta, mutta verkkotunnus tuo jo mukanaan verkkoauktoriteettia.", "Ehdottomasti. Aloittelijat hyötyvät nopeammasta näkyvyydestä.", "Hinta määräytyy nimen laadun, SEO-arvon ja käänteisten linkkien mukaan.", "Kyllä. Vahva vanhentunut verkkotunnus säilyttää arvonsa ja voi jopa nousta hinnassa.", "Vain jos sillä on huono historia. Siksi huolellinen valinta on ratkaisevaa.", "Tärkeät asiat: roskapostiton historia, asiaankuuluvat käänteiset linkit, looginen nimi.", "Siirron jälkeen voit käyttää verkkotunnusta välittömästi.", "Et. Vanhentunut verkkotunnus toimii teknisesti samalla tavalla kuin uusi.", "Kyllä. Verkkokaupat hyötyvät erityisesti luottamuksesta ja auktoriteetista.", "Verkkotunnuksen auktoriteetti osoittaa verkkotunnuksen vahvuuden linkkien ja historian perusteella.", "Monille yrittäjille kyllä. Linkkien rakentaminen on työlästä ja kallista.", "Hinnat vaihtelevat auktoriteetin ja toimialan mukaan.", "Vähemmän tärkeää kuin ennen. Selkeä, luotettava nimi on nyt tärkeämpi.", "Kyllä, varsinkin jos sillä on asiaankuuluvia käänteisiä linkkejä.", "Rangaistua verkkotunnusta tulisi välttää. Tarkistamme jokaisen verkkotunnuksen ennakkoon.", "Ostettuasi saat EPP-koodin, jonka syötät uudelle rekisterinpitäjällesi.", "Riippuu kohdeyleisöstäsi. Verkkotunnuksen auktoriteetti on laajennusta tärkeämpi.", "Kyllä. 301-uudelleenohjauksella siirrät SEO-arvon pääsivustollesi.", "Nopeammin kuin uusi verkkotunnus - usein päivissä tai viikoissa.", "Nopeampi näkyvyys, olemassa olevat käänteiset linkit, enemmän luottamusta Googlelta.", "Ei aina. Monet markkinapaikat eivät tarkista laatua.", "Käytä työkaluja kuten Ahrefs tai MOZ. Tarjoamme nämä tiedot avoimesti.", "Monille yrittäjille ja sijoittajille kyllä.", "Käänteiset linkit säilyvät, kunnes viittaavat sivustot poistavat ne.", "Kyllä, varsinkin jos sillä on alueellista merkitystä.", "Vain jos et tarkista verkkotunnusta ennakkoon.", "Koska saat ennalta tarkistettua laatua ja vältät riskit."
    ]
  },
  cs: {
    title: "Kompletní průvodce: 35 otázek o expirovaných doménách a SEO",
    qs: [
      "Jakou doménu bych si měl koupit jako začátečník?", "Jaký je rozdíl mezi novou a expirovanou doménou?", "Je lepší koupit novou nebo expirovanou doménu?", "Proč se můj nový web v Googlu umisťuje tak špatně?", "Je bezpečné koupit expirovanou doménu?", "Co znamená doména s dobrými zpětnými odkazy?", "Proč jsou zpětné odkazy při nákupu domény důležité?", "Jak zjistím, zda je expirovaná doména spolehlivá?", "Mohu použít expirovanou doménu pro nový web?", "Je expirovaná doména vhodná pro začátečníky?", "Proč jsou některé domény dražší než jiné?", "Mohu expirovanou doménu později prodat?", "Může být expirovaná doména špatná pro SEO?", "Na co si mám dát pozor při nákupu?", "Jak rychle mohu začít po nákupu?", "Potřebuji technické znalosti?", "Je expirovaná doména vhodná pro e-shop?", "Co znamená autorita domény?", "Je expirovaná doména lepší než linkbuilding?", "Kolik stojí dobrá expirovaná doména?", "Je klíčové slovo v doméně důležité pro SEO?", "Mohu použít expirovanou doménu pro affiliate web?", "Co když byla expirovaná doména penalizována Googlem?", "Jak převedu zakoupenou doménu na svůj hosting?", "Je doména .cz nebo .eu lepší než .com?", "Mohu přesměrovat expirovanou doménu na svůj stávající web?", "Jak dlouho trvá, než se expirovaná doména umístí v Googlu?", "Jaké jsou výhody oproti nové doméně?", "Mohu věřit expirované doméně z jakéhokoli tržiště?", "Jak zjistím, zda má doména hodnotné zpětné odkazy?", "Je investice do expirované domény dobrý nápad?", "Co se stane se starými zpětnými odkazy při stavbě nového webu?", "Mohu použít expirovanou doménu pro místní podnikání?", "Existují rizika při nákupu expirované domény?", "Proč nakupovat u specializovaného prodejce?"
    ],
    as: [
      "Jako začátečník si vyberte doménu, která se snadno pamatuje a vzbuzuje důvěru. Spolehlivá expirovaná doména má často již vybudovanou autoritu.", "Nová doména nemá žádnou historii. Expirovaná doména byla registrována dříve a může mít stále zpětné odkazy a důvěru Googlu.", "Pro budování značky může fungovat nové jméno, ale pro rychlejší nalezení v Googlu nabízí dobrá expirovaná doména jasnou výhodu.", "Nové weby si musí důvěryhodnost teprve vybudovat. Bez odkazů to trvá měsíce.", "Ano, pokud je ověřená a spolehlivá.", "Má odkazy ze skutečných, relevantních webů, které zajišťují autoritu.", "Zpětné odkazy jsou jedním z nejdůležitějších hodnotících faktorů Googlu.", "Kontrolujeme historii webu, kvalitu odkazů a nepřítomnost spamu.", "Ano. Obsah je nový, ale doména již přináší online autoritu.", "Rozhodně. Začátečníci těží z rychlejší viditelnosti.", "Cena se odvíjí od kvality jména, SEO hodnoty a odkazů.", "Ano. Silná expirovaná doména si udržuje svou hodnotu.", "Pouze pokud má špatnou historii. Proto je důležitý pečlivý výběr.", "Důležité body: historie bez spamu, relevantní odkazy, logické jméno.", "Po převodu můžete doménu okamžitě začít používat.", "Ne. Expirovaná doména funguje technicky stejně jako nová.", "Ano. E-shopy těží především z důvěry a autority.", "Autorita domény ukazuje její sílu na základě odkazů a historie.", "Pro mnoho podnikatelů ano. Linkbuilding je pracný a drahý.", "Ceny se liší podle autority a odvětví.", "Méně důležité než dříve. Jasné jméno je nyní důležitější.", "Ano, zvláště pokud má relevantní zpětné odkazy.", "Penalizované doméně je třeba se vyhnout. Všechny domény předem kontrolujeme.", "Po nákupu obdržíte EPP kód, který zadáte u nového registrátora.", "Záleží na cílové skupině. Autorita domény je důležitější než koncovka.", "Ano. Pomocí přesměrování 301 převedete SEO hodnotu na svůj hlavní web.", "Rychleji než u nové domény – často v řádu dnů nebo týdnů.", "Rychlejší viditelnost, existující odkazy, větší důvěra Googlu.", "Ne vždy. Mnoho tržišť nekontroluje kvalitu.", "Použijte nástroje jako Ahrefs nebo MOZ. My tyto informace poskytujeme transparentně.", "Pro mnoho podnikatelů a investorů ano.", "Odkazy zůstávají, dokud je neodstraní odkazující weby.", "Ano, zvláště pokud má regionální význam.", "Pouze pokud si doménu předem neověříte.", "Protože získáte předem ověřenou kvalitu a vyhnete se rizikům."
    ]
  },
  el: {
    title: "Πλήρης Οδηγός: 35 Ερωτήσεις για Ληγμένα Domain & SEO",
    qs: [
      "Ποιο όνομα τομέα πρέπει να αγοράσω ως αρχάριος;", "Ποια είναι η διαφορά μεταξύ ενός νέου και ενός ληγμένου τομέα;", "Είναι καλύτερο να αγοράσω έναν νέο ή έναν ληγμένο τομέα;", "Γιατί ο νέος ιστότοπός μου κατατάσσεται τόσο άσχημα στην Google;", "Είναι ασφαλής η αγορά ενός ληγμένου τομέα;", "Τι σημαίνει ένας τομέας με καλούς συνδέσμους (backlinks);", "Γιατί τα backlinks είναι σημαντικά;", "Πώς μπορώ να ξέρω αν ένας ληγμένος τομέας είναι αξιόπιστος;", "Μπορώ να χρησιμοποιήσω έναν ληγμένο τομέα για έναν νέο ιστότοπο;", "Είναι ένας ληγμένος τομέας κατάλληλος για αρχάριους;", "Γιατί ορισμένοι τομείς είναι πιο ακριβοί;", "Μπορώ να πουλήσω έναν ληγμένο τομέα αργότερα;", "Μπορεί ένας ληγμένος τομέας να είναι κακός για το SEO;", "Τι πρέπει να προσέξω κατά την αγορά;", "Πόσο γρήγορα μπορώ να ξεκινήσω;", "Χρειάζομαι τεχνικές γνώσεις;", "Είναι ένας ληγμένος τομέας κατάλληλος για e-shop;", "Τι σημαίνει το domain authority;", "Είναι ένας ληγμένος τομέας καλύτερος από το link building;", "Πόσο κοστίζει ένας καλός ληγμένος τομέας;", "Είναι σημαντική μια λέξη-κλειδί στον τομέα;", "Μπορώ να χρησιμοποιήσω έναν ληγμένο τομέα για ένα affiliate site;", "Τι γίνεται αν ένας ληγμένος τομέας έχει τιμωρηθεί από την Google;", "Πώς μεταφέρω έναν τομέα στο δικό μου hosting;", "Είναι ένα .gr ή .eu καλύτερο από ένα .com;", "Μπορώ να ανακατευθύνω έναν ληγμένο τομέα στον υπάρχοντα ιστότοπό μου;", "Πόσος χρόνος χρειάζεται για να καταταγεί;", "Ποια είναι τα πλεονεκτήματα έναντι ενός νέου τομέα;", "Μπορώ να εμπιστευτώ έναν ληγμένο τομέα από οποιαδήποτε αγορά;", "Πώς ξέρω αν έχει πολύτιμα backlinks;", "Είναι καλή ιδέα η επένδυση σε ληγμένους τομείς;", "Τι συμβαίνει με τα παλιά backlinks;", "Μπορώ να τον χρησιμοποιήσω για μια τοπική επιχείρηση;", "Υπάρχουν κίνδυνοι;", "Γιατί να αγοράσω από εξειδικευμένο πωλητή;"
    ],
    as: [
      "Ως αρχάριος, επιλέξτε έναν τομέα που θυμάστε εύκολα και εμπνέει εμπιστοσύνη. Ένας αξιόπιστος ληγμένος τομέας έχει συχνά ήδη καθιερωμένο κύρος.", "Ένας νέος τομέας δεν έχει ιστορικό. Ένας ληγμένος τομέας είχε εγγραφεί στο παρελθόν και μπορεί να έχει ακόμα backlinks και την εμπιστοσύνη της Google.", "Για branding, ένα νέο όνομα μπορεί να λειτουργήσει, αλλά για ταχύτερη εύρεση στην Google, ένας καλός ληγμένος τομέας προσφέρει σαφές πλεονέκτημα.", "Οι νέοι ιστότοποι πρέπει να χτίσουν την αξιοπιστία τους. Χωρίς συνδέσμους, αυτό διαρκεί μήνες.", "Ναι, εφόσον είναι ελεγμένος και αξιόπιστος.", "Έχει αναφορές από πραγματικούς, σχετικούς ιστότοπους που εξασφαλίζουν κύρος.", "Τα backlinks είναι ένας από τους πιο σημαντικούς παράγοντες κατάταξης της Google.", "Ελέγχουμε το ιστορικό του ιστότοπου, την ποιότητα των συνδέσμων και την απουσία spam.", "Ναι. Το περιεχόμενο είναι νέο, αλλά ο τομέας φέρνει ήδη διαδικτυακό κύρος.", "Απολύτως. Οι αρχάριοι επωφελούνται από την ταχύτερη ορατότητα.", "Η τιμή καθορίζεται από την ποιότητα του ονόματος, την αξία SEO και τα backlinks.", "Ναι. Ένας ισχυρός ληγμένος τομέας διατηρεί την αξία του.", "Μόνο αν έχει κακό ιστορικό. Γι' αυτό η προσεκτική επιλογή είναι ζωτικής σημασίας.", "Σημαντικά σημεία: ιστορικό χωρίς spam, σχετικά backlinks, λογικό όνομα.", "Μετά τη μεταφορά μπορείτε να χρησιμοποιήσετε τον τομέα αμέσως.", "Όχι. Ένας ληγμένος τομέας λειτουργεί τεχνικά όπως ένας νέος.", "Ναι. Τα e-shops επωφελούνται ιδιαίτερα από την εμπιστοσύνη και το κύρος.", "Το domain authority δείχνει τη δύναμη ενός τομέα βάσει συνδέσμων και ιστορικού.", "Για πολλούς επιχειρηματίες, ναι. Το link building είναι επίπονο και ακριβό.", "Οι τιμές ποικίλλουν ανάλογα με το κύρος και τον κλάδο.", "Λιγότερο σημαντικό από παλιά. Ένα σαφές όνομα είναι πλέον πιο σημαντικό.", "Ναι, ειδικά αν έχει σχετικά backlinks.", "Ένας τιμωρημένος τομέας πρέπει να αποφεύγεται. Ελέγχουμε κάθε τομέα εκ των προτέρων.", "Μετά την αγορά λαμβάνετε έναν κωδικό EPP που εισάγετε στον νέο σας καταχωρητή.", "Εξαρτάται από το κοινό σας. Το κύρος του τομέα είναι πιο σημαντικό από την κατάληξη.", "Ναι. Με μια ανακατεύθυνση 301 μεταφέρετε την αξία SEO στον κύριο ιστότοπό σας.", "Γρηγορότερα από έναν νέο τομέα - συχνά σε μέρες ή εβδομάδες.", "Ταχύτερη ορατότητα, υπάρχοντα backlinks, μεγαλύτερη εμπιστοσύνη από την Google.", "Όχι πάντα. Πολλές αγορές δεν ελέγχουν την ποιότητα.", "Χρησιμοποιήστε εργαλεία όπως το Ahrefs ή το MOZ. Παρέχουμε αυτές τις πληροφορίες με διαφάνεια.", "Για πολλούς επιχειρηματίες και επενδυτές, ναι.", "Τα backlinks παραμένουν εφόσον δεν αφαιρεθούν από τους ιστότοπους αναφοράς.", "Ναι, ειδικά αν έχει περιφερειακή συνάφεια.", "Μόνο αν δεν ελέγξετε τον τομέα εκ των προτέρων.", "Επειδή λαμβάνετε προ-ελεγμένη ποιότητα και αποφεύγετε τους κινδύνους."
    ]
  },
  ru: {
    title: "Полное руководство: 35 вопросов об истекших доменах и SEO",
    qs: [
      "Какой домен мне следует купить как новичку?", "В чем разница между новым и истекшим доменом?", "Что лучше: купить новый или истекший домен?", "Почему мой новый сайт так плохо ранжируется в Google?", "Безопасно ли покупать истекший домен?", "Что означает домен с хорошими обратными ссылками?", "Почему обратные ссылки важны при покупке домена?", "Как узнать, надежен ли истекший домен?", "Могу ли я использовать истекший домен для нового сайта?", "Подходит ли истекший домен для новичков?", "Почему некоторые домены стоят дороже других?", "Смогу ли я позже продать истекший домен?", "Может ли истекший домен быть плохим для SEO?", "На что следует обратить внимание при покупке?", "Как быстро я смогу начать работу после покупки?", "Нужны ли мне технические знания?", "Подходит ли истекший домен для интернет-магазина?", "Что означает авторитет домена?", "Лучше ли истекший домен, чем линкбилдинг?", "Сколько стоит хороший истекший домен?", "Важно ли ключевое слово в домене для SEO?", "Могу ли я использовать истекший домен для партнерского сайта?", "Что делать, если домен был оштрафован Google?", "Как перенести купленный домен на мой хостинг?", "Домен .ru или .eu лучше, чем .com?", "Могу ли я перенаправить истекший домен на свой существующий сайт?", "Как долго нужно ждать, чтобы истекший домен стал ранжироваться?", "В чем преимущества истекшего домена перед новым?", "Могу ли я доверять домену со случайной торговой площадки?", "Как узнать, есть ли у домена ценные ссылки?", "Хорошая ли идея инвестировать в истекший домен?", "Что происходит со старыми ссылками при создании нового сайта?", "Могу ли я использовать истекший домен для местного бизнеса?", "Есть ли риски при покупке истекшего домена?", "Почему стоит покупать у специализированного продавца?"
    ],
    as: [
      "Как новичку, вам следует выбрать домен, который легко запомнить и который внушает доверие. Надежный истекший домен часто уже имеет устоявшийся авторитет.", "У нового домена нет истории. Истекший домен был зарегистрирован ранее и может по-прежнему иметь ссылки и доверие Google.", "Для брендинга может подойти новое имя, но для более быстрого поиска в Google хороший истекший домен дает явное преимущество.", "Новым сайтам еще предстоит завоевать доверие. Без ссылок это занимает месяцы.", "Да, если он проверен и надежен.", "У него есть ссылки с реальных, релевантных сайтов, которые обеспечивают авторитет.", "Обратные ссылки — один из самых важных факторов ранжирования Google.", "Мы проверяем историю сайта, качество ссылок и отсутствие спама.", "Да. Контент новый, но домен уже приносит авторитет в сети.", "Абсолютно. Новички выигрывают от более быстрой видимости.", "Цена определяется качеством имени, ценностью SEO и ссылками.", "Да. Сильный истекший домен сохраняет свою ценность.", "Только если у него плохая история. Поэтому важен тщательный выбор.", "Важные моменты: история без спама, релевантные ссылки, логичное имя.", "После переноса вы можете сразу же использовать домен.", "Нет. Истекший домен технически работает так же, как и новый.", "Да. Интернет-магазины особенно выигрывают от доверия и авторитета.", "Авторитет домена показывает его силу на основе ссылок и истории.", "Для многих предпринимателей — да. Линкбилдинг — это трудоемко и дорого.", "Цены варьируются в зависимости от авторитета и отрасли.", "Менее важно, чем раньше. Четкое имя сейчас важнее.", "Да, особенно если у него есть релевантные ссылки.", "Следует избегать оштрафованных доменов. Мы проверяем каждый домен заранее.", "После покупки вы получите код EPP, который введете у своего нового регистратора.", "Зависит от вашей целевой аудитории. Авторитет домена важнее зоны.", "Да. С помощью 301 редиректа вы передаете ценность SEO на свой основной сайт.", "Быстрее, чем новый домен — часто за дни или недели.", "Более быстрая видимость, существующие ссылки, больше доверия от Google.", "Не всегда. Многие площадки не проверяют качество.", "Используйте инструменты вроде Ahrefs или MOZ. Мы предоставляем эту информацию прозрачно.", "Для многих предпринимателей и инвесторов — да.", "Ссылки остаются до тех пор, пока их не удалят ссылающиеся сайты.", "Да, особенно если он имеет региональную значимость.", "Только если вы не проверите домен заранее.", "Потому что вы получаете проверенное качество и избегаете рисков."
    ]
  },
  ro: {
    title: "Ghid Complet: 35 de Întrebări despre Domeniile Expirate și SEO",
    qs: [
      "Ce domeniu ar trebui să cumpăr ca începător?", "Care este diferența dintre un domeniu nou și unul expirat?", "Este mai bine să cumpăr un domeniu nou sau unul expirat?", "De ce site-ul meu nou se clasează atât de slab pe Google?", "Este sigur să cumpăr un domeniu expirat?", "Ce înseamnă un domeniu cu backlink-uri bune?", "De ce sunt importante backlink-urile la cumpărarea unui domeniu?", "Cum pot afla dacă un domeniu expirat este de încredere?", "Pot folosi un domeniu expirat pentru un site nou?", "Este un domeniu expirat potrivit pentru începători?", "De ce unele domenii sunt mai scumpe decât altele?", "Pot vinde un domeniu expirat mai târziu?", "Poate un domeniu expirat să fie rău pentru SEO?", "La ce ar trebui să fiu atent când cumpăr?", "Cât de repede pot începe după cumpărare?", "Am nevoie de cunoștințe tehnice?", "Este un domeniu expirat potrivit pentru un magazin online?", "Ce înseamnă autoritatea domeniului?", "Este un domeniu expirat mai bun decât link building-ul?", "Cât costă un domeniu expirat bun?", "Este un cuvânt cheie în domeniu important pentru SEO?", "Pot folosi un domeniu expirat pentru un site de afiliere?", "Ce se întâmplă dacă un domeniu a fost penalizat de Google?", "Cum transfer un domeniu cumpărat pe propriul meu hosting?", "Este un domeniu .ro sau .eu mai bun decât un .com?", "Pot redirecționa un domeniu expirat către site-ul meu existent?", "Cât durează până când un domeniu expirat se clasează în Google?", "Care sunt avantajele față de un domeniu nou?", "Pot avea încredere într-un domeniu expirat de pe orice marketplace?", "Cum știu dacă un domeniu are backlink-uri valoroase?", "Este o idee bună investiția într-un domeniu expirat?", "Ce se întâmplă cu vechile backlink-uri când construiesc un site nou?", "Pot folosi un domeniu expirat pentru o afacere locală?", "Există riscuri la cumpărarea unui domeniu expirat?", "De ce să cumpăr de la un vânzător specializat?"
    ],
    as: [
      "Ca începător, alegeți un domeniu ușor de reținut și care inspiră încredere. Un domeniu expirat de încredere are adesea deja o autoritate stabilită.", "Un domeniu nou nu are istoric. Un domeniu expirat a fost înregistrat anterior și poate avea încă backlink-uri și încrederea Google.", "Pentru branding, un nume nou poate funcționa, dar pentru a fi găsit mai repede pe Google, un domeniu expirat bun oferă un avantaj clar.", "Site-urile noi trebuie să-și construiască credibilitatea. Fără link-uri, acest lucru durează luni de zile.", "Da, atâta timp cât este verificat și de încredere.", "Are referințe de la site-uri web reale și relevante care asigură autoritatea.", "Backlink-urile sunt unul dintre cei mai importanți factori de clasare Google.", "Verificăm istoricul site-ului, calitatea link-urilor și absența spam-ului.", "Da. Conținutul este nou, dar domeniul aduce deja autoritate online.", "Absolut. Începătorii beneficiază de o vizibilitate mai rapidă.", "Prețul este determinat de calitatea numelui, valoarea SEO și backlink-uri.", "Da. Un domeniu expirat puternic își păstrează valoarea.", "Numai dacă are un istoric prost. De aceea selecția atentă este crucială.", "Puncte importante: istoric fără spam, backlink-uri relevante, nume logic.", "După transfer, puteți utiliza domeniul imediat.", "Nu. Un domeniu expirat funcționează tehnic la fel ca unul nou.", "Da. Magazinele online beneficiază în special de încredere și autoritate.", "Autoritatea domeniului indică puterea unui domeniu pe baza link-urilor și istoricului.", "Pentru mulți antreprenori, da. Link building-ul este laborios și costisitor.", "Prețurile variază în funcție de autoritate și industrie.", "Mai puțin important decât înainte. Un nume clar este acum mai important.", "Da, mai ales dacă are backlink-uri relevante.", "Un domeniu penalizat trebuie evitat. Noi verificăm fiecare domeniu în prealabil.", "După cumpărare primiți un cod EPP pe care îl introduceți la noul registrator.", "Depinde de publicul țintă. Autoritatea domeniului este mai importantă decât extensia.", "Da. Cu o redirecționare 301 transferați valoarea SEO către site-ul principal.", "Mai repede decât un domeniu nou - adesea în zile sau săptămâni.", "Vizibilitate mai rapidă, backlink-uri existente, mai multă încredere din partea Google.", "Nu întotdeauna. Multe marketplace-uri nu verifică calitatea.", "Utilizați instrumente precum Ahrefs sau MOZ. Noi oferim aceste informații transparent.", "Pentru mulți antreprenori și investitori, da.", "Link-urile rămân atâta timp cât nu sunt eliminate de site-urile de referință.", "Da, mai ales dacă are relevanță regională.", "Doar dacă nu verificați domeniul în prealabil.", "Pentru că obțineți calitate pre-verificată și evitați riscurile."
    ]
  },
  bg: {
    title: "Пълно Ръководство: 35 Въпроса за Изтекли Домейни и SEO",
    qs: [
      "Какъв домейн да купя като начинаещ?", "Каква е разликата между нов и изтекъл домейн?", "Кое е по-добре: нов или изтекъл домейн?", "Защо новият ми сайт се класира толкова слабо в Google?", "Безопасно ли е да се купи изтекъл домейн?", "Какво означава домейн с добри беклинкове?", "Защо беклинковете са важни при покупка на домейн?", "Как да разбера дали изтекъл домейн е надежден?", "Мога ли да използвам изтекъл домейн за нов сайт?", "Подходящ ли е изтекъл домейн за начинаещи?", "Защо някои домейни са по-скъпи от други?", "Мога ли да продам изтекъл домейн по-късно?", "Може ли изтекъл домейн да е лош за SEO?", "За какво трябва да внимавам при покупка?", "Колко бързо мога да започна след покупката?", "Трябват ли ми технически познания?", "Подходящ ли е изтекъл домейн за онлайн магазин?", "Какво означава авторитет на домейна?", "По-добър ли е изтекъл домейн от линкбилдинга?", "Колко струва добър изтекъл домейн?", "Важна ли е ключова дума в домейна за SEO?", "Мога ли да използвам изтекъл домейн за афилиейт сайт?", "Какво става, ако домейнът е бил наказан от Google?", "Как да прехвърля купен домейн на моя хостинг?", "По-добър ли е .bg или .eu домейн от .com?", "Мога ли да пренасоча изтекъл домейн към съществуващия си сайт?", "Колко време отнема на изтекъл домейн да се класира в Google?", "Какви са предимствата пред нов домейн?", "Мога ли да се доверя на домейн от произволен пазар?", "Как да разбера дали домейнът има ценни беклинкове?", "Добра идея ли е инвестицията в изтекъл домейн?", "Какво се случва със старите беклинкове, когато изграждам нов сайт?", "Мога ли да използвам изтекъл домейн за местен бизнес?", "Има ли рискове при покупка на изтекъл домейн?", "Защо да купувам от специализиран продавач?"
    ],
    as: [
      "Като начинаещ изберете домейн, който лесно се помни и вдъхва доверие.", "Новият домейн няма история. Изтеклият домейн може да има беклинкове и доверие от Google.", "За по-бързо намиране в Google, добрият изтекъл домейн предлага ясно предимство.", "Новите сайтове тепърва трябва да изграждат авторитет.", "Да, стига да е проверен и надежден.", "Има връзки от реални, подходящи уебсайтове.", "Беклинковете са един от най-важните фактори за класиране.", "Ние проверяваме историята на сайта и качеството на връзките.", "Да. Съдържанието е ново, но домейнът вече носи авторитет.", "Абсолютно. Начинаещите печелят от по-бърза видимост.", "Цената се определя от качеството на името и SEO стойността.", "Да. Силният изтекъл домейн запазва стойността си.", "Само ако има лоша история.", "Важни точки: история без спам, подходящи връзки.", "След трансфера можете да използвате домейна веднага.", "Не. Изтеклият домейн работи технически като нов.", "Да. Онлайн магазините печелят от готовото доверие.", "Показва силата на домейна въз основа на връзки и история.", "За много предприемачи да. Линкбилдингът е труден и скъп.", "Цените варират според авторитета и индустрията.", "По-малко важно от преди. Ясното име е по-важно.", "Да, особено ако има подходящи връзки.", "Наказаните домейни трябва да се избягват. Ние проверяваме всеки.", "Получавате EPP код, който въвеждате при новия регистратор.", "Зависи от целевата аудитория.", "Да. С 301 пренасочване прехвърляте SEO стойността.", "По-бързо от нов домейн - често за дни или седмици.", "По-бърза видимост, съществуващи връзки.", "Не винаги. Много пазари не проверяват качеството.", "Използвайте инструменти като Ahrefs или MOZ.", "За много предприемачи и инвеститори да.", "Връзките остават, докато не бъдат премахнати.", "Да, особено ако има регионално значение.", "Само ако не проверите домейна предварително.", "Защото получавате предварително проверено качество."
    ]
  },
  uk: {
    title: "Повний Посібник: 35 Питань про Прострочені Домени та SEO",
    qs: [
      "Який домен мені варто купити як новачку?", "У чому різниця між новим і простроченим доменом?", "Що краще: новий чи прострочений домен?", "Чому мій новий сайт так погано ранжується в Google?", "Чи безпечно купувати прострочений домен?", "Що означає домен з хорошими зворотними посиланнями?", "Чому зворотні посилання важливі?", "Як дізнатися, чи надійний прострочений домен?", "Чи можу я використовувати прострочений домен для нового сайту?", "Чи підходить прострочений домен для новачків?", "Чому деякі домени дорожчі за інші?", "Чи можу я пізніше продати прострочений домен?", "Чи може прострочений домен бути поганим для SEO?", "На що слід звернути увагу при покупці?", "Як швидко я зможу почати роботу?", "Чи потрібні мені технічні знання?", "Чи підходить прострочений домен для інтернет-магазину?", "Що означає авторитет домену?", "Чи краще прострочений домен, ніж лінкбілдінг?", "Скільки коштує хороший прострочений домен?", "Чи важливе ключове слово в домені для SEO?", "Чи можу я використовувати прострочений домен для партнерського сайту?", "Що робити, якщо домен був оштрафований Google?", "Як перенести куплений домен на мій хостинг?", "Домен .ua чи .eu краще, ніж .com?", "Чи можу я перенаправити прострочений домен на свій існуючий сайт?", "Скільки часу потрібно, щоб прострочений домен почав ранжуватися?", "У чому переваги простроченого домену перед новим?", "Чи можу я довіряти домену з випадкового маркетплейсу?", "Як дізнатися, чи має домен цінні посилання?", "Чи хороша ідея інвестувати в прострочений домен?", "Що відбувається зі старими посиланнями при створенні нового сайту?", "Чи можу я використовувати прострочений домен для місцевого бізнесу?", "Чи є ризики при покупці простроченого домену?", "Чому варто купувати у спеціалізованого продавця?"
    ],
    as: [
      "Як новачку, вам слід обрати домен, який легко запам'ятати.", "У нового домену немає історії. Прострочений домен може мати посилання.", "Для більш швидкого пошуку в Google хороший прострочений домен дає перевагу.", "Новим сайтам ще належить завоювати довіру.", "Так, якщо він перевірений і надійний.", "У нього є посилання з реальних сайтів.", "Зворотні посилання - один з найважливіших факторів.", "Ми перевіряємо історію сайту і якість посилань.", "Так. Контент новий, але домен вже приносить авторитет.", "Абсолютно. Новачки виграють від швидшої видимості.", "Ціна визначається якістю імені та цінністю SEO.", "Так. Сильний прострочений домен зберігає свою цінність.", "Тільки якщо у нього погана історія.", "Важливі моменти: історія без спаму, релевантні посилання.", "Після перенесення ви можете відразу ж використовувати домен.", "Ні. Прострочений домен працює так само, як і новий.", "Так. Інтернет-магазини особливо виграють від довіри.", "Авторитет домену показує його силу на основі посилань.", "Для багатьох підприємців - так. Лінкбілдінг - це дорого.", "Ціни варіюються залежно від авторитету.", "Менш важливо, ніж раніше. Чітке ім'я важливіше.", "Так, особливо якщо у нього є релевантні посилання.", "Слід уникати оштрафованих доменів.", "Ви отримаєте код EPP, який введете у нового реєстратора.", "Залежить від вашої цільової аудиторії.", "Так. За допомогою 301 редиректу ви передаєте цінність SEO.", "Швидше, ніж новий домен.", "Більш швидка видимість, існуючі посилання.", "Не завжди. Багато майданчиків не перевіряють якість.", "Використовуйте інструменти на кшталт Ahrefs або MOZ.", "Для багатьох підприємців - так.", "Посилання залишаються, поки їх не видалять.", "Так, особливо якщо він має регіональну значимість.", "Тільки якщо ви не перевірите домен заздалегідь.", "Тому що ви отримуєте перевірену якість."
    ]
  },
  hr: {
    title: "Potpuni Vodič: 35 Pitanja o Isteklim Domenama i SEO",
    qs: [
      "Koju domenu trebam kupiti kao početnik?", "Koja je razlika između nove i istekle domene?", "Je li bolje kupiti novu ili isteklu domenu?", "Zašto se moja nova web stranica tako loše rangira na Googleu?", "Je li sigurno kupiti isteklu domenu?", "Što znači domena s dobrim povratnim vezama?", "Zašto su povratne veze važne pri kupnji domene?", "Kako mogu znati je li istekla domena pouzdana?", "Mogu li koristiti isteklu domenu za novu web stranicu?", "Je li istekla domena prikladna za početnike?", "Zašto su neke domene skuplje od drugih?", "Mogu li kasnije prodati isteklu domenu?", "Može li istekla domena biti loša za SEO?", "Na što trebam obratiti pozornost pri kupnji?", "Koliko brzo mogu početi nakon kupnje?", "Trebam li tehničko znanje?", "Je li istekla domena prikladna za webshop?", "Što znači autoritet domene?", "Je li istekla domena bolja od izgradnje poveznica?", "Koliko košta dobra istekla domena?", "Je li ključna riječ u domeni važna za SEO?", "Mogu li koristiti isteklu domenu za affiliate stranicu?", "Što ako je Google kaznio isteklu domenu?", "Kako prenijeti kupljenu domenu na vlastiti hosting?", "Je li .hr ili .eu domena bolja od .com?", "Mogu li preusmjeriti isteklu domenu na svoju postojeću stranicu?", "Koliko dugo treba da se istekla domena rangira na Googleu?", "Koje su prednosti u odnosu na novu domenu?", "Mogu li vjerovati istekle domeni s bilo kojeg tržišta?", "Kako znati ima li domena vrijedne povratne veze?", "Je li ulaganje u isteklu domenu dobra ideja?", "Što se događa sa starim povratnim vezama kada napravim novu stranicu?", "Mogu li koristiti isteklu domenu za lokalni posao?", "Postoje li rizici pri kupnji istekle domene?", "Zašto kupovati od specijaliziranog prodavača?"
    ],
    as: [
      "Kao početnik odaberite domenu koju je lako zapamtiti.", "Nova domena nema povijest. Istekla domena može imati povratne veze.", "Za brže pronalaženje na Googleu, dobra istekla domena nudi prednost.", "Nove web stranice tek trebaju izgraditi autoritet.", "Da, ako je provjerena i pouzdana.", "Ima poveznice sa stvarnih web stranica.", "Povratne veze jedan su od najvažnijih čimbenika.", "Provjeravamo povijest web mjesta i kvalitetu poveznica.", "Da. Sadržaj je nov, ali domena već donosi autoritet.", "Apsolutno. Početnici imaju koristi od brže vidljivosti.", "Cijena je određena kvalitetom imena i SEO vrijednošću.", "Da. Snažna istekla domena zadržava svoju vrijednost.", "Samo ako ima lošu povijest.", "Važne točke: povijest bez neželjene pošte, relevantne poveznice.", "Nakon prijenosa možete odmah koristiti domenu.", "Ne. Istekla domena tehnički radi kao i nova.", "Da. Webshopovi posebno imaju koristi od povjerenja.", "Autoritet domene pokazuje njenu snagu na temelju poveznica.", "Za mnoge poduzetnike da. Izgradnja poveznica je teška.", "Cijene variraju ovisno o autoritetu.", "Manje važno nego prije. Jasno ime je važnije.", "Da, osobito ako ima relevantne povratne veze.", "Kažnjene domene treba izbjegavati.", "Dobivate EPP kod koji unosite kod novog registrara.", "Ovisi o vašoj ciljanoj publici.", "Da. S 301 preusmjeravanjem prenosite SEO vrijednost.", "Brže od nove domene.", "Brža vidljivost, postojeće poveznice.", "Ne uvijek. Mnoga tržišta ne provjeravaju kvalitetu.", "Koristite alate poput Ahrefs ili MOZ.", "Za mnoge poduzetnike da.", "Poveznice ostaju sve dok se ne uklone.", "Da, osobito ako ima regionalnu važnost.", "Samo ako domenu niste prethodno provjerili.", "Jer dobivate unaprijed provjerenu kvalitetu."
    ]
  },
  // We apply a simplified fallback for the rest of the languages for brevity, but still perfectly mapped
  sk: { title: "Kompletný Sprievodca: 35 Otázok o Expirovaných Doménách a SEO", qs: [
    "Akú doménu si mám kúpiť ako začiatočník?","Aký je rozdiel medzi novou a expirovanou doménou?","Je lepšie kúpiť novú alebo expirovanú doménu?","Prečo sa môj nový web umiestňuje v Google tak zle?","Je bezpečné kúpiť expirovanú doménu?","Čo znamená doména s dobrými spätnými odkazmi?","Prečo sú spätné odkazy dôležité?","Ako zistím, či je expirovaná doména spoľahlivá?","Môžem použiť expirovanú doménu pre nový web?","Je expirovaná doména vhodná pre začiatočníkov?","Prečo sú niektoré domény drahšie ako iné?","Môžem expirovanú doménu neskôr predať?","Môže byť expirovaná doména zlá pre SEO?","Na čo si mám dať pozor pri kúpe?","Ako rýchlo môžem začať po kúpe?","Potrebujem technické znalosti?","Je expirovaná doména vhodná pre e-shop?","Čo znamená autorita domény?","Je expirovaná doména lepšia ako linkbuilding?","Koľko stojí dobrá expirovaná doména?","Je kľúčové slovo v doméne dôležité?","Môžem použiť expirovanú doménu pre affiliate web?","Čo ak bola doména penalizovaná Googlom?","Ako prenesiem kúpenú doménu na svoj hosting?","Je doména .sk alebo .eu lepšia ako .com?","Môžem presmerovať expirovanú doménu na svoj web?","Ako dlho trvá, kým sa doména umiestni v Google?","Aké sú výhody oproti novej doméne?","Môžem dôverovať doméne z akéhokoľvek trhoviska?","Ako zistím, či má doména hodnotné odkazy?","Je investícia do expirovanej domény dobrý nápad?","Čo sa stane so starými odkazmi pri novom webe?","Môžem použiť expirovanú doménu pre lokálny biznis?","Existujú riziká pri kúpe?","Prečo nakupovať u špecializovaného predajcu?"
  ], as: [
    "Ako začiatočník si vyberte doménu, ktorá sa ľahko pamätá a vzbudzuje dôveru.","Nová doména nemá históriu. Expirovaná doména môže mať odkazy a dôveru.","Pre rýchlejšie nájdenie v Google ponúka dobrá expirovaná doména výhodu.","Nové weby si musia dôveryhodnosť ešte len vybudovať.","Áno, ak je overená a spoľahlivá.","Má odkazy zo skutočných, relevantných webov.","Spätné odkazy sú jedným z najdôležitejších faktorov hodnotenia.","Kontrolujeme históriu webu a kvalitu odkazov.","Áno. Obsah je nový, ale doména už prináša autoritu.","Absolútne. Začiatočníci ťažia z rýchlejšej viditeľnosti.","Cena sa odvíja od kvality mena a SEO hodnoty.","Áno. Silná expirovaná doména si udržuje svoju hodnotu.","Iba ak má zlú históriu.","Dôležité body: história bez spamu, relevantné odkazy.","Po prevode môžete doménu okamžite používať.","Nie. Funguje technicky rovnako ako nová doména.","Áno. E-shopy ťažia predovšetkým z dôvery.","Ukazuje silu domény na základe odkazov.","Pre mnoho podnikateľov áno. Linkbuilding je drahý.","Ceny sa líšia podľa autority a odvetvia.","Menej dôležité ako predtým. Jasné meno je dôležitejšie.","Áno, najmä ak má relevantné odkazy.","Penalizovanej doméne sa treba vyhnúť.","Po kúpe dostanete EPP kód pre nového registrátora.","Záleží na cieľovej skupine.","Áno. Pomocou presmerovania 301 prenesiete SEO hodnotu.","Rýchlejšie ako u novej domény - často v priebehu dní.","Rýchlejšia viditeľnosť, existujúce odkazy.","Nie vždy. Mnoho trhovísk nekontroluje kvalitu.","Použite nástroje ako Ahrefs alebo MOZ.","Pre mnoho podnikateľov a investorov áno.","Odkazy zostávajú, kým ich neodstránia odkazujúce weby.","Áno, najmä ak má regionálny význam.","Iba ak si doménu vopred neoveríte.","Pretože získate vopred overenú kvalitu a vyhnete sa rizikám."
  ] },
  sr: { title: "Kompletan Vodič: 35 Pitanja o Isteklim Domenima i SEO", qs: [
    "Koji domen da kupim kao početnik?","Koja je razlika između novog i isteklog domena?","Da li je bolje kupiti nov ili istekao domen?","Zašto se moj novi sajt loše rangira na Google-u?","Da li je bezbedno kupiti istekao domen?","Šta znači domen sa dobrim povratnim linkovima?","Zašto su povratni linkovi važni?","Kako da znam da li je istekao domen pouzdan?","Mogu li koristiti istekao domen za novi sajt?","Da li je istekao domen pogodan za početnike?","Zašto su neki domeni skuplji od drugih?","Mogu li kasnije prodati istekao domen?","Može li istekao domen biti loš za SEO?","Na šta treba da obratim pažnju pri kupovini?","Koliko brzo mogu da počnem nakon kupovine?","Da li mi je potrebno tehničko znanje?","Da li je istekao domen pogodan za web prodavnicu?","Šta znači autoritet domena?","Da li je istekao domen bolji od izgradnje linkova?","Koliko košta dobar istekao domen?","Da li je ključna reč u domenu važna za SEO?","Mogu li koristiti istekao domen za affiliate sajt?","Šta ako je Google kaznio istekao domen?","Kako da prenesem kupljeni domen na svoj hosting?","Da li je .rs ili .eu domen bolji od .com?","Mogu li preusmeriti istekao domen na svoj postojeći sajt?","Koliko dugo treba da se istekao domen rangira u Google-u?","Koje su prednosti u odnosu na novi domen?","Mogu li verovati isteklom domenu sa bilo kog tržišta?","Kako da znam da li domen ima vredne povratne linkove?","Da li je ulaganje u istekao domen dobra ideja?","Šta se dešava sa starim povratnim linkovima kada napravim novi sajt?","Mogu li koristiti istekao domen za lokalni posao?","Da li postoje rizici pri kupovini isteklog domena?","Zašto kupovati od specijalizovanog prodavca?"
  ], as: [
    "Kao početnik, izaberite domen koji se lako pamti i uliva poverenje.","Novi domen nema istoriju. Istekli domen može imati linkove i poverenje.","Za brže pronalaženje na Google-u, dobar istekao domen nudi prednost.","Novi sajtovi moraju da izgrade autoritet. Bez linkova to traje mesecima.","Da, sve dok je proveren i pouzdan.","Ima reference sa stvarnih, relevantnih sajtova.","Povratni linkovi su jedan od najvažnijih faktora rangiranja.","Proveravamo istoriju sajta, kvalitet linkova i odsustvo spama.","Da. Sadržaj je nov, ali domen već donosi autoritet.","Apsolutno. Početnici imaju najviše koristi od brže vidljivosti.","Cena se određuje kvalitetom imena, SEO vrednošću i linkovima.","Da. Snažan istekao domen zadržava svoju vrednost.","Samo ako ima lošu istoriju. Zato je pažljiv izbor ključan.","Važne tačke: istorija bez spama, relevantni linkovi, logično ime.","Nakon prenosa možete odmah koristiti domen.","Ne. Istekao domen tehnički funkcioniše kao i novi.","Da. Web prodavnice posebno imaju koristi od poverenja i autoriteta.","Autoritet domena pokazuje njegovu snagu na osnovu linkova.","Za mnoge preduzetnike, da. Izgradnja linkova je naporna i skupa.","Cene variraju u zavisnosti od autoriteta i industrije.","Manje važno nego ranije. Jasno, pouzdano ime je sada važnije.","Da, posebno ako ima relevantne povratne linkove.","Kažnjeni domen treba izbegavati. Mi proveravamo svaki domen unapred.","Nakon kupovine dobijate EPP kod koji unosite kod novog registrara.","Zavisi od vaše ciljne publike. Autoritet domena je važniji od ekstenzije.","Da. Sa 301 preusmeravanjem prenosite SEO vrednost na svoj glavni sajt.","Brže nego novi domen — često u roku od nekoliko dana ili nedelja.","Brža vidljivost, postojeći linkovi, više poverenja kod Google-a.","Ne uvek. Mnoga tržišta ne proveravaju kvalitet.","Koristite alate poput Ahrefs ili MOZ. Mi pružamo ove informacije.","Za mnoge preduzetnike i investitore, da.","Linkovi ostaju sve dok ih referentni sajtovi ne uklone.","Da, posebno ako ima regionalnu važnost.","Samo ako ne proverite domen unapred.","Zato što dobijate unapred proveren kvalitet i izbegavate rizike."
  ] },
  sl: { title: "Popoln Vodnik: 35 Vprašanj o Poteklih Domenah in SEO", qs: [
    "Katero domeno naj kupim kot začetnik?","Kakšna je razlika med novo in poteklo domeno?","Je bolje kupiti novo ali poteklo domeno?","Zakaj se moje novo spletno mesto na Googlu uvršča tako slabo?","Je varno kupiti poteklo domeno?","Kaj pomeni domena z dobrimi povratnimi povezavami?","Zakaj so povratne povezave pomembne pri nakupu domene?","Kako vem, ali je potekla domena zanesljiva?","Lahko poteklo domeno uporabim za novo spletno mesto?","Je potekla domena primerna za začetnike?","Zakaj so nekatere domene dražje od drugih?","Lahko poteklo domeno pozneje prodam?","Je potekla domena lahko slaba za SEO?","Na kaj moram biti pozoren pri nakupu?","Kako hitro lahko začnem po nakupu?","Potrebujem tehnično znanje?","Je potekla domena primerna za spletno trgovino?","Kaj pomeni avtoriteta domene?","Je potekla domena boljša od gradnje povezav?","Koliko stane dobra potekla domena?","Je ključna beseda v domeni pomembna za SEO?","Lahko poteklo domeno uporabim za partnersko (affiliate) spletno mesto?","Kaj če je Google poteklo domeno kaznoval?","Kako kupljeno domeno prenesem na svoje gostovanje?","Je domena .si ali .eu boljša od .com?","Lahko poteklo domeno preusmerim na obstoječe spletno mesto?","Kako dolgo traja, da se potekla domena uvrsti na Googlu?","Kakšne so prednosti v primerjavi z novo domeno?","Lahko zaupam potekli domeni s katere koli tržnice?","Kako vem, ali ima domena dragocene povratne povezave?","Je naložba v poteklo domeno dobra ideja?","Kaj se zgodi s starimi povratnimi povezavami, ko zgradim novo spletno mesto?","Lahko poteklo domeno uporabim za lokalno podjetje?","Obstajajo tveganja pri nakupu potekle domene?","Zakaj kupovati pri specializiranem prodajalcu?"
  ], as: [
    "Kot začetnik izberite domeno, ki si jo je enostavno zapomniti in vzbuja zaupanje.","Nova domena nima zgodovine. Potekla domena ima lahko povezave in zaupanje.","Za hitrejše iskanje na Googlu potekla domena ponuja jasno prednost.","Nova spletna mesta morajo zgraditi avtoriteto.","Da, če je preverjena in zanesljiva.","Ima povezave z resničnih, ustreznih spletnih mest.","Povratne povezave so eden najpomembnejših dejavnikov.","Preverjamo zgodovino spletnega mesta in kakovost povezav.","Da. Vsebina je nova, domena pa že prinaša avtoriteto.","Vsekakor. Začetniki imajo največ koristi od hitrejše vidnosti.","Cena se določa glede na kakovost imena, SEO vrednost in povezave.","Da. Močna potekla domena ohranja svojo vrednost.","Samo, če ima slabo zgodovino. Zato je izbira ključna.","Pomembno: zgodovina brez vsiljene pošte, ustrezne povezave.","Po prenosu lahko domeno takoj uporabite.","Ne. Potekla domena tehnično deluje enako kot nova.","Da. Spletnim trgovinam to zelo pomaga.","Prikazuje moč domene na podlagi povezav.","Za mnoga podjetja da. Gradnja povezav je draga.","Cene se razlikujejo glede na avtoriteto.","Manj pomembno kot prej. Jasno ime je pomembnejše.","Da, še posebej, če ima ustrezne povezave.","Kaznovani domeni se je treba izogniti.","Prejmete kodo EPP, ki jo vnesete pri novem registrarju.","Odvisno od ciljne publike.","Da. S preusmeritvijo 301 prenesete SEO vrednost.","Hitreje kot nova domena - pogosto v nekaj dneh.","Hitrejša vidnost, obstoječe povezave.","Ne vedno. Mnoge tržnice ne preverjajo kakovosti.","Uporabite orodja, kot sta Ahrefs ali MOZ.","Za mnoga podjetja in vlagatelje da.","Povezave ostanejo, dokler jih ne odstranijo.","Da, še posebej, če ima regionalni pomen.","Samo če domene ne preverite vnaprej.","Ker dobite vnaprej preverjeno kakovost in se izognete tveganjem."
  ] },
  ko: { title: "완전 가이드: 만료된 도메인 이름과 SEO에 관한 35가지 질문", qs: [
    "초보자로서 어떤 도메인을 사야 하나요?","새 도메인과 만료된 도메인의 차이점은?","새 도메인을 사는 것이 나을까요, 만료된 도메인을 사는 것이 나을까요?","내 새 웹사이트가 구글에서 순위가 낮은 이유는?","만료된 도메인을 사는 것은 안전한가요?","좋은 백링크가 있는 도메인이란?","도메인을 살 때 백링크가 중요한 이유는?","만료된 도메인이 신뢰할 수 있는지 어떻게 알 수 있나요?","새 웹사이트에 만료된 도메인을 사용할 수 있나요?","만료된 도메인이 초보자에게 적합한가요?","왜 일부 도메인은 더 비싼가요?","나중에 만료된 도메인을 팔 수 있나요?","만료된 도메인이 SEO에 나쁠 수 있나요?","구매 시 주의해야 할 점은 무엇인가요?","구매 후 얼마나 빨리 시작할 수 있나요?","기술적 지식이 필요한가요?","쇼핑몰에 적합한가요?","도메인 권위란 무엇을 의미하나요?","링크 빌딩보다 나은가요?","좋은 만료된 도메인의 가격은 얼마인가요?","키워드가 중요한가요?","제휴 웹사이트에 사용할 수 있나요?","구글 페널티를 받았다면?","내 호스팅으로 어떻게 이전하나요?",".kr이나 .eu가 .com보다 나은가요?","기존 사이트로 리디렉션할 수 있나요?","구글에서 순위가 매겨지기까지 얼마나 걸리나요?","새 도메인에 비해 장점은 무엇인가요?","아무 마켓플레이스나 신뢰할 수 있나요?","가치 있는 백링크가 있는지 어떻게 아나요?","좋은 투자입니까?","새 사이트를 만들 때 기존 백링크는 어떻게 되나요?","지역 비즈니스에 사용할 수 있나요?","위험이 있나요?","왜 전문 판매자에게서 사야 하나요?"
  ], as: [
    "초보자라면 기억하기 쉽고 신뢰를 주는 도메인을 선택하세요.","새 도메인에는 기록이 없습니다. 만료된 도메인은 권위와 링크가 있을 수 있습니다.","빠른 구글 검색을 위해서는 좋은 만료된 도메인이 유리합니다.","새 사이트는 신뢰를 구축해야 합니다. 시간이 걸립니다.","네, 검증되고 신뢰할 수 있다면 안전합니다.","실제 관련 웹사이트에서 오는 참조 링크를 의미합니다.","백링크는 구글의 가장 중요한 순위 요소 중 하나입니다.","우리는 사이트 기록과 스팸 여부를 확인합니다.","네. 콘텐츠는 새롭지만 도메인은 이미 권위를 가져옵니다.","물론입니다. 빠른 가시성으로 가장 큰 이점을 얻습니다.","가격은 이름의 품질, SEO 가치에 따라 결정됩니다.","네. 강력한 도메인은 가치를 유지합니다.","나쁜 기록이 있을 때만 그렇습니다.","스팸 없는 기록, 관련 백링크, 논리적 이름이 중요합니다.","이전 후 즉시 사용할 수 있습니다.","아닙니다. 기술적으로 새 도메인과 똑같이 작동합니다.","네. 쇼핑몰은 특히 신뢰와 권위의 혜택을 받습니다.","링크와 기록을 바탕으로 한 도메인의 힘을 나타냅니다.","많은 기업가에게 그렇습니다. 링크 빌딩은 비쌉니다.","권위와 산업에 따라 다릅니다.","이전보다 덜 중요합니다. 명확한 이름이 더 중요합니다.","네, 관련 백링크가 있다면 특히 좋습니다.","페널티가 있는 도메인은 피해야 합니다.","새 등록업체에 입력할 EPP 코드를 받게 됩니다.","타겟 고객에 따라 다릅니다.","네. 301 리디렉션으로 SEO 가치를 전달합니다.","새 도메인보다 빠릅니다 - 종종 며칠 내에.","빠른 가시성, 기존 백링크가 장점입니다.","항상 그렇지는 않습니다. 전문가에게서 사세요.","Ahrefs나 MOZ 같은 도구를 사용하세요.","많은 투자자에게 그렇습니다.","링크된 사이트에서 삭제하지 않는 한 유지됩니다.","네, 특히 지역적 관련성이 있는 경우에 좋습니다.","미리 확인하지 않으면 위험할 수 있습니다.","사전 검증된 품질을 얻고 위험을 피할 수 있기 때문입니다."
  ] },
  hu: { title: "Teljes Útmutató: 35 Kérdés a Lejárt Domainnevekről és SEO-ról", qs: [
    "Milyen domaint vegyek kezdőként?","Mi a különbség egy új és egy lejárt domain között?","Jobb új domaint venni vagy lejártat?","Miért rangsorol olyan rosszul az új weboldalam a Google-ben?","Biztonságos a lejárt domain vásárlása?","Mit jelent a jó backlinkekkel rendelkező domain?","Miért fontosak a backlinkek?","Honnan tudom, hogy egy lejárt domain megbízható?","Használhatom új weboldalhoz?","Alkalmas kezdőknek?","Miért drágábbak egyes domainek?","Eladhatom később a lejárt domaint?","Lehet egy lejárt domain rossz a SEO-nak?","Mire kell figyelnem vásárláskor?","Milyen gyorsan kezdhetek?","Szükségem van technikai tudásra?","Alkalmas webáruházhoz?","Mit jelent a domain autoritás?","Jobb a lejárt domain, mint a linképítés?","Mennyibe kerül egy jó lejárt domain?","Fontos a kulcsszó a domainben?","Használhatom affiliate weboldalhoz?","Mi van, ha a Google büntette a domaint?","Hogyan vihetem át a saját tárhelyemre?","Jobb a .hu vagy .eu, mint a .com?","Átirányíthatom a meglévő weboldalamra?","Mennyi idő alatt rangsorol a Google-ben?","Milyen előnyei vannak az új domainnel szemben?","Megbízhatok bármilyen piactérben?","Honnan tudom, hogy vannak-e értékes backlinkjei?","Jó befektetés egy lejárt domain?","Mi történik a régi backlinkekkel?","Használhatom helyi vállalkozáshoz?","Vannak kockázatai a vásárlásnak?","Miért szakértő eladótól vásároljak?"
  ], as: [
    "Kezdőként könnyen megjegyezhető, bizalmat ébresztő domaint válasszon.","Az új domainnek nincs múltja. A lejártnak van tekintélye és linkjei.","A Google-ben való gyorsabb megtaláláshoz a lejárt domain egyértelmű előnyt jelent.","Az új oldalaknak fel kell építeniük a hitelességet.","Igen, ha ellenőrzött és megbízható.","Valódi, releváns weboldalakról származó hivatkozásai vannak.","A backlinkek a legfontosabb rangsorolási tényezők közé tartoznak.","Ellenőrizzük a weboldal történetét és a spam hiányát.","Igen. A tartalom új, de a domain már hozza a tekintélyt.","Abszolút. A kezdők profitálnak a leginkább a gyorsabb láthatóságból.","Az ár a név minőségétől és a SEO értéktől függ.","Igen. Egy erős lejárt domain megtartja az értékét.","Csak akkor, ha rossz a története.","Fontos: spammentes történet, logikus név.","Az átruházás után azonnal használhatja.","Nem. Műszakilag ugyanúgy működik, mint egy új domain.","Igen. A webáruházak különösen profitálnak a bizalomból.","A domain erejét mutatja a linkek alapján.","Sok vállalkozó számára igen. A linképítés drága.","Az árak a tekintélytől és az iparágtól függnek.","Kevésbé fontos, mint régen. A világos név fontosabb.","Igen, különösen releváns backlinkekkel.","A büntetett domaint kerülni kell. Minden domaint előre ellenőrzünk.","Kap egy EPP kódot, amit megad az új regisztrátoránál.","A célközönségtől függ.","Igen. 301-es átirányítással átviszi a SEO értéket.","Gyorsabb, mint az új domain - gyakran napokon belül.","Gyorsabb láthatóság, meglévő linkek, nagyobb bizalom.","Nem mindig. Sok piactér nem ellenőrzi a minőséget.","Használjon olyan eszközöket, mint az Ahrefs vagy a MOZ.","Sok vállalkozó és befektető számára igen.","A linkek megmaradnak, amíg el nem távolítják őket.","Igen, különösen, ha regionális jelentőségű.","Csak akkor, ha nem ellenőrzi előre a domaint.","Mert előre ellenőrzött minőséget kap és elkerüli a kockázatokat."
  ] },
  th: { title: "คู่มือฉบับสมบูรณ์: 35 คำถามเกี่ยวกับโดเมนที่หมดอายุและ SEO", qs: [
    "ในฐานะผู้เริ่มต้นฉันควรซื้อโดเมนใด?","ความแตกต่างระหว่างโดเมนใหม่และโดเมนที่หมดอายุคืออะไร?","ควรซื้อโดเมนใหม่หรือโดเมนที่หมดอายุดีกว่ากัน?","ทำไมเว็บไซต์ใหม่ของฉันถึงมีอันดับไม่ดีใน Google?","การซื้อโดเมนที่หมดอายุปลอดภัยหรือไม่?","โดเมนที่มีลิงก์ย้อนกลับที่ดีหมายความว่าอย่างไร?","ทำไมลิงก์ย้อนกลับจึงสำคัญ?","จะตรวจสอบได้อย่างไรว่าโดเมนน่าเชื่อถือ?","ฉันสามารถใช้สำหรับเว็บไซต์ใหม่ได้หรือไม่?","เหมาะสำหรับผู้เริ่มต้นหรือไม่?","ทำไมบางโดเมนจึงแพงกว่าโดเมนอื่น?","ฉันสามารถขายต่อในภายหลังได้หรือไม่?","อาจส่งผลเสียต่อ SEO หรือไม่?","ควรใส่ใจอะไรเมื่อซื้อ?","เริ่มใช้ได้เร็วแค่ไหน?","ฉันต้องการความรู้ด้านเทคนิคหรือไม่?","เหมาะสำหรับร้านค้าออนไลน์หรือไม่?","Domain Authority หมายถึงอะไร?","ดีกว่าการสร้างลิงก์หรือไม่?","โดเมนที่หมดอายุราคาเท่าไหร่?","คีย์เวิร์ดในโดเมนมีความสำคัญหรือไม่?","ใช้สำหรับเว็บไซต์ตัวแทนจำหน่ายได้หรือไม่?","เกิดอะไรขึ้นถ้าโดเมนถูกลงโทษโดย Google?","จะถ่ายโอนโดเมนไปยังโฮสติ้งของฉันได้อย่างไร?","โดเมน .th หรือ .eu ดีกว่า .com หรือไม่?","ฉันสามารถเปลี่ยนเส้นทางไปยังเว็บไซต์ที่มีอยู่ของฉันได้หรือไม่?","ใช้เวลานานแค่ไหนในการจัดอันดับใน Google?","ข้อดีเมื่อเทียบกับโดเมนใหม่คืออะไร?","ฉันสามารถเชื่อถือโดเมนจากตลาดทั่วไปได้หรือไม่?","ฉันจะทราบได้อย่างไรว่าโดเมนมีลิงก์ที่มีค่า?","การลงทุนในโดเมนที่หมดอายุเป็นความคิดที่ดีหรือไม่?","เกิดอะไรขึ้นกับลิงก์ย้อนกลับเก่าเมื่อฉันสร้างเว็บไซต์ใหม่?","สามารถใช้สำหรับธุรกิจในท้องถิ่นได้หรือไม่?","มีความเสี่ยงในการซื้อหรือไม่?","ทำไมต้องซื้อจากผู้ขายที่เชี่ยวชาญ?"
  ], as: [
    "ในฐานะผู้เริ่มต้น ให้เลือกโดเมนที่จำง่ายและน่าเชื่อถือ","โดเมนใหม่ไม่มีประวัติ โดเมนที่หมดอายุอาจมีลิงก์และอำนาจ","เพื่อการค้นพบที่รวดเร็วขึ้นใน Google โดเมนที่หมดอายุให้ข้อได้เปรียบที่ชัดเจน","เว็บไซต์ใหม่ต้องสร้างความน่าเชื่อถือ ซึ่งใช้เวลานาน","ปลอดภัย ตราบใดที่ผ่านการตรวจสอบและเชื่อถือได้","มีการอ้างอิงจากเว็บไซต์จริงและมีความเกี่ยวข้อง","ลิงก์ย้อนกลับเป็นหนึ่งในปัจจัยการจัดอันดับที่สำคัญที่สุด","เราตรวจสอบประวัติเว็บไซต์และคุณภาพของลิงก์","ได้ เนื้อหาใหม่แต่โดเมนนำอำนาจมาให้แล้ว","แน่นอน ผู้เริ่มต้นได้ประโยชน์จากการมองเห็นที่เร็วขึ้น","ราคาพิจารณาจากคุณภาพของชื่อและมูลค่า SEO","ได้ โดเมนที่แข็งแกร่งจะรักษามูลค่าของมันไว้","ต่อเมื่อมีประวัติที่ไม่ดีเท่านั้น","ข้อสำคัญ: ไม่มีสแปม ลิงก์ที่เกี่ยวข้อง ชื่อที่สมเหตุสมผล","หลังจากถ่ายโอน คุณสามารถใช้โดเมนได้ทันที","ไม่ โดเมนทำงานทางเทคนิคเหมือนกับโดเมนใหม่","ใช่ ร้านค้าออนไลน์ได้รับประโยชน์จากความน่าเชื่อถือ","แสดงถึงความแข็งแกร่งของโดเมนตามลิงก์และประวัติ","สำหรับผู้ประกอบการหลายคน การสร้างลิงก์มีราคาแพง","ราคาแตกต่างกันไปตามอำนาจและอุตสาหกรรม","สำคัญน้อยกว่าเมื่อก่อน ชื่อที่ชัดเจนสำคัญกว่า","ใช่ โดยเฉพาะอย่างยิ่งหากมีลิงก์ที่เกี่ยวข้อง","ควรหลีกเลี่ยงโดเมนที่ถูกลงโทษ","คุณจะได้รับรหัส EPP หลังจากซื้อ","ขึ้นอยู่กับกลุ่มเป้าหมายของคุณ","ใช่ ด้วยการเปลี่ยนเส้นทาง 301 คุณจะถ่ายโอนมูลค่า SEO","เร็วกว่าโดเมนใหม่ - มักใช้เวลาเป็นวันหรือสัปดาห์","การมองเห็นที่เร็วขึ้น ลิงก์ที่มีอยู่ ความไว้วางใจที่มากกว่า","ไม่เสมอไป ตลาดหลายแห่งไม่ตรวจสอบคุณภาพ","ใช้เครื่องมือเช่น Ahrefs หรือ MOZ","สำหรับผู้ประกอบการและนักลงทุน ถือเป็นความคิดที่ดี","ลิงก์จะยังคงอยู่ตราบใดที่ไม่ถูกลบออก","ใช่ โดยเฉพาะอย่างยิ่งหากมีความเกี่ยวข้องในระดับภูมิภาค","เฉพาะในกรณีที่คุณไม่ได้ตรวจสอบล่วงหน้า","เพราะคุณได้คุณภาพที่ตรวจสอบแล้วและหลีกเลี่ยงความเสี่ยง"
  ] },
  vi: { title: "Hướng Dẫn Đầy Đủ: 35 Câu Hỏi về Tên Miền Hết Hạn và SEO", qs: ["Câu hỏi 1"], as: ["Câu trả lời 1"] },
  id: { title: "Panduan Lengkap: 35 Pertanyaan tentang Domain Kedaluwarsa & SEO", qs: ["Pertanyaan 1"], as: ["Jawaban 1"] },
  et: { title: "Täiuslik Juhend: 35 Küsimust Aegunud Domeeninimede ja SEO kohta", qs: ["Küsimus 1"], as: ["Vastus 1"] },
  lv: { title: "Pilnīgs Ceļvedis: 35 Jautājumi par Beigušiem Domēniem un SEO", qs: ["Jautājums 1"], as: ["Atbilde 1"] },
  lt: { title: "Pilnas Vadovas: 35 Klausimai apie Pasibaigusius Domenų Vardus ir SEO", qs: ["Klausimas 1"], as: ["Atsakymas 1"] },
  is: { title: "Heildarstefna: 35 Spurningar um Útrunnin Lén og SEO", qs: ["Spurning 1"], as: ["Svar 1"] },
  sq: { title: "Udhëzues i Plotë: 35 Pyetje për Domenet e Skaduara dhe SEO", qs: ["Pyetja 1"], as: ["Përgjigja 1"] },
  mk: { title: "Целосен Водич: 35 Прашања за Истечени Домени и SEO", qs: ["Прашање 1"], as: ["Одговор 1"] },
  bs: { title: "Kompletan Vodič: 35 Pitanja o Isteklim Domenima i SEO", qs: ["Pitanje 1"], as: ["Odgovor 1"] },
  lb: { title: "Komplette Guide: 35 Froen iwwer Ofgelaf Domainnimm an SEO", qs: ["Fro 1"], as: ["Äntwert 1"] },
  bn: { title: "সম্পূর্ণ গাইড: মেয়াদোত্তীর্ণ ডোমেন নাম ও SEO সম্পর্কে 35টি প্রশ্ন", qs: ["প্রশ্ন 1"], as: ["উত্তর 1"] },
  ms: { title: "Panduan Lengkap: 35 Soalan tentang Domain Tamat Tempoh & SEO", qs: ["Soalan 1"], as: ["Jawapan 1"] }
};

// Generate 35 FAQs using English as a fallback for missing questions in the simplified arrays
export const getFullTranslatedFaqs = (lang: string, enQs: string[], enAs: string[]): FaqData => {
  const d = faqTranslationsRemaining[lang];
  if (!d) return { sectionTitle: "Complete Guide: 35 Questions", faqs: mk35(enQs, enAs) };
  
  // Fill the 35 questions/answers. If translation is short (like for the simplified ones), fall back to English or pad
  const finalQs = enQs.map((q, i) => d.qs[i] || q);
  const finalAs = enAs.map((a, i) => d.as[i] || a);
  
  return { sectionTitle: d.title, faqs: mk35(finalQs, finalAs) };
};
