import { Badge } from "@/components/ui/badge";
import { Shield } from "lucide-react";

type Lang = 'en' | 'nl' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'pl' | 'tr' | 'ar' | 'hi' | 'ja' | 'zh' | 'sv' | 'no' | 'da' | 'fi' | 'cs' | 'el' | 'ru' | 'ro' | 'bg' | 'uk' | 'hr' | 'sk' | 'sr' | 'sl' | 'ko' | 'hu' | 'th' | 'vi' | 'id' | 'et' | 'lv' | 'lt' | 'is' | 'sq' | 'mk' | 'bs' | 'lb' | 'bn' | 'ms';

const t: Record<Lang, {
  badge: string; title: string;
  euInfo: string; nonEuInfo: string; trusteeLink: string;
  vatNote: string; transferNote: string;
}> = {
  en: { badge: "Important to Know", title: "Before You Buy", euInfo: "EU residents can register .EU domains directly. No additional services needed.", nonEuInfo: "Non-EU residents can register .EU domains via a trustee service — a registrar provides a verified EU address for you.", trusteeLink: "What is a Trustee Service?", vatNote: "All prices include VAT for EU customers (EU VAT regulation).", transferNote: "After payment, you receive the transfer token (EPP/Auth code) within 24 hours via email." },
  nl: { badge: "Belangrijk om te Weten", title: "Voordat u Koopt", euInfo: "EU-inwoners kunnen .EU-domeinen direct registreren. Geen extra diensten nodig.", nonEuInfo: "Niet-EU-inwoners kunnen .EU-domeinen registreren via een trustee-service — een registrar biedt een geverifieerd EU-adres voor u.", trusteeLink: "Wat is een Trustee Service?", vatNote: "Alle prijzen zijn inclusief BTW voor EU-klanten (EU BTW-regelgeving).", transferNote: "Na betaling ontvangt u de transfertoken (EPP/Auth-code) binnen 24 uur per e-mail." },
  de: { badge: "Wichtig zu Wissen", title: "Vor dem Kauf", euInfo: "EU-Einwohner können .EU-Domains direkt registrieren. Keine zusätzlichen Dienste erforderlich.", nonEuInfo: "Nicht-EU-Einwohner können .EU-Domains über einen Treuhänder-Service registrieren.", trusteeLink: "Was ist ein Treuhänder-Service?", vatNote: "Alle Preise verstehen sich inklusive MwSt. für EU-Kunden.", transferNote: "Nach Zahlung erhalten Sie den Transfer-Token (EPP/Auth-Code) innerhalb von 24 Stunden per E-Mail." },
  fr: { badge: "Important à Savoir", title: "Avant d'Acheter", euInfo: "Les résidents de l'UE peuvent enregistrer des domaines .EU directement.", nonEuInfo: "Les résidents hors UE peuvent enregistrer des domaines .EU via un service de mandataire.", trusteeLink: "Qu'est-ce qu'un Service de Mandataire?", vatNote: "Tous les prix incluent la TVA pour les clients de l'UE.", transferNote: "Après paiement, vous recevez le jeton de transfert (code EPP/Auth) dans les 24 heures par e-mail." },
  es: { badge: "Importante Saber", title: "Antes de Comprar", euInfo: "Los residentes de la UE pueden registrar dominios .EU directamente.", nonEuInfo: "Los residentes fuera de la UE pueden registrar dominios .EU a través de un servicio de fideicomisario.", trusteeLink: "¿Qué es un Servicio de Fideicomisario?", vatNote: "Todos los precios incluyen IVA para clientes de la UE.", transferNote: "Después del pago, recibirá el token de transferencia (código EPP/Auth) en 24 horas por correo electrónico." },
  it: { badge: "Importante da Sapere", title: "Prima di Acquistare", euInfo: "I residenti UE possono registrare domini .EU direttamente.", nonEuInfo: "I residenti extra-UE possono registrare domini .EU tramite un servizio fiduciario.", trusteeLink: "Cos'è un Servizio Fiduciario?", vatNote: "Tutti i prezzi includono IVA per i clienti UE.", transferNote: "Dopo il pagamento, riceverai il token di trasferimento (codice EPP/Auth) entro 24 ore via email." },
  pt: { badge: "Importante Saber", title: "Antes de Comprar", euInfo: "Residentes da UE podem registrar domínios .EU diretamente.", nonEuInfo: "Residentes fora da UE podem registrar domínios .EU através de um serviço de representante.", trusteeLink: "O que é um Serviço de Representante?", vatNote: "Todos os preços incluem IVA para clientes da UE.", transferNote: "Após o pagamento, você receberá o token de transferência (código EPP/Auth) em 24 horas por e-mail." },
  pl: { badge: "Ważne Informacje", title: "Przed Zakupem", euInfo: "Mieszkańcy UE mogą rejestrować domeny .EU bezpośrednio.", nonEuInfo: "Mieszkańcy spoza UE mogą rejestrować domeny .EU za pośrednictwem usługi powierniczej.", trusteeLink: "Czym jest Usługa Powiernicza?", vatNote: "Wszystkie ceny zawierają VAT dla klientów z UE.", transferNote: "Po dokonaniu płatności otrzymasz token transferu (kod EPP/Auth) w ciągu 24 godzin e-mailem." },
  tr: { badge: "Bilinmesi Gerekenler", title: "Satın Almadan Önce", euInfo: "AB sakinleri .EU alan adlarını doğrudan kaydedebilir.", nonEuInfo: "AB dışı sakinler, bir vekil hizmeti aracılığıyla .EU alan adlarını kaydedebilir.", trusteeLink: "Vekil Hizmeti Nedir?", vatNote: "Tüm fiyatlar AB müşterileri için KDV dahildir.", transferNote: "Ödeme sonrası transfer tokenini (EPP/Auth kodu) 24 saat içinde e-posta ile alırsınız." },
  ar: { badge: "مهم أن تعرف", title: "قبل الشراء", euInfo: "يمكن لسكان الاتحاد الأوروبي تسجيل نطاقات .EU مباشرة.", nonEuInfo: "يمكن لغير المقيمين في الاتحاد الأوروبي تسجيل نطاقات .EU عبر خدمة الوكيل.", trusteeLink: "ما هي خدمة الوكيل؟", vatNote: "جميع الأسعار تشمل ضريبة القيمة المضافة لعملاء الاتحاد الأوروبي.", transferNote: "بعد الدفع، ستتلقى رمز النقل (EPP/Auth) خلال 24 ساعة عبر البريد الإلكتروني." },
  hi: { badge: "जानना ज़रूरी", title: "खरीदने से पहले", euInfo: "EU निवासी .EU डोमेन सीधे पंजीकृत कर सकते हैं।", nonEuInfo: "गैर-EU निवासी ट्रस्टी सेवा के माध्यम से .EU डोमेन पंजीकृत कर सकते हैं।", trusteeLink: "ट्रस्टी सेवा क्या है?", vatNote: "सभी कीमतों में EU ग्राहकों के लिए VAT शामिल है।", transferNote: "भुगतान के बाद, आपको 24 घंटे के भीतर ट्रांसफर टोकन (EPP/Auth कोड) ईमेल द्वारा प्राप्त होगा।" },
  ja: { badge: "重要な情報", title: "購入前に", euInfo: "EU居住者は.EUドメインを直接登録できます。", nonEuInfo: "EU非居住者はトラスティサービスを通じて.EUドメインを登録できます。", trusteeLink: "トラスティサービスとは？", vatNote: "すべての価格にはEU顧客向けのVATが含まれています。", transferNote: "お支払い後、24時間以内に転送トークン（EPP/Authコード）をメールでお届けします。" },
  zh: { badge: "重要须知", title: "购买前", euInfo: "欧盟居民可以直接注册.EU域名。", nonEuInfo: "非欧盟居民可以通过信托服务注册.EU域名。", trusteeLink: "什么是信托服务？", vatNote: "所有价格均包含欧盟客户的增值税。", transferNote: "付款后，您将在24小时内通过电子邮件收到转移令牌（EPP/Auth代码）。" },
  sv: { badge: "Viktigt att Veta", title: "Innan du Köper", euInfo: "EU-invånare kan registrera .EU-domäner direkt.", nonEuInfo: "Icke-EU-invånare kan registrera .EU-domäner via en trustee-tjänst.", trusteeLink: "Vad är en Trustee-Tjänst?", vatNote: "Alla priser inkluderar moms för EU-kunder.", transferNote: "Efter betalning får du överföringstoken (EPP/Auth-kod) inom 24 timmar via e-post." },
  no: { badge: "Viktig å Vite", title: "Før du Kjøper", euInfo: "EU-innbyggere kan registrere .EU-domener direkte.", nonEuInfo: "Ikke-EU-innbyggere kan registrere .EU-domener via en trustee-tjeneste.", trusteeLink: "Hva er en Trustee-Tjeneste?", vatNote: "Alle priser inkluderer MVA for EU-kunder.", transferNote: "Etter betaling mottar du overføringstoken (EPP/Auth-kode) innen 24 timer via e-post." },
  da: { badge: "Vigtigt at Vide", title: "Før du Køber", euInfo: "EU-borgere kan registrere .EU-domæner direkte.", nonEuInfo: "Ikke-EU-borgere kan registrere .EU-domæner via en trustee-tjeneste.", trusteeLink: "Hvad er en Trustee-Tjeneste?", vatNote: "Alle priser inkluderer moms for EU-kunder.", transferNote: "Efter betaling modtager du overførselstoken (EPP/Auth-kode) inden for 24 timer via e-mail." },
  fi: { badge: "Tärkeää Tietää", title: "Ennen Ostoa", euInfo: "EU-asukkaat voivat rekisteröidä .EU-verkkotunnuksia suoraan.", nonEuInfo: "EU:n ulkopuoliset asukkaat voivat rekisteröidä .EU-verkkotunnuksia trustee-palvelun kautta.", trusteeLink: "Mikä on Trustee-Palvelu?", vatNote: "Kaikki hinnat sisältävät ALV:n EU-asiakkaille.", transferNote: "Maksun jälkeen saat siirtotunnuksen (EPP/Auth-koodin) 24 tunnin kuluessa sähköpostitse." },
  cs: { badge: "Důležité Vědět", title: "Před Nákupem", euInfo: "Rezidenti EU mohou registrovat .EU domény přímo.", nonEuInfo: "Nerezidenti EU mohou registrovat .EU domény prostřednictvím trustee služby.", trusteeLink: "Co je Trustee Služba?", vatNote: "Všechny ceny zahrnují DPH pro zákazníky z EU.", transferNote: "Po zaplacení obdržíte přenosový token (EPP/Auth kód) do 24 hodin e-mailem." },
  el: { badge: "Σημαντικό να Γνωρίζετε", title: "Πριν Αγοράσετε", euInfo: "Οι κάτοικοι ΕΕ μπορούν να καταχωρήσουν .EU domains απευθείας.", nonEuInfo: "Οι μη κάτοικοι ΕΕ μπορούν να καταχωρήσουν .EU domains μέσω υπηρεσίας εμπιστοσύνης.", trusteeLink: "Τι είναι η Υπηρεσία Εμπιστοσύνης;", vatNote: "Όλες οι τιμές περιλαμβάνουν ΦΠΑ για πελάτες ΕΕ.", transferNote: "Μετά την πληρωμή, θα λάβετε το token μεταφοράς (κωδικός EPP/Auth) εντός 24 ωρών μέσω email." },
  ru: { badge: "Важно Знать", title: "Перед Покупкой", euInfo: "Жители ЕС могут регистрировать .EU домены напрямую.", nonEuInfo: "Нерезиденты ЕС могут регистрировать .EU домены через трастовую службу.", trusteeLink: "Что такое Трастовая Служба?", vatNote: "Все цены включают НДС для клиентов из ЕС.", transferNote: "После оплаты вы получите токен переноса (EPP/Auth код) в течение 24 часов по электронной почте." },
  ro: { badge: "Important de Știut", title: "Înainte de Cumpărare", euInfo: "Rezidenții UE pot înregistra domenii .EU direct.", nonEuInfo: "Nerezidenții UE pot înregistra domenii .EU printr-un serviciu de mandatar.", trusteeLink: "Ce este un Serviciu de Mandatar?", vatNote: "Toate prețurile includ TVA pentru clienții din UE.", transferNote: "După plată, veți primi tokenul de transfer (cod EPP/Auth) în 24 de ore prin e-mail." },
  bg: { badge: "Важно да Знаете", title: "Преди Покупка", euInfo: "Жителите на ЕС могат да регистрират .EU домейни директно.", nonEuInfo: "Нерезидентите на ЕС могат да регистрират .EU домейни чрез доверителна служба.", trusteeLink: "Какво е Доверителна Служба?", vatNote: "Всички цени включват ДДС за клиенти от ЕС.", transferNote: "След плащане ще получите токен за трансфер (EPP/Auth код) в рамките на 24 часа по имейл." },
  uk: { badge: "Важливо Знати", title: "Перед Покупкою", euInfo: "Мешканці ЄС можуть реєструвати .EU домени безпосередньо.", nonEuInfo: "Нерезиденти ЄС можуть реєструвати .EU домени через трастову службу.", trusteeLink: "Що таке Трастова Служба?", vatNote: "Всі ціни включають ПДВ для клієнтів з ЄС.", transferNote: "Після оплати ви отримаєте токен переносу (EPP/Auth код) протягом 24 годин електронною поштою." },
  hr: { badge: "Važno Znati", title: "Prije Kupnje", euInfo: "Stanovnici EU mogu izravno registrirati .EU domene.", nonEuInfo: "Nestanovnici EU mogu registrirati .EU domene putem skrbničke usluge.", trusteeLink: "Što je Skrbnička Usluga?", vatNote: "Sve cijene uključuju PDV za kupce iz EU.", transferNote: "Nakon plaćanja, primit ćete token za prijenos (EPP/Auth kod) u roku od 24 sata e-poštom." },
  sk: { badge: "Dôležité Vedieť", title: "Pred Kúpou", euInfo: "Obyvatelia EÚ môžu registrovať .EU domény priamo.", nonEuInfo: "Nerezidenti EÚ môžu registrovať .EU domény prostredníctvom správcovskej služby.", trusteeLink: "Čo je Správcovská Služba?", vatNote: "Všetky ceny zahŕňajú DPH pre zákazníkov z EÚ.", transferNote: "Po zaplatení dostanete prenosový token (EPP/Auth kód) do 24 hodín e-mailom." },
  sr: { badge: "Важно да Знате", title: "Пре Куповине", euInfo: "Становници ЕУ могу директно регистровати .EU домене.", nonEuInfo: "Нерезиденти ЕУ могу регистровати .EU домене путем повереничке услуге.", trusteeLink: "Шта је Повереничка Услуга?", vatNote: "Све цене укључују ПДВ за купце из ЕУ.", transferNote: "Након плаћања, примићете токен за пренос (EPP/Auth код) у року од 24 сата путем е-поште." },
  sl: { badge: "Pomembno Vedeti", title: "Pred Nakupom", euInfo: "Prebivalci EU lahko neposredno registrirajo .EU domene.", nonEuInfo: "Nerezidenti EU lahko registrirajo .EU domene prek skrbniške storitve.", trusteeLink: "Kaj je Skrbniška Storitev?", vatNote: "Vse cene vključujejo DDV za stranke iz EU.", transferNote: "Po plačilu boste prejeli žeton za prenos (EPP/Auth koda) v 24 urah po elektronski pošti." },
  ko: { badge: "알아두세요", title: "구매 전 안내", euInfo: "EU 거주자는 .EU 도메인을 직접 등록할 수 있습니다.", nonEuInfo: "비EU 거주자는 수탁 서비스를 통해 .EU 도메인을 등록할 수 있습니다.", trusteeLink: "수탁 서비스란?", vatNote: "모든 가격에는 EU 고객을 위한 VAT가 포함되어 있습니다.", transferNote: "결제 후 24시간 이내에 이전 토큰(EPP/Auth 코드)을 이메일로 받으실 수 있습니다." },
  hu: { badge: "Fontos Tudnivalók", title: "Vásárlás Előtt", euInfo: "Az EU lakosai közvetlenül regisztrálhatnak .EU domaineket.", nonEuInfo: "A nem EU-s lakosok megbízotti szolgáltatáson keresztül regisztrálhatnak .EU domaineket.", trusteeLink: "Mi az a Megbízotti Szolgáltatás?", vatNote: "Minden ár tartalmazza az ÁFÁ-t EU ügyfelek számára.", transferNote: "Fizetés után 24 órán belül megkapja az átviteli tokent (EPP/Auth kódot) e-mailben." },
  th: { badge: "ข้อมูลสำคัญ", title: "ก่อนซื้อ", euInfo: "ผู้อยู่อาศัยใน EU สามารถลงทะเบียนโดเมน .EU ได้โดยตรง", nonEuInfo: "ผู้อยู่อาศัยนอก EU สามารถลงทะเบียนโดเมน .EU ผ่านบริการทรัสตี", trusteeLink: "บริการทรัสตีคืออะไร?", vatNote: "ราคาทั้งหมดรวม VAT สำหรับลูกค้า EU แล้ว", transferNote: "หลังชำระเงิน คุณจะได้รับโทเค็นการโอน (รหัส EPP/Auth) ภายใน 24 ชั่วโมงทางอีเมล" },
  vi: { badge: "Thông Tin Quan Trọng", title: "Trước Khi Mua", euInfo: "Cư dân EU có thể đăng ký tên miền .EU trực tiếp.", nonEuInfo: "Cư dân ngoài EU có thể đăng ký tên miền .EU thông qua dịch vụ ủy thác.", trusteeLink: "Dịch Vụ Ủy Thác là gì?", vatNote: "Tất cả giá đã bao gồm VAT cho khách hàng EU.", transferNote: "Sau khi thanh toán, bạn sẽ nhận được mã chuyển nhượng (EPP/Auth) trong vòng 24 giờ qua email." },
  id: { badge: "Penting Diketahui", title: "Sebelum Membeli", euInfo: "Penduduk EU dapat mendaftarkan domain .EU secara langsung.", nonEuInfo: "Penduduk non-EU dapat mendaftarkan domain .EU melalui layanan wali amanat.", trusteeLink: "Apa itu Layanan Wali Amanat?", vatNote: "Semua harga sudah termasuk PPN untuk pelanggan EU.", transferNote: "Setelah pembayaran, Anda akan menerima token transfer (kode EPP/Auth) dalam 24 jam melalui email." },
  et: { badge: "Oluline Teada", title: "Enne Ostmist", euInfo: "EL elanikud saavad .EU domeene otse registreerida.", nonEuInfo: "Väljaspool EL elavad isikud saavad .EU domeene registreerida usaldusisiku teenuse kaudu.", trusteeLink: "Mis on Usaldusisiku Teenus?", vatNote: "Kõik hinnad sisaldavad käibemaksu EL klientidele.", transferNote: "Pärast maksmist saate ülekande tokeni (EPP/Auth koodi) 24 tunni jooksul e-postiga." },
  lv: { badge: "Svarīgi Zināt", title: "Pirms Pirkuma", euInfo: "ES iedzīvotāji var reģistrēt .EU domēnus tieši.", nonEuInfo: "Ne-ES iedzīvotāji var reģistrēt .EU domēnus, izmantojot pilnvarnieka pakalpojumu.", trusteeLink: "Kas ir Pilnvarnieka Pakalpojums?", vatNote: "Visas cenas ietver PVN ES klientiem.", transferNote: "Pēc apmaksas jūs saņemsiet pārsūtīšanas tokenu (EPP/Auth kodu) 24 stundu laikā pa e-pastu." },
  lt: { badge: "Svarbu Žinoti", title: "Prieš Perkant", euInfo: "ES gyventojai gali tiesiogiai registruoti .EU domenus.", nonEuInfo: "Ne ES gyventojai gali registruoti .EU domenus per patikėtinio asmens paslaugą.", trusteeLink: "Kas yra Patikėtinio Asmens Paslauga?", vatNote: "Visos kainos apima PVM ES klientams.", transferNote: "Po apmokėjimo gausite perdavimo ženklą (EPP/Auth kodą) per 24 valandas el. paštu." },
  is: { badge: "Mikilvægt að Vita", title: "Áður en þú Kaupir", euInfo: "ESB-búar geta skráð .EU lén beint.", nonEuInfo: "Einstaklingar utan ESB geta skráð .EU lén í gegnum umboðsþjónustu.", trusteeLink: "Hvað er Umboðsþjónusta?", vatNote: "Öll verð innihalda virðisaukaskatt fyrir ESB-viðskiptavini.", transferNote: "Eftir greiðslu færðu flutningsmerki (EPP/Auth kóða) innan 24 klukkustunda í tölvupósti." },
  sq: { badge: "E Rëndësishme", title: "Para Blerjes", euInfo: "Banorët e BE-së mund të regjistrojnë domenet .EU drejtpërdrejt.", nonEuInfo: "Banorët jashtë BE-së mund të regjistrojnë domenet .EU përmes një shërbimi kujdestari.", trusteeLink: "Çfarë është Shërbimi i Kujdestarisë?", vatNote: "Të gjitha çmimet përfshijnë TVSH-në për klientët e BE-së.", transferNote: "Pas pagesës, do të merrni tokenin e transferimit (kodin EPP/Auth) brenda 24 orëve me email." },
  mk: { badge: "Важно да Знаете", title: "Пред Купување", euInfo: "Жителите на ЕУ можат директно да регистрираат .EU домени.", nonEuInfo: "Нерезидентите на ЕУ можат да регистрираат .EU домени преку старателска услуга.", trusteeLink: "Што е Старателска Услуга?", vatNote: "Сите цени вклучуваат ДДВ за клиенти од ЕУ.", transferNote: "По плаќањето, ќе добиете токен за пренос (EPP/Auth код) во рок од 24 часа по е-пошта." },
  bs: { badge: "Važno Znati", title: "Prije Kupovine", euInfo: "Stanovnici EU mogu direktno registrirati .EU domene.", nonEuInfo: "Nerezidenti EU mogu registrirati .EU domene putem starateljske usluge.", trusteeLink: "Šta je Starateljska Usluga?", vatNote: "Sve cijene uključuju PDV za kupce iz EU.", transferNote: "Nakon plaćanja, primit ćete token za prijenos (EPP/Auth kod) u roku od 24 sata e-poštom." },
  lb: { badge: "Wichteg ze Wëssen", title: "Virum Kaf", euInfo: "EU-Awunner kënnen .EU-Domainen direkt registréieren.", nonEuInfo: "Net-EU-Awunner kënnen .EU-Domainen iwwer en Trustee-Service registréieren.", trusteeLink: "Wat ass en Trustee-Service?", vatNote: "All Präisser si mat TVA fir EU-Clienten.", transferNote: "No der Bezuelung kritt Dir den Transfertoken (EPP/Auth Code) bannent 24 Stonnen per E-Mail." },
  bn: { badge: "জানা গুরুত্বপূর্ণ", title: "কেনার আগে", euInfo: "EU বাসিন্দারা সরাসরি .EU ডোমেইন নিবন্ধন করতে পারেন।", nonEuInfo: "অ-EU বাসিন্দারা ট্রাস্টি সেবার মাধ্যমে .EU ডোমেইন নিবন্ধন করতে পারেন।", trusteeLink: "ট্রাস্টি সেবা কী?", vatNote: "সকল মূল্যে EU গ্রাহকদের জন্য VAT অন্তর্ভুক্ত।", transferNote: "পেমেন্টের পরে, আপনি 24 ঘণ্টার মধ্যে ইমেইলে ট্রান্সফার টোকেন (EPP/Auth কোড) পাবেন।" },
  ms: { badge: "Penting untuk Diketahui", title: "Sebelum Membeli", euInfo: "Penduduk EU boleh mendaftarkan domain .EU secara langsung.", nonEuInfo: "Penduduk bukan EU boleh mendaftarkan domain .EU melalui perkhidmatan pemegang amanah.", trusteeLink: "Apakah Perkhidmatan Pemegang Amanah?", vatNote: "Semua harga termasuk VAT untuk pelanggan EU.", transferNote: "Selepas pembayaran, anda akan menerima token pemindahan (kod EPP/Auth) dalam masa 24 jam melalui e-mel." },
};

const ImportantToKnowSection = ({ lang }: { lang: string }) => {
  const l = t[lang as Lang] || t.en;
  return (
    <section className="py-10 bg-gradient-to-b from-slate-950 to-slate-900">
      <div className="container mx-auto px-4">
        <div className="max-w-5xl mx-auto">
          <div className="bg-gradient-to-br from-amber-500/10 to-slate-800/30 border border-amber-500/30 rounded-2xl p-6 md:p-8">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-6 h-6 text-amber-400 flex-shrink-0" />
              <Badge className="bg-amber-500/10 text-amber-400 border-amber-500/30">{l.badge}</Badge>
            </div>
            <h3 className="text-xl font-bold text-white mb-4">{l.title}</h3>
            <div className="space-y-3 text-sm sm:text-base">
              <div className="flex items-start gap-2"><span className="text-green-400 mt-0.5">✅</span><span className="text-slate-300">{l.euInfo}</span></div>
              <div className="flex items-start gap-2"><span className="text-amber-400 mt-0.5">🌐</span><span className="text-slate-300">{l.nonEuInfo} <a href="#trustee-service-section" className="text-amber-400 hover:text-amber-300 underline">{l.trusteeLink}</a></span></div>
              <div className="flex items-start gap-2"><span className="text-blue-400 mt-0.5">💡</span><span className="text-slate-300">{l.vatNote}</span></div>
              <div className="flex items-start gap-2"><span className="text-purple-400 mt-0.5">📧</span><span className="text-slate-300">{l.transferNote}</span></div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ImportantToKnowSection;
