import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

const translations: Record<string, { badge: string; title: string; desc: string; questions: { q: string; a: string }[] }> = {
  sv: { badge: "FAQ", title: "Vanliga frågor", desc: "Vanliga frågor från fotografer om juridiskt skydd", questions: [{ q: "Hur kan jag fotografera i svagt ljus utan blixt?", a: "Använd en stor bländare (f/1.8–f/2.8), lägre slutartid och öka ISO försiktigt. Stabilisera kameran på stativ. Fotografera i RAW för bättre efterbearbetning." }, { q: "Vad är det bästa objektivet för porträttfotografering?", a: "Ett primobjektiv med stor bländare, som 50mm f/1.8 eller 85mm f/1.4, är idealiskt för porträtt med vacker bakgrundsoskärpa." }, { q: "Hur tar jag bra landskapsfoton?", a: "Använd liten bländare (f/8–f/16) för stort skärpedjup, fokusera en tredjedel in i scenen och använd stativ. Bästa tiderna är soluppgång och solnedgång." }, { q: "Vad är vitbalans i fotografering?", a: "Vitbalans justerar färgtemperaturen för att säkerställa att vita färger ser neutrala ut under olika belysning." }, { q: "Hur kan jag skapa bättre kompositioner?", a: "Tillämpa tekniker som tredjedelsregeln, symmetri, ledande linjer och inramning. Undvik att centrera varje motiv." }] },
  pl: { badge: "FAQ", title: "Często zadawane pytania", desc: "Najczęstsze pytania fotografów dotyczące ochrony prawnej", questions: [{ q: "Jak fotografować przy słabym oświetleniu bez lampy?", a: "Użyj szerokiej przysłony (f/1.8–f/2.8), wolniejszego czasu naświetlania i ostrożnie zwiększ ISO. Stabilizuj aparat na statywie." }, { q: "Jaki jest najlepszy obiektyw do portretów?", a: "Obiektyw stałoogniskowy o szerokiej przysłonie, jak 50mm f/1.8 lub 85mm f/1.4, jest idealny do portretów." }, { q: "Jak robić dobre zdjęcia krajobrazu?", a: "Użyj małej przysłony (f/8–f/16), ustaw ostrość na jedną trzecią sceny i użyj statywu." }, { q: "Co to jest balans bieli?", a: "Balans bieli dostosowuje temperaturę kolorów, aby biel wyglądała neutralnie przy różnym oświetleniu." }, { q: "Jak tworzyć lepsze kompozycje?", a: "Stosuj techniki jak zasada trójpodziału, symetria, linie prowadzące i kadrowanie." }] },
  el: { badge: "FAQ", title: "Συχνές ερωτήσεις", desc: "Κοινές ερωτήσεις από φωτογράφους", questions: [{ q: "Πώς φωτογραφίζω σε χαμηλό φως;", a: "Χρησιμοποιήστε μεγάλο διάφραγμα, αργή ταχύτητα κλείστρου και αυξήστε το ISO. Χρησιμοποιήστε τρίποδο." }, { q: "Ποιος είναι ο καλύτερος φακός για πορτρέτα;", a: "Ένας σταθερός φακός όπως 50mm f/1.8 ή 85mm f/1.4 είναι ιδανικός." }, { q: "Πώς βγάζω καλές φωτογραφίες τοπίου;", a: "Χρησιμοποιήστε μικρό διάφραγμα (f/8-f/16) και τρίποδο." }, { q: "Τι είναι η ισορροπία λευκού;", a: "Η ισορροπία λευκού ρυθμίζει τη θερμοκρασία χρώματος." }, { q: "Πώς δημιουργώ καλύτερες συνθέσεις;", a: "Εφαρμόστε τον κανόνα των τρίτων, συμμετρία και οδηγούμενες γραμμές." }] },
  da: { badge: "FAQ", title: "Ofte stillede spørgsmål", desc: "Almindelige spørgsmål fra fotografer", questions: [{ q: "Hvordan fotograferer jeg i svagt lys uden flash?", a: "Brug stor blænde (f/1.8-f/2.8), langsommere lukkertid og øg ISO forsigtigt. Stabiliser kameraet med stativ." }, { q: "Hvad er det bedste objektiv til portrætter?", a: "Et fastbrændvidde-objektiv som 50mm f/1.8 eller 85mm f/1.4 er ideelt." }, { q: "Hvordan tager jeg gode landskabsfotos?", a: "Brug lille blænde (f/8-f/16), fokuser en tredjedel ind i scenen og brug stativ." }, { q: "Hvad er hvidbalance?", a: "Hvidbalance justerer farvetemperaturen for neutrale hvide toner." }, { q: "Hvordan skaber jeg bedre kompositioner?", a: "Anvend tredjedelsreglen, symmetri og ledende linjer." }] },
  no: { badge: "FAQ", title: "Vanlige spørsmål", desc: "Vanlige spørsmål fra fotografer", questions: [{ q: "Hvordan fotograferer jeg i svakt lys uten blits?", a: "Bruk stor blenderåpning (f/1.8-f/2.8), tregere lukkertid og øk ISO forsiktig. Stabiliser kameraet med stativ." }, { q: "Hva er det beste objektivet for portretter?", a: "Et fastbrennvidde-objektiv som 50mm f/1.8 eller 85mm f/1.4 er ideelt." }, { q: "Hvordan tar jeg gode landskapsbilder?", a: "Bruk liten blenderåpning (f/8-f/16), fokuser en tredjedel inn i scenen og bruk stativ." }, { q: "Hva er hvitbalanse?", a: "Hvitbalanse justerer fargetemperaturen for nøytrale hvite toner." }, { q: "Hvordan skaper jeg bedre komposisjoner?", a: "Bruk tredjedelsregelen, symmetri og ledende linjer." }] },
  ro: { badge: "FAQ", title: "Întrebări frecvente", desc: "Întrebări comune de la fotografi", questions: [{ q: "Cum fotografiez în lumină slabă fără bliț?", a: "Folosiți o diafragmă largă (f/1.8-f/2.8), viteză mai lentă și creșteți ISO cu atenție. Folosiți trepied." }, { q: "Care este cel mai bun obiectiv pentru portrete?", a: "Un obiectiv fix precum 50mm f/1.8 sau 85mm f/1.4 este ideal." }, { q: "Cum fac fotografii bune de peisaj?", a: "Folosiți diafragmă mică (f/8-f/16) și trepied." }, { q: "Ce este balansul de alb?", a: "Balansul de alb ajustează temperatura de culoare." }, { q: "Cum creez compoziții mai bune?", a: "Aplicați regula treimilor, simetrie și linii directoare." }] },
  bg: { badge: "FAQ", title: "Често задавани въпроси", desc: "Общи въпроси от фотографи", questions: [{ q: "Как да снимам при слаба светлина без светкавица?", a: "Използвайте широк отвор (f/1.8-f/2.8), по-бавна скорост и увеличете ISO внимателно. Използвайте статив." }, { q: "Кой е най-добрият обектив за портрети?", a: "Фиксиран обектив като 50mm f/1.8 или 85mm f/1.4 е идеален." }, { q: "Как правя добри пейзажни снимки?", a: "Използвайте малък отвор (f/8-f/16) и статив." }, { q: "Какво е баланс на бялото?", a: "Балансът на бялото регулира цветовата температура." }, { q: "Как да създам по-добри композиции?", a: "Прилагайте правилото на третините, симетрия и водещи линии." }] },
  fi: { badge: "FAQ", title: "Usein kysytyt kysymykset", desc: "Valokuvaajien yleisiä kysymyksiä", questions: [{ q: "Miten kuvaan heikossa valossa ilman salamaa?", a: "Käytä suurta aukkoa (f/1.8-f/2.8), hitaampaa suljinaikaa ja nosta ISO varovasti. Käytä jalustaa." }, { q: "Mikä on paras objektiivi muotokuville?", a: "Kiinteäpolttoväli kuten 50mm f/1.8 tai 85mm f/1.4 on ihanteellinen." }, { q: "Miten otan hyviä maisemakuvia?", a: "Käytä pientä aukkoa (f/8-f/16) ja jalustaa." }, { q: "Mikä on valkotasapaino?", a: "Valkotasapaino säätää värilämpötilaa neutraalien valkeiden varmistamiseksi." }, { q: "Miten luon parempia sommitelmia?", a: "Sovella kolmasosasääntöä, symmetriaa ja johtavia linjoja." }] },
  ru: { badge: "FAQ", title: "Часто задаваемые вопросы", desc: "Общие вопросы фотографов", questions: [{ q: "Как снимать при слабом освещении без вспышки?", a: "Используйте широкую диафрагму (f/1.8-f/2.8), медленную выдержку и аккуратно увеличьте ISO. Используйте штатив." }, { q: "Какой лучший объектив для портретов?", a: "Фикс-объектив 50mm f/1.8 или 85mm f/1.4 идеален." }, { q: "Как снимать хорошие пейзажи?", a: "Используйте малую диафрагму (f/8-f/16) и штатив." }, { q: "Что такое баланс белого?", a: "Баланс белого регулирует цветовую температуру." }, { q: "Как создавать лучшие композиции?", a: "Применяйте правило третей, симметрию и направляющие линии." }] },
  zh: { badge: "常见问题", title: "常见问题解答", desc: "摄影师的常见问题", questions: [{ q: "如何在弱光下不使用闪光灯拍摄？", a: "使用大光圈 (f/1.8-f/2.8)，较慢的快门速度，并谨慎提高ISO。使用三脚架稳定相机。" }, { q: "拍人像最好的镜头是什么？", a: "50mm f/1.8 或 85mm f/1.4 的定焦镜头是理想选择。" }, { q: "如何拍出好的风景照？", a: "使用小光圈 (f/8-f/16) 和三脚架。" }, { q: "什么是白平衡？", a: "白平衡调节色温以确保白色在不同光线下看起来中性。" }, { q: "如何创造更好的构图？", a: "运用三分法则、对称和引导线。" }] },
  hi: { badge: "FAQ", title: "अक्सर पूछे जाने वाले प्रश्न", desc: "फ़ोटोग्राफ़रों के सामान्य प्रश्न", questions: [{ q: "कम रोशनी में बिना फ्लैश के कैसे शूट करें?", a: "चौड़े एपर्चर (f/1.8-f/2.8), धीमी शटर स्पीड का उपयोग करें और सावधानी से ISO बढ़ाएं। ट्राइपॉड का उपयोग करें।" }, { q: "पोर्ट्रेट के लिए सबसे अच्छा लेंस कौन सा है?", a: "50mm f/1.8 या 85mm f/1.4 जैसा प्राइम लेंस आदर्श है।" }, { q: "अच्छी लैंडस्केप फ़ोटो कैसे लें?", a: "छोटे एपर्चर (f/8-f/16) और ट्राइपॉड का उपयोग करें।" }, { q: "व्हाइट बैलेंस क्या है?", a: "व्हाइट बैलेंस रंग तापमान को समायोजित करता है।" }, { q: "बेहतर कंपोज़िशन कैसे बनाएं?", a: "तिहाई नियम, सममिति और अग्रणी रेखाओं का उपयोग करें।" }] },
  ja: { badge: "FAQ", title: "よくある質問", desc: "写真家からの一般的な質問", questions: [{ q: "フラッシュなしで暗い場所で撮影するには？", a: "広い絞り (f/1.8-f/2.8)、遅いシャッタースピードを使い、ISOを慎重に上げます。三脚を使用してください。" }, { q: "ポートレートに最適なレンズは？", a: "50mm f/1.8や85mm f/1.4のような単焦点レンズが理想的です。" }, { q: "風景写真をうまく撮るには？", a: "小さな絞り (f/8-f/16) と三脚を使用してください。" }, { q: "ホワイトバランスとは？", a: "ホワイトバランスは色温度を調整して白が自然に見えるようにします。" }, { q: "より良い構図を作るには？", a: "三分割法、対称性、リーディングラインを活用してください。" }] },
  ar: { badge: "الأسئلة الشائعة", title: "أسئلة متكررة", desc: "أسئلة شائعة من المصورين", questions: [{ q: "كيف أصور في الإضاءة المنخفضة بدون فلاش؟", a: "استخدم فتحة عدسة واسعة (f/1.8-f/2.8)، سرعة غالق أبطأ وزد ISO بحذر. استخدم حامل ثلاثي." }, { q: "ما هي أفضل عدسة للبورتريه؟", a: "عدسة ثابتة مثل 50mm f/1.8 أو 85mm f/1.4 مثالية." }, { q: "كيف ألتقط صور مناظر طبيعية جيدة؟", a: "استخدم فتحة صغيرة (f/8-f/16) وحامل ثلاثي." }, { q: "ما هو توازن الأبيض؟", a: "توازن الأبيض يضبط درجة حرارة اللون." }, { q: "كيف أنشئ تكوينات أفضل؟", a: "طبق قاعدة الأثلاث والتماثل والخطوط الموجهة." }] },
  ko: { badge: "FAQ", title: "자주 묻는 질문", desc: "사진작가의 일반적인 질문", questions: [{ q: "플래시 없이 저조도에서 촬영하려면?", a: "넓은 조리개 (f/1.8-f/2.8), 느린 셔터 속도를 사용하고 ISO를 신중하게 올리세요. 삼각대를 사용하세요." }, { q: "인물 사진에 가장 좋은 렌즈는?", a: "50mm f/1.8이나 85mm f/1.4 같은 단초점 렌즈가 이상적입니다." }, { q: "좋은 풍경 사진을 찍으려면?", a: "작은 조리개 (f/8-f/16)와 삼각대를 사용하세요." }, { q: "화이트 밸런스란?", a: "화이트 밸런스는 색온도를 조정하여 흰색이 자연스럽게 보이게 합니다." }, { q: "더 나은 구도를 만들려면?", a: "삼분법, 대칭, 리딩라인을 활용하세요." }] },
  cs: { badge: "FAQ", title: "Často kladené otázky", desc: "Běžné otázky fotografů", questions: [{ q: "Jak fotografovat při slabém osvětlení bez blesku?", a: "Použijte širokou clonu (f/1.8-f/2.8), pomalejší závěrku a opatrně zvyšte ISO. Použijte stativ." }, { q: "Jaký je nejlepší objektiv na portréty?", a: "Pevný objektiv jako 50mm f/1.8 nebo 85mm f/1.4 je ideální." }, { q: "Jak fotit dobré krajiny?", a: "Použijte malou clonu (f/8-f/16) a stativ." }, { q: "Co je vyvážení bílé?", a: "Vyvážení bílé upravuje teplotu barev." }, { q: "Jak vytvořit lepší kompozice?", a: "Aplikujte pravidlo třetin, symetrii a vodící linie." }] },
  hu: { badge: "GYIK", title: "Gyakran ismételt kérdések", desc: "Fotósok gyakori kérdései", questions: [{ q: "Hogyan fotózzak gyenge fényben vaku nélkül?", a: "Használjon nagy rekesznyílást (f/1.8-f/2.8), lassabb záridőt és óvatosan növelje az ISO-t. Használjon állványt." }, { q: "Mi a legjobb objektív portréfotózáshoz?", a: "Fix objektív, mint az 50mm f/1.8 vagy 85mm f/1.4 ideális." }, { q: "Hogyan készítsek jó tájképeket?", a: "Használjon kis rekesznyílást (f/8-f/16) és állványt." }, { q: "Mi a fehéregyensúly?", a: "A fehéregyensúly a színhőmérsékletet állítja be." }, { q: "Hogyan hozzak létre jobb kompozíciókat?", a: "Alkalmazza a harmadolás szabályát, szimmetriát és vezető vonalakat." }] },
  uk: { badge: "FAQ", title: "Поширені запитання", desc: "Загальні питання фотографів", questions: [{ q: "Як фотографувати при слабкому освітленні без спалаху?", a: "Використовуйте широку діафрагму (f/1.8-f/2.8), повільнішу витримку та обережно збільшуйте ISO. Використовуйте штатив." }, { q: "Який найкращий об'єктив для портретів?", a: "Фікс-об'єктив 50mm f/1.8 або 85mm f/1.4 ідеальний." }, { q: "Як робити гарні пейзажні фото?", a: "Використовуйте малу діафрагму (f/8-f/16) і штатив." }, { q: "Що таке баланс білого?", a: "Баланс білого налаштовує колірну температуру." }, { q: "Як створювати кращі композиції?", a: "Застосовуйте правило третин, симетрію та напрямні лінії." }] },
  sk: { badge: "FAQ", title: "Často kladené otázky", desc: "Bežné otázky fotografov", questions: [{ q: "Ako fotografovať pri slabom osvetlení bez blesku?", a: "Použite širokú clonu (f/1.8-f/2.8), pomalšiu závierku a opatrne zvýšte ISO. Použite statív." }, { q: "Aký je najlepší objektív na portréty?", a: "Pevný objektív ako 50mm f/1.8 alebo 85mm f/1.4 je ideálny." }, { q: "Ako fotiť dobré krajiny?", a: "Použite malú clonu (f/8-f/16) a statív." }, { q: "Čo je vyváženie bielej?", a: "Vyváženie bielej upravuje teplotu farieb." }, { q: "Ako vytvoriť lepšie kompozície?", a: "Aplikujte pravidlo tretín, symetriu a vodiacie línie." }] },
  hr: { badge: "FAQ", title: "Često postavljana pitanja", desc: "Uobičajena pitanja fotografa", questions: [{ q: "Kako fotografirati pri slabom osvjetljenju bez bljeskalice?", a: "Koristite široki otvor (f/1.8-f/2.8), sporiji zatvarač i pažljivo povećajte ISO. Koristite stativ." }, { q: "Koji je najbolji objektiv za portrete?", a: "Fiksni objektiv poput 50mm f/1.8 ili 85mm f/1.4 je idealan." }, { q: "Kako snimati dobre pejzaže?", a: "Koristite mali otvor (f/8-f/16) i stativ." }, { q: "Što je balans bijele?", a: "Balans bijele prilagođava temperaturu boje." }, { q: "Kako stvoriti bolje kompozicije?", a: "Primijenite pravilo trećina, simetriju i vodeće linije." }] },
  sr: { badge: "FAQ", title: "Често постављана питања", desc: "Уобичајена питања фотографа", questions: [{ q: "Како фотографисати при слабом осветљењу без блица?", a: "Користите широк отвор (f/1.8-f/2.8), спорији затварач и пажљиво повећајте ISO. Користите статив." }, { q: "Који је најбољи објектив за портрете?", a: "Фиксни објектив попут 50mm f/1.8 или 85mm f/1.4 је идеалан." }, { q: "Како снимати добре пејзаже?", a: "Користите мали отвор (f/8-f/16) и статив." }, { q: "Шта је баланс беле?", a: "Баланс беле прилагођава температуру боје." }, { q: "Како створити боље композиције?", a: "Примените правило трећина, симетрију и водеће линије." }] },
  sl: { badge: "FAQ", title: "Pogosta vprašanja", desc: "Pogosta vprašanja fotografov", questions: [{ q: "Kako fotografirati pri šibki svetlobi brez bliskavice?", a: "Uporabite široko zaslonko (f/1.8-f/2.8), počasnejšo hitrost zaklopa in previdno povečajte ISO. Uporabite stojalo." }, { q: "Kateri je najboljši objektiv za portrete?", a: "Fiksni objektiv, kot je 50mm f/1.8 ali 85mm f/1.4, je idealen." }, { q: "Kako posneti dobre pokrajinske fotografije?", a: "Uporabite majhno zaslonko (f/8-f/16) in stojalo." }, { q: "Kaj je ravnovesje beline?", a: "Ravnovesje beline prilagaja barvno temperaturo." }, { q: "Kako ustvariti boljše kompozicije?", a: "Uporabite pravilo tretjin, simetrijo in vodilne črte." }] },
  tr: { badge: "SSS", title: "Sık Sorulan Sorular", desc: "Fotoğrafçıların yaygın soruları", questions: [{ q: "Flaş olmadan düşük ışıkta nasıl çekim yapılır?", a: "Geniş diyafram (f/1.8-f/2.8), yavaş deklanşör hızı kullanın ve ISO'yu dikkatli artırın. Tripod kullanın." }, { q: "Portre için en iyi lens hangisi?", a: "50mm f/1.8 veya 85mm f/1.4 gibi sabit bir lens idealdir." }, { q: "İyi manzara fotoğrafları nasıl çekilir?", a: "Küçük diyafram (f/8-f/16) ve tripod kullanın." }, { q: "Beyaz dengesi nedir?", a: "Beyaz dengesi, beyazların doğal görünmesi için renk sıcaklığını ayarlar." }, { q: "Daha iyi kompozisyonlar nasıl oluşturulur?", a: "Üçler kuralını, simetriyi ve yönlendirici çizgileri uygulayın." }] },
};

interface Props { lang: string; }

const FAQPhotographyMulti = ({ lang }: Props) => {
  const t = translations[lang];
  return (
    <section className="py-20 bg-secondary/30">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto">
          <Badge className="mb-4">{t.badge}</Badge>
          <h1 className="text-4xl font-bold mb-4">{t.title}</h1>
          <p className="text-xl text-muted-foreground mb-12">{t.desc}</p>
          <Accordion type="single" collapsible className="space-y-4">
            {t.questions.map((item, index) => (
              <AccordionItem key={index} value={`faq-${index}`} className="border rounded-lg px-6 py-2">
                <AccordionTrigger className="hover:no-underline">
                  <h2 className="text-lg font-semibold text-left">{item.q}</h2>
                </AccordionTrigger>
                <AccordionContent className="pt-4">
                  <p className="text-muted-foreground">{item.a}</p>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default FAQPhotographyMulti;
