import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const translations: Record<string, { badge: string; title: string; desc: string; questions: { q: string; a: string }[] }> = {
  sv: { badge: "Q&A", title: "Vanliga frågor om juridiska dokument för fotografer", desc: "Vanliga frågor från fotografer om juridiskt skydd och dokumentation", questions: [{ q: "Varför behöver jag juridiska dokument som fotograf?", a: "Som professionell fotograf behöver du juridiskt skydd av flera skäl: för att skydda din upphovsrätt, definiera tydliga villkor med kunder, följa GDPR vid insamling av kunddata, fastställa betalnings- och avbokningspolicyer och skydda dig mot ansvarsanspråk." }, { q: "Vad ingår i uppdragsavtalet?", a: "Uppdragsavtalet innehåller en komplett kontraktsmall som du kan anpassa för varje kund. Det täcker tjänsteavgifter, betalningsvillkor, uppdragsdetaljer, leveranstider, upphovsrättsägande och avbokningspolicyer." }, { q: "Kan jag använda dessa dokument för flera specialiteter?", a: "Ja! Oavsett om du är porträtt-, bröllops-, kommersiell eller eventfotograf är dessa dokument flexibla och anpassningsbara för alla typer av fotografiverksamhet." }, { q: "Är upphovsrättsskyddet internationellt giltigt?", a: "Ja, upphovsrättsskyddet är utformat med internationell täckning i åtanke, med hänvisning till Bernkonventionen och andra internationella upphovsrättsfördrag." }, { q: "Behöver jag en integritetspolicy om jag bara har ett kontaktformulär?", a: "Ja! Enligt GDPR och andra integritetslagar, om du samlar in personuppgifter via din webbplats (även bara namn och e-post via ett kontaktformulär), är du juridiskt skyldig att ha en integritetspolicy." }] },
  pl: { badge: "Q&A", title: "Często zadawane pytania dotyczące dokumentów prawnych dla fotografów", desc: "Najczęstsze pytania fotografów dotyczące ochrony prawnej", questions: [{ q: "Dlaczego potrzebuję dokumentów prawnych jako fotograf?", a: "Jako profesjonalny fotograf potrzebujesz ochrony prawnej z wielu powodów: ochrona praw autorskich, jasne warunki z klientami, zgodność z RODO, zasady płatności i anulowania oraz ochrona przed roszczeniami." }, { q: "Co zawiera umowa zlecenia?", a: "Umowa zlecenia zawiera kompletny szablon kontraktu, który możesz dostosować. Obejmuje opłaty, warunki płatności, szczegóły zlecenia, terminy dostaw, własność praw autorskich i zasady anulowania." }, { q: "Czy mogę używać tych dokumentów dla wielu specjalizacji?", a: "Tak! Niezależnie od tego, czy jesteś fotografem portretowym, ślubnym, komercyjnym czy eventowym, te dokumenty są elastyczne i dostosowywalne." }, { q: "Czy ochrona praw autorskich jest ważna międzynarodowo?", a: "Tak, ochrona praw autorskich jest zaprojektowana z myślą o międzynarodowym zasięgu, odwołując się do Konwencji Berneńskiej." }, { q: "Czy potrzebuję polityki prywatności, jeśli mam tylko formularz kontaktowy?", a: "Tak! Zgodnie z RODO, jeśli zbierasz jakiekolwiek dane osobowe przez swoją stronę, musisz mieć politykę prywatności." }] },
  el: { badge: "Q&A", title: "Συχνές ερωτήσεις για νομικά έγγραφα φωτογραφίας", desc: "Κοινές ερωτήσεις από φωτογράφους σχετικά με τη νομική προστασία", questions: [{ q: "Γιατί χρειάζομαι νομικά έγγραφα ως φωτογράφος;", a: "Ως επαγγελματίας φωτογράφος χρειάζεστε νομική προστασία για πολλούς λόγους: προστασία πνευματικών δικαιωμάτων, σαφείς όροι με πελάτες, συμμόρφωση GDPR και προστασία από αξιώσεις." }, { q: "Τι περιλαμβάνει η σύμβαση ανάθεσης;", a: "Η σύμβαση ανάθεσης περιλαμβάνει ένα πλήρες πρότυπο σύμβασης που μπορείτε να προσαρμόσετε για κάθε πελάτη." }, { q: "Μπορώ να χρησιμοποιήσω αυτά τα έγγραφα για πολλές ειδικότητες;", a: "Ναι! Αυτά τα έγγραφα είναι ευέλικτα και προσαρμόσιμα για κάθε τύπο φωτογραφικής επιχείρησης." }, { q: "Είναι η προστασία πνευματικών δικαιωμάτων διεθνώς ισχυρή;", a: "Ναι, αναφέρεται στη Σύμβαση της Βέρνης και σε άλλες διεθνείς συνθήκες." }, { q: "Χρειάζομαι πολιτική απορρήτου αν έχω μόνο φόρμα επικοινωνίας;", a: "Ναι! Σύμφωνα με το GDPR, αν συλλέγετε οποιαδήποτε προσωπικά δεδομένα, πρέπει να έχετε πολιτική απορρήτου." }] },
  da: { badge: "Q&A", title: "Ofte stillede spørgsmål om juridiske dokumenter til fotografer", desc: "Almindelige spørgsmål fra fotografer om juridisk beskyttelse", questions: [{ q: "Hvorfor har jeg brug for juridiske dokumenter som fotograf?", a: "Som professionel fotograf har du brug for juridisk beskyttelse af flere grunde: ophavsretsbeskyttelse, klare vilkår med kunder, GDPR-overholdelse og beskyttelse mod ansvarskrav." }, { q: "Hvad indeholder opgaveaftalen?", a: "Opgaveaftalen indeholder en komplet kontraktskabelon, der kan tilpasses til hver klient med gebyrer, leveringstider og ophavsret." }, { q: "Kan jeg bruge disse dokumenter til flere specialer?", a: "Ja! Dokumenterne er fleksible og tilpasselige til enhver type fotografivirksomhed." }, { q: "Er ophavsretsbeskyttelsen international?", a: "Ja, den er designet med international dækning baseret på Berne-konventionen." }, { q: "Har jeg brug for en privatlivspolitik med kun en kontaktformular?", a: "Ja! Under GDPR skal du have en privatlivspolitik, hvis du indsamler persondata." }] },
  no: { badge: "Q&A", title: "Vanlige spørsmål om juridiske dokumenter for fotografer", desc: "Vanlige spørsmål fra fotografer om juridisk beskyttelse", questions: [{ q: "Hvorfor trenger jeg juridiske dokumenter som fotograf?", a: "Som profesjonell fotograf trenger du juridisk beskyttelse for å beskytte opphavsretten din, definere vilkår med kunder, overholde GDPR og beskytte deg mot ansvarskrav." }, { q: "Hva inkluderer oppdragsavtalen?", a: "Oppdragsavtalen inkluderer en komplett kontraktsmal som kan tilpasses for hver klient med honorarer, leveringstider og opphavsrett." }, { q: "Kan jeg bruke disse dokumentene for flere spesialiteter?", a: "Ja! Dokumentene er fleksible og tilpassbare for alle typer fotografivirksomhet." }, { q: "Er opphavsrettsbeskyttelsen internasjonalt gyldig?", a: "Ja, den er utformet med internasjonal dekning basert på Bern-konvensjonen." }, { q: "Trenger jeg en personvernpolicy med bare et kontaktskjema?", a: "Ja! Under GDPR må du ha en personvernpolicy hvis du samler inn persondata." }] },
  ro: { badge: "Q&A", title: "Întrebări frecvente despre documentele juridice pentru fotografi", desc: "Întrebări comune ale fotografilor despre protecția juridică", questions: [{ q: "De ce am nevoie de documente juridice ca fotograf?", a: "Ca fotograf profesionist aveți nevoie de protecție juridică: drepturi de autor, termeni clari cu clienții, conformitate GDPR și protecție împotriva revendicărilor." }, { q: "Ce include contractul de atribuire?", a: "Contractul include un șablon complet personalizabil cu tarife, termene și drepturi de autor." }, { q: "Pot folosi aceste documente pentru mai multe specialități?", a: "Da! Documentele sunt flexibile și adaptabile pentru orice tip de afacere fotografică." }, { q: "Este protecția drepturilor de autor valabilă internațional?", a: "Da, bazată pe Convenția de la Berna și alte tratate internaționale." }, { q: "Am nevoie de o politică de confidențialitate doar cu un formular de contact?", a: "Da! Conform GDPR, dacă colectați date personale, aveți nevoie de o politică de confidențialitate." }] },
  bg: { badge: "Q&A", title: "Често задавани въпроси за правни документи за фотографи", desc: "Общи въпроси от фотографи за правна защита", questions: [{ q: "Защо ми трябват правни документи като фотограф?", a: "Като професионален фотограф се нуждаете от правна защита: авторски права, ясни условия с клиенти, GDPR съответствие и защита от претенции." }, { q: "Какво включва договорът за възлагане?", a: "Договорът включва пълен персонализируем шаблон с такси, срокове и авторски права." }, { q: "Мога ли да използвам тези документи за различни специалности?", a: "Да! Документите са гъвкави и адаптивни за всеки тип фотографски бизнес." }, { q: "Защитата на авторските права валидна ли е международно?", a: "Да, базирана е на Бернската конвенция и международни договори." }, { q: "Трябва ли ми политика за поверителност само с контактна форма?", a: "Да! Според GDPR, ако събирате лични данни, трябва да имате политика за поверителност." }] },
  fi: { badge: "Q&A", title: "Usein kysytyt kysymykset valokuvaajien oikeudellisista asiakirjoista", desc: "Valokuvaajien yleisiä kysymyksiä oikeudellisesta suojasta", questions: [{ q: "Miksi tarvitsen oikeudellisia asiakirjoja valokuvaajana?", a: "Ammattivalokuvaajana tarvitset oikeudellista suojaa: tekijänoikeudet, selkeät ehdot asiakkaiden kanssa, GDPR-vaatimustenmukaisuus ja suoja vaatimuksilta." }, { q: "Mitä toimeksiantosopimus sisältää?", a: "Toimeksiantosopimus sisältää mukautettavan mallin maksuilla, aikatauluilla ja tekijänoikeuksilla." }, { q: "Voinko käyttää näitä asiakirjoja useille erikoistumisaloille?", a: "Kyllä! Asiakirjat ovat joustavia ja muokattavissa kaikkiin valokuvaustyyppeihin." }, { q: "Onko tekijänoikeussuoja kansainvälisesti pätevä?", a: "Kyllä, se perustuu Bernin yleissopimukseen ja muihin kansainvälisiin sopimuksiin." }, { q: "Tarvitsenko tietosuojakäytäntöä pelkällä yhteydenottolomakkeella?", a: "Kyllä! GDPR:n mukaan sinun on oltava tietosuojakäytäntö, jos keräät henkilötietoja." }] },
  ru: { badge: "Q&A", title: "Часто задаваемые вопросы о юридических документах для фотографов", desc: "Общие вопросы фотографов о юридической защите", questions: [{ q: "Зачем мне юридические документы как фотографу?", a: "Как профессиональный фотограф вам нужна юридическая защита: авторские права, чёткие условия с клиентами, соответствие GDPR и защита от претензий." }, { q: "Что включает договор на работу?", a: "Договор включает полный настраиваемый шаблон с гонорарами, сроками и авторскими правами." }, { q: "Могу ли я использовать эти документы для разных специализаций?", a: "Да! Документы гибкие и настраиваемые для любого типа фотобизнеса." }, { q: "Действительна ли защита авторских прав международно?", a: "Да, она основана на Бернской конвенции и международных договорах." }, { q: "Нужна ли мне политика конфиденциальности только с контактной формой?", a: "Да! По GDPR, если вы собираете персональные данные, вам нужна политика конфиденциальности." }] },
  zh: { badge: "问答", title: "摄影师法律文件常见问题", desc: "摄影师关于法律保护的常见问题", questions: [{ q: "作为摄影师为什么需要法律文件？", a: "作为专业摄影师，您需要法律保护：版权保护、与客户的明确条款、GDPR合规以及免于索赔的保护。" }, { q: "委托协议包含什么？", a: "委托协议包含一个完整的可定制合同模板，包括费用、时间表和版权。" }, { q: "这些文件可以用于多种专业吗？", a: "是的！这些文件灵活且可适用于任何类型的摄影业务。" }, { q: "版权保护在国际上有效吗？", a: "是的，基于伯尔尼公约和其他国际条约。" }, { q: "如果只有联系表单需要隐私政策吗？", a: "是的！根据GDPR，如果您收集任何个人数据，就需要隐私政策。" }] },
  hi: { badge: "प्रश्नोत्तर", title: "फ़ोटोग्राफ़रों के लिए कानूनी दस्तावेज़ सामान्य प्रश्न", desc: "फ़ोटोग्राफ़रों के कानूनी सुरक्षा के बारे में सामान्य प्रश्न", questions: [{ q: "एक फ़ोटोग्राफ़र के रूप में मुझे कानूनी दस्तावेज़ क्यों चाहिए?", a: "एक पेशेवर फ़ोटोग्राफ़र के रूप में आपको कानूनी सुरक्षा की आवश्यकता है: कॉपीराइट, ग्राहकों के साथ स्पष्ट शर्तें, GDPR अनुपालन और दावों से सुरक्षा।" }, { q: "असाइनमेंट अनुबंध में क्या शामिल है?", a: "अनुबंध में शुल्क, समय सीमा और कॉपीराइट के साथ एक पूर्ण अनुकूलन योग्य टेम्पलेट शामिल है।" }, { q: "क्या मैं इन दस्तावेज़ों का उपयोग कई विशेषज्ञताओं के लिए कर सकता हूँ?", a: "हाँ! ये दस्तावेज़ लचीले और किसी भी प्रकार के फ़ोटोग्राफ़ी व्यवसाय के लिए अनुकूलन योग्य हैं।" }, { q: "क्या कॉपीराइट सुरक्षा अंतरराष्ट्रीय स्तर पर मान्य है?", a: "हाँ, यह बर्न कन्वेंशन और अन्य अंतरराष्ट्रीय संधियों पर आधारित है।" }, { q: "क्या मुझे केवल संपर्क फ़ॉर्म के साथ गोपनीयता नीति की आवश्यकता है?", a: "हाँ! GDPR के अनुसार, यदि आप कोई भी व्यक्तिगत डेटा एकत्र करते हैं, तो आपको गोपनीयता नीति की आवश्यकता है।" }] },
  ja: { badge: "Q&A", title: "写真家の法的文書に関するよくある質問", desc: "法的保護に関する写真家からの一般的な質問", questions: [{ q: "写真家として法的文書が必要な理由は？", a: "プロの写真家として、著作権保護、クライアントとの明確な条件、GDPR準拠、責任からの保護のために法的保護が必要です。" }, { q: "業務委託契約には何が含まれますか？", a: "契約には、料金、スケジュール、著作権を含む完全にカスタマイズ可能なテンプレートが含まれています。" }, { q: "複数の専門分野でこれらの文書を使用できますか？", a: "はい！これらの文書は柔軟で、あらゆる種類の写真ビジネスに適応可能です。" }, { q: "著作権保護は国際的に有効ですか？", a: "はい、ベルヌ条約やその他の国際条約に基づいています。" }, { q: "お問い合わせフォームだけでもプライバシーポリシーが必要ですか？", a: "はい！GDPRの下では、個人データを収集する場合、プライバシーポリシーが必要です。" }] },
  ar: { badge: "أسئلة وأجوبة", title: "الأسئلة الشائعة حول الوثائق القانونية للمصورين", desc: "أسئلة شائعة من المصورين حول الحماية القانونية", questions: [{ q: "لماذا أحتاج وثائق قانونية كمصور؟", a: "كمصور محترف تحتاج حماية قانونية: حقوق النشر، شروط واضحة مع العملاء، امتثال GDPR وحماية من المطالبات." }, { q: "ماذا تتضمن اتفاقية التكليف؟", a: "تتضمن الاتفاقية قالب عقد كامل قابل للتخصيص مع الرسوم والجداول الزمنية وحقوق النشر." }, { q: "هل يمكنني استخدام هذه الوثائق لتخصصات متعددة؟", a: "نعم! هذه الوثائق مرنة وقابلة للتكيف مع أي نوع من أعمال التصوير." }, { q: "هل حماية حقوق النشر صالحة دولياً؟", a: "نعم، تستند إلى اتفاقية برن والمعاهدات الدولية الأخرى." }, { q: "هل أحتاج سياسة خصوصية مع نموذج اتصال فقط؟", a: "نعم! وفقاً لـ GDPR، إذا جمعت أي بيانات شخصية، تحتاج سياسة خصوصية." }] },
  ko: { badge: "Q&A", title: "사진작가 법적 문서 자주 묻는 질문", desc: "법적 보호에 관한 사진작가들의 일반적인 질문", questions: [{ q: "사진작가로서 왜 법적 문서가 필요한가요?", a: "전문 사진작가로서 저작권 보호, 고객과의 명확한 조건, GDPR 준수, 책임으로부터의 보호를 위해 법적 보호가 필요합니다." }, { q: "위탁 계약에는 무엇이 포함되나요?", a: "계약에는 수수료, 일정 및 저작권이 포함된 완전히 맞춤화 가능한 템플릿이 포함됩니다." }, { q: "여러 전문 분야에서 이 문서를 사용할 수 있나요?", a: "네! 이 문서들은 유연하고 모든 유형의 사진 비즈니스에 적응 가능합니다." }, { q: "저작권 보호가 국제적으로 유효한가요?", a: "네, 베른 협약 및 기타 국제 조약에 기반합니다." }, { q: "문의 양식만 있어도 개인정보 보호정책이 필요한가요?", a: "네! GDPR에 따라 개인 데이터를 수집하면 개인정보 보호정책이 필요합니다." }] },
  cs: { badge: "Q&A", title: "Často kladené otázky o právních dokumentech pro fotografy", desc: "Běžné otázky fotografů o právní ochraně", questions: [{ q: "Proč potřebuji právní dokumenty jako fotograf?", a: "Jako profesionální fotograf potřebujete právní ochranu: autorská práva, jasné podmínky s klienty, soulad s GDPR a ochranu před nároky." }, { q: "Co obsahuje smlouva o dílo?", a: "Smlouva obsahuje kompletní přizpůsobitelnou šablonu s poplatky, termíny a autorskými právy." }, { q: "Mohu tyto dokumenty použít pro více specializací?", a: "Ano! Dokumenty jsou flexibilní a přizpůsobitelné pro jakýkoli typ fotografického podnikání." }, { q: "Je ochrana autorských práv mezinárodně platná?", a: "Ano, je založena na Bernské úmluvě a dalších mezinárodních smlouvách." }, { q: "Potřebuji zásady ochrany osobních údajů jen s kontaktním formulářem?", a: "Ano! Podle GDPR, pokud shromažďujete osobní údaje, musíte mít zásady ochrany osobních údajů." }] },
  hu: { badge: "Q&A", title: "Gyakran ismételt kérdések a fotós jogi dokumentumokról", desc: "Fotósok gyakori kérdései a jogi védelemről", questions: [{ q: "Miért van szükségem jogi dokumentumokra fotósként?", a: "Professzionális fotósként jogi védelemre van szüksége: szerzői jogok, világos feltételek az ügyfelekkel, GDPR megfelelőség és védekezés igényekkel szemben." }, { q: "Mit tartalmaz a megbízási szerződés?", a: "A szerződés teljesen testreszabható sablont tartalmaz díjakkal, határidőkkel és szerzői jogokkal." }, { q: "Több szakterületre is használhatom ezeket a dokumentumokat?", a: "Igen! A dokumentumok rugalmasak és minden típusú fotóvállalkozáshoz adaptálhatóak." }, { q: "A szerzői jogi védelem nemzetközileg érvényes?", a: "Igen, a Berni Egyezményen és más nemzetközi szerződéseken alapul." }, { q: "Szükségem van adatvédelmi irányelvekre csak egy kapcsolatfelvételi űrlappal?", a: "Igen! A GDPR szerint, ha személyes adatokat gyűjt, szüksége van adatvédelmi irányelvekre." }] },
  uk: { badge: "Q&A", title: "Поширені запитання про юридичні документи для фотографів", desc: "Загальні питання фотографів про юридичний захист", questions: [{ q: "Навіщо мені юридичні документи як фотографу?", a: "Як професійний фотограф вам потрібен юридичний захист: авторські права, чіткі умови з клієнтами, відповідність GDPR та захист від претензій." }, { q: "Що включає договір на роботу?", a: "Договір включає повний налаштовуваний шаблон з гонорарами, термінами та авторськими правами." }, { q: "Чи можу я використовувати ці документи для кількох спеціалізацій?", a: "Так! Документи гнучкі та адаптовані для будь-якого типу фотобізнесу." }, { q: "Чи діє захист авторських прав міжнародно?", a: "Так, він базується на Бернській конвенції та міжнародних договорах." }, { q: "Чи потрібна мені політика конфіденційності тільки з контактною формою?", a: "Так! За GDPR, якщо ви збираєте персональні дані, вам потрібна політика конфіденційності." }] },
  sk: { badge: "Q&A", title: "Často kladené otázky o právnych dokumentoch pre fotografov", desc: "Bežné otázky fotografov o právnej ochrane", questions: [{ q: "Prečo potrebujem právne dokumenty ako fotograf?", a: "Ako profesionálny fotograf potrebujete právnu ochranu: autorské práva, jasné podmienky s klientmi, súlad s GDPR a ochranu pred nárokmi." }, { q: "Čo obsahuje zmluva o dielo?", a: "Zmluva obsahuje kompletne prispôsobiteľnú šablónu s poplatkami, termínmi a autorskými právami." }, { q: "Môžem tieto dokumenty použiť pre viac špecializácií?", a: "Áno! Dokumenty sú flexibilné a prispôsobiteľné pre akýkoľvek typ fotografického podnikania." }, { q: "Je ochrana autorských práv medzinárodne platná?", a: "Áno, je založená na Bernskom dohovore a medzinárodných zmluvách." }, { q: "Potrebujem zásady ochrany súkromia len s kontaktným formulárom?", a: "Áno! Podľa GDPR, ak zhromažďujete osobné údaje, musíte mať zásady ochrany súkromia." }] },
  hr: { badge: "Q&A", title: "Često postavljana pitanja o pravnim dokumentima za fotografe", desc: "Uobičajena pitanja fotografa o pravnoj zaštiti", questions: [{ q: "Zašto trebam pravne dokumente kao fotograf?", a: "Kao profesionalni fotograf trebate pravnu zaštitu: autorska prava, jasni uvjeti s klijentima, GDPR usklađenost i zaštita od zahtjeva." }, { q: "Što sadrži ugovor o zadatku?", a: "Ugovor sadrži potpuno prilagodljiv predložak s naknadama, rokovima i autorskim pravima." }, { q: "Mogu li koristiti ove dokumente za više specijalizacija?", a: "Da! Dokumenti su fleksibilni i prilagodljivi za svaki tip fotografskog poslovanja." }, { q: "Je li zaštita autorskih prava međunarodno valjana?", a: "Da, temelji se na Bernskoj konvenciji i međunarodnim ugovorima." }, { q: "Trebam li politiku privatnosti samo s kontaktnim obrascem?", a: "Da! Prema GDPR-u, ako prikupljate osobne podatke, morate imati politiku privatnosti." }] },
  sr: { badge: "Q&A", title: "Често постављана питања о правним документима за фотографе", desc: "Уобичајена питања фотографа о правној заштити", questions: [{ q: "Зашто ми требају правни документи као фотографу?", a: "Као професионални фотограф потребна вам је правна заштита: ауторска права, јасни услови са клијентима, GDPR усклађеност и заштита од захтева." }, { q: "Шта садржи уговор о делу?", a: "Уговор садржи потпуно прилагодљив шаблон са накнадама, роковима и ауторским правима." }, { q: "Могу ли користити ове документе за више специјализација?", a: "Да! Документи су флексибилни и прилагодљиви за сваки тип фотографског пословања." }, { q: "Да ли је заштита ауторских права међународно важећа?", a: "Да, заснива се на Бернској конвенцији и међународним уговорима." }, { q: "Да ли ми треба политика приватности само са контакт формуларом?", a: "Да! Према GDPR-у, ако прикупљате личне податке, морате имати политику приватности." }] },
  sl: { badge: "Q&A", title: "Pogosta vprašanja o pravnih dokumentih za fotografe", desc: "Pogosta vprašanja fotografov o pravni zaščiti", questions: [{ q: "Zakaj potrebujem pravne dokumente kot fotograf?", a: "Kot profesionalni fotograf potrebujete pravno zaščito: avtorske pravice, jasni pogoji s strankami, skladnost z GDPR in zaščita pred zahtevki." }, { q: "Kaj vsebuje pogodba o naročilu?", a: "Pogodba vsebuje popolnoma prilagodljivo predlogo s pristojbinami, roki in avtorskimi pravicami." }, { q: "Ali lahko te dokumente uporabim za več specializacij?", a: "Da! Dokumenti so prilagodljivi za vsak tip fotografske dejavnosti." }, { q: "Ali je zaščita avtorskih pravic mednarodno veljavna?", a: "Da, temelji na Bernski konvenciji in mednarodnih pogodbah." }, { q: "Ali potrebujem pravilnik o zasebnosti samo s kontaktnim obrazcem?", a: "Da! Po GDPR, če zbirate osebne podatke, potrebujete pravilnik o zasebnosti." }] },
  tr: { badge: "S&C", title: "Fotoğrafçılar için yasal belgeler hakkında sık sorulan sorular", desc: "Fotoğrafçıların yasal koruma hakkında sık soruları", questions: [{ q: "Fotoğrafçı olarak neden yasal belgelere ihtiyacım var?", a: "Profesyonel bir fotoğrafçı olarak yasal korumaya ihtiyacınız var: telif hakları, müşterilerle net koşullar, GDPR uyumu ve taleplerden koruma." }, { q: "Görev sözleşmesi neleri içerir?", a: "Sözleşme, ücretler, zaman çizelgeleri ve telif haklarını içeren tamamen özelleştirilebilir bir şablon içerir." }, { q: "Bu belgeleri birden fazla uzmanlık alanı için kullanabilir miyim?", a: "Evet! Bu belgeler esnek ve her türlü fotoğrafçılık işine uyarlanabilir." }, { q: "Telif hakkı koruması uluslararası olarak geçerli mi?", a: "Evet, Bern Sözleşmesi ve diğer uluslararası anlaşmalara dayanmaktadır." }, { q: "Sadece iletişim formum varsa gizlilik politikasına ihtiyacım var mı?", a: "Evet! GDPR'ye göre, kişisel veri topluyorsanız gizlilik politikasına ihtiyacınız var." }] },
};

interface Props { lang: string; }

const PhotographyQAMulti = ({ lang }: Props) => {
  const t = translations[lang];
  return (
    <section className="py-20 bg-background">
      <div className="container">
        <div className="text-center mb-12">
          <Badge variant="outline" className="mb-4">{t.badge}</Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">{t.title}</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">{t.desc}</p>
        </div>
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {t.questions.map((item, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left hover:no-underline">
                  <span className="text-base font-medium text-foreground">{item.q}</span>
                </AccordionTrigger>
                <AccordionContent>
                  <p className="text-muted-foreground leading-relaxed">{item.a}</p>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default PhotographyQAMulti;
