import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Check, AlertTriangle } from "lucide-react";
import stripeLogo from "@/assets/stripe-logo.svg";
import StripeBuyButton from "@/components/StripeBuyButton";

const translations: Record<string, { badge: string; title: string; desc: string; cardTitle: string; cardDesc: string; items: string[]; stripe: string; noReturn: string; noReturnDesc: string }> = {
  sv: { badge: "Prissättning", title: "Väsentliga juridiska dokument för fotografer", desc: "Komplett paket med alla juridiska dokument du behöver för din fotograferingsverksamhet. Ladda ner enkelt på ditt eget språk – eller på flera språk – och gör din webbplats redo för internationell användning.", cardTitle: "Komplett juridiskt paket för fotografer", cardDesc: "Alla väsentliga juridiska dokument för obegränsad användning på alla dina fotografiwebbplatser", items: ["Villkor för fotografer", "Uppdragsavtal (Offerte) med mallar", "Integritetspolicy (GDPR-kompatibel)", "Cookiepolicy (GDPR-kompatibel)", "Ansvarsfriskrivning för foto- och innehållsskydd", "Frisläppning för modellavtal", "Upphovsrättsskydd (Auteursrecht)", "Implementeringsguide"], stripe: "Säker betalning via Stripe • Automatiskt konverterad till din lokala valuta", noReturn: "Viktigt: Ingen retur", noReturnDesc: "Våra produkter kan inte returneras och vi erbjuder ingen pengarna-tillbaka-garanti. Detta är rimligt för digitala dokument som enkelt kan kopieras efter nedladdning." },
  pl: { badge: "Cennik", title: "Niezbędne dokumenty prawne dla fotografów", desc: "Kompletny pakiet ze wszystkimi dokumentami prawnymi potrzebnymi dla Twojej działalności fotograficznej.", cardTitle: "Kompletny pakiet prawny dla fotografów", cardDesc: "Wszystkie niezbędne dokumenty prawne do nieograniczonego użytku na wszystkich stronach", items: ["Regulamin dla fotografów", "Umowa zlecenia (Offerte) z szablonami", "Polityka prywatności (zgodna z RODO)", "Polityka cookies (zgodna z RODO)", "Zastrzeżenie dotyczące ochrony zdjęć i treści", "Zrzeczenie się roszczeń", "Ochrona praw autorskich (Auteursrecht)", "Przewodnik wdrożeniowy"], stripe: "Bezpieczna płatność przez Stripe • Automatycznie przeliczone na Twoją walutę", noReturn: "Ważne: Bez zwrotów", noReturnDesc: "Nasze produkty nie podlegają zwrotowi. To ma sens dla dokumentów cyfrowych." },
  el: { badge: "Τιμολόγηση", title: "Βασικά νομικά έγγραφα για φωτογράφους", desc: "Πλήρες πακέτο με όλα τα νομικά έγγραφα που χρειάζεστε.", cardTitle: "Πλήρες νομικό πακέτο φωτογραφίας", cardDesc: "Όλα τα βασικά νομικά έγγραφα για απεριόριστη χρήση", items: ["Όροι χρήσης για φωτογράφους", "Σύμβαση ανάθεσης με πρότυπα", "Πολιτική απορρήτου (GDPR)", "Πολιτική cookies (GDPR)", "Αποποίηση ευθύνης", "Παραίτηση για μοντέλα", "Προστασία πνευματικών δικαιωμάτων", "Οδηγός εφαρμογής"], stripe: "Ασφαλής πληρωμή μέσω Stripe • Αυτόματη μετατροπή", noReturn: "Σημαντικό: Χωρίς επιστροφές", noReturnDesc: "Τα προϊόντα μας δεν επιστρέφονται. Αυτό ισχύει για ψηφιακά έγγραφα." },
  da: { badge: "Prissætning", title: "Vigtige juridiske dokumenter til fotografer", desc: "Komplet pakke med alle juridiske dokumenter til din fotografivirksomhed.", cardTitle: "Komplet juridisk pakke til fotografer", cardDesc: "Alle vigtige juridiske dokumenter til ubegrænset brug", items: ["Vilkår for fotografer", "Opgaveaftale (Offerte) med skabeloner", "Privatlivspolitik (GDPR)", "Cookiepolitik (GDPR)", "Ansvarsfraskrivelse", "Fraskrivelse for modeller", "Ophavsretsbeskyttelse", "Implementeringsguide"], stripe: "Sikker betaling via Stripe • Automatisk konvertering", noReturn: "Vigtigt: Ingen retur", noReturnDesc: "Vores produkter kan ikke returneres. Dette giver mening for digitale dokumenter." },
  no: { badge: "Priser", title: "Viktige juridiske dokumenter for fotografer", desc: "Komplett pakke med alle juridiske dokumenter for din fotografivirksomhet.", cardTitle: "Komplett juridisk pakke for fotografer", cardDesc: "Alle viktige juridiske dokumenter for ubegrenset bruk", items: ["Vilkår for fotografer", "Oppdragsavtale (Offerte) med maler", "Personvernregler (GDPR)", "Informasjonskapselregler (GDPR)", "Ansvarsfraskrivelse", "Fraskrivelse for modeller", "Opphavsrettsbeskyttelse", "Implementeringsguide"], stripe: "Sikker betaling via Stripe • Automatisk konvertering", noReturn: "Viktig: Ingen retur", noReturnDesc: "Våre produkter kan ikke returneres. Dette gir mening for digitale dokumenter." },
  ro: { badge: "Prețuri", title: "Documente juridice esențiale pentru fotografi", desc: "Pachet complet cu toate documentele juridice pentru afacerea dvs. de fotografie.", cardTitle: "Pachet juridic complet pentru fotografi", cardDesc: "Toate documentele juridice esențiale pentru utilizare nelimitată", items: ["Termeni și condiții pentru fotografi", "Contract de atribuire cu șabloane", "Politica de confidențialitate (GDPR)", "Politica de cookies (GDPR)", "Declinare de responsabilitate", "Renunțare pentru modele", "Protecția drepturilor de autor", "Ghid de implementare"], stripe: "Plată sigură prin Stripe • Conversie automată", noReturn: "Important: Fără returnări", noReturnDesc: "Produsele noastre nu pot fi returnate. Acest lucru este logic pentru documente digitale." },
  bg: { badge: "Цени", title: "Основни правни документи за фотографи", desc: "Пълен пакет с всички правни документи за вашия фотографски бизнес.", cardTitle: "Пълен правен пакет за фотографи", cardDesc: "Всички основни правни документи за неограничено използване", items: ["Общи условия за фотографи", "Договор за възлагане с шаблони", "Политика за поверителност (GDPR)", "Политика за бисквитки (GDPR)", "Отказ от отговорност", "Отказ от претенции за модели", "Защита на авторски права", "Ръководство за внедряване"], stripe: "Сигурно плащане чрез Stripe • Автоматично конвертиране", noReturn: "Важно: Без връщане", noReturnDesc: "Нашите продукти не могат да бъдат върнати. Това е логично за цифрови документи." },
  fi: { badge: "Hinnoittelu", title: "Olennaiset oikeudelliset asiakirjat valokuvaajille", desc: "Täydellinen paketti kaikilla oikeudellisilla asiakirjoilla valokuvausliiketoimintaasi varten.", cardTitle: "Täydellinen oikeudellinen paketti valokuvaajille", cardDesc: "Kaikki olennaiset oikeudelliset asiakirjat rajoittamattomaan käyttöön", items: ["Käyttöehdot valokuvaajille", "Toimeksiantosopimus malleilla", "Tietosuojakäytäntö (GDPR)", "Evästekäytäntö (GDPR)", "Vastuuvapauslauseke", "Oikeuksista luopuminen malleille", "Tekijänoikeussuoja", "Käyttöönotto-opas"], stripe: "Turvallinen maksu Stripen kautta • Automaattinen muunnos", noReturn: "Tärkeää: Ei palautuksia", noReturnDesc: "Tuotteitamme ei voi palauttaa. Tämä on loogista digitaalisille asiakirjoille." },
  ru: { badge: "Цены", title: "Основные юридические документы для фотографов", desc: "Полный пакет юридических документов для вашего фотобизнеса.", cardTitle: "Полный юридический пакет для фотографов", cardDesc: "Все основные юридические документы для неограниченного использования", items: ["Условия использования для фотографов", "Договор на работу с шаблонами", "Политика конфиденциальности (GDPR)", "Политика cookies (GDPR)", "Отказ от ответственности", "Отказ от претензий для моделей", "Защита авторских прав", "Руководство по внедрению"], stripe: "Безопасная оплата через Stripe • Автоматическая конвертация", noReturn: "Важно: Без возврата", noReturnDesc: "Наши продукты не подлежат возврату. Это логично для цифровых документов." },
  zh: { badge: "价格", title: "摄影师必备法律文件", desc: "包含摄影业务所需全部法律文件的完整套餐。", cardTitle: "摄影师完整法律套餐", cardDesc: "所有必备法律文件，无限使用", items: ["摄影师条款与条件", "委托协议及模板", "隐私政策 (GDPR合规)", "Cookie政策 (GDPR合规)", "免责声明", "模特权利放弃", "版权保护", "实施指南"], stripe: "通过Stripe安全支付 • 自动转换为当地货币", noReturn: "重要：不退货", noReturnDesc: "我们的产品不接受退货。这对于可以轻松复制的数字文件是合理的。" },
  hi: { badge: "मूल्य निर्धारण", title: "फ़ोटोग्राफ़रों के लिए आवश्यक कानूनी दस्तावेज़", desc: "आपके फ़ोटोग्राफ़ी व्यवसाय के लिए सभी कानूनी दस्तावेज़ों का पूर्ण पैकेज।", cardTitle: "फ़ोटोग्राफ़रों के लिए पूर्ण कानूनी पैकेज", cardDesc: "असीमित उपयोग के लिए सभी आवश्यक कानूनी दस्तावेज़", items: ["फ़ोटोग्राफ़रों के लिए नियम और शर्तें", "टेम्पलेट्स के साथ असाइनमेंट अनुबंध", "गोपनीयता नीति (GDPR)", "कुकी नीति (GDPR)", "अस्वीकरण", "मॉडल छूट", "कॉपीराइट सुरक्षा", "कार्यान्वयन गाइड"], stripe: "Stripe के माध्यम से सुरक्षित भुगतान • स्वचालित रूपांतरण", noReturn: "महत्वपूर्ण: कोई वापसी नहीं", noReturnDesc: "हमारे उत्पाद वापस नहीं किए जा सकते। यह डिजिटल दस्तावेज़ों के लिए तर्कसंगत है।" },
  ja: { badge: "料金", title: "写真家に必要な法的文書", desc: "写真ビジネスに必要なすべての法的文書の完全パッケージ。", cardTitle: "写真家向け完全法的パッケージ", cardDesc: "無制限使用のためのすべての必須法的文書", items: ["写真家向け利用規約", "テンプレート付き業務委託契約", "プライバシーポリシー (GDPR)", "Cookieポリシー (GDPR)", "免責事項", "モデル権利放棄", "著作権保護", "実装ガイド"], stripe: "Stripeによる安全な支払い • 自動通貨換算", noReturn: "重要：返品不可", noReturnDesc: "当社の製品は返品できません。デジタル文書としては合理的です。" },
  ar: { badge: "التسعير", title: "الوثائق القانونية الأساسية للمصورين", desc: "حزمة كاملة بجميع الوثائق القانونية لأعمال التصوير الخاصة بك.", cardTitle: "الحزمة القانونية الكاملة للمصورين", cardDesc: "جميع الوثائق القانونية الأساسية للاستخدام غير المحدود", items: ["الشروط والأحكام للمصورين", "اتفاقية التكليف مع القوالب", "سياسة الخصوصية (GDPR)", "سياسة ملفات تعريف الارتباط (GDPR)", "إخلاء المسؤولية", "التنازل للنماذج", "حماية حقوق النشر", "دليل التنفيذ"], stripe: "دفع آمن عبر Stripe • تحويل تلقائي", noReturn: "مهم: لا إرجاع", noReturnDesc: "لا يمكن إرجاع منتجاتنا. هذا منطقي للوثائق الرقمية." },
  ko: { badge: "가격", title: "사진작가를 위한 필수 법적 문서", desc: "사진 비즈니스에 필요한 모든 법적 문서의 완전한 패키지.", cardTitle: "사진작가를 위한 완전한 법적 패키지", cardDesc: "무제한 사용을 위한 모든 필수 법적 문서", items: ["사진작가를 위한 이용약관", "템플릿 포함 위탁 계약", "개인정보 보호정책 (GDPR)", "쿠키 정책 (GDPR)", "면책조항", "모델 권리 포기", "저작권 보호", "구현 가이드"], stripe: "Stripe를 통한 안전한 결제 • 자동 통화 변환", noReturn: "중요: 반품 불가", noReturnDesc: "당사 제품은 반품할 수 없습니다. 디지털 문서로서 합리적입니다." },
  cs: { badge: "Ceník", title: "Základní právní dokumenty pro fotografy", desc: "Kompletní balíček se všemi právními dokumenty pro vaše fotografické podnikání.", cardTitle: "Kompletní právní balíček pro fotografy", cardDesc: "Všechny základní právní dokumenty pro neomezené použití", items: ["Obchodní podmínky pro fotografy", "Smlouva o dílo se šablonami", "Zásady ochrany osobních údajů (GDPR)", "Zásady cookies (GDPR)", "Prohlášení", "Vzdání se nároku pro modely", "Ochrana autorských práv", "Průvodce implementací"], stripe: "Bezpečná platba přes Stripe • Automatický převod měny", noReturn: "Důležité: Bez vrácení", noReturnDesc: "Naše produkty nelze vrátit. To dává smysl u digitálních dokumentů." },
  hu: { badge: "Árak", title: "Alapvető jogi dokumentumok fotósoknak", desc: "Teljes csomag minden jogi dokumentummal fotóvállalkozásához.", cardTitle: "Teljes jogi csomag fotósoknak", cardDesc: "Minden alapvető jogi dokumentum korlátlan használatra", items: ["Általános feltételek fotósoknak", "Megbízási szerződés sablonokkal", "Adatvédelmi irányelvek (GDPR)", "Cookie szabályzat (GDPR)", "Felelősségkizárás", "Lemondó nyilatkozat modelleknek", "Szerzői jogi védelem", "Megvalósítási útmutató"], stripe: "Biztonságos fizetés Stripe-on keresztül • Automatikus pénznemváltás", noReturn: "Fontos: Nincs visszatérítés", noReturnDesc: "Termékeink nem visszaküldhetők. Digitális dokumentumok esetében ez logikus." },
  uk: { badge: "Ціни", title: "Основні юридичні документи для фотографів", desc: "Повний пакет юридичних документів для вашого фотобізнесу.", cardTitle: "Повний юридичний пакет для фотографів", cardDesc: "Усі основні юридичні документи для необмеженого використання", items: ["Умови використання для фотографів", "Договір на роботу з шаблонами", "Політика конфіденційності (GDPR)", "Політика cookies (GDPR)", "Застереження", "Відмова від претензій для моделей", "Захист авторських прав", "Посібник з впровадження"], stripe: "Безпечна оплата через Stripe • Автоматична конвертація", noReturn: "Важливо: Без повернення", noReturnDesc: "Наші продукти не підлягають поверненню. Це логічно для цифрових документів." },
  sk: { badge: "Cenník", title: "Základné právne dokumenty pre fotografov", desc: "Kompletný balíček so všetkými právnymi dokumentmi pre vaše fotografické podnikanie.", cardTitle: "Kompletný právny balíček pre fotografov", cardDesc: "Všetky základné právne dokumenty pre neobmedzené použitie", items: ["Obchodné podmienky pre fotografov", "Zmluva o dielo so šablónami", "Zásady ochrany súkromia (GDPR)", "Zásady cookies (GDPR)", "Vyhlásenie", "Vzdanie sa nároku pre modelov", "Ochrana autorských práv", "Sprievodca implementáciou"], stripe: "Bezpečná platba cez Stripe • Automatický prevod meny", noReturn: "Dôležité: Bez vrátenia", noReturnDesc: "Naše produkty nie je možné vrátiť. To je logické pre digitálne dokumenty." },
  hr: { badge: "Cijene", title: "Osnovni pravni dokumenti za fotografe", desc: "Kompletan paket sa svim pravnim dokumentima za vašu fotografsku djelatnost.", cardTitle: "Kompletan pravni paket za fotografe", cardDesc: "Svi osnovni pravni dokumenti za neograničenu uporabu", items: ["Uvjeti korištenja za fotografe", "Ugovor o zadatku s predlošcima", "Politika privatnosti (GDPR)", "Politika kolačića (GDPR)", "Odricanje od odgovornosti", "Odricanje za modele", "Zaštita autorskih prava", "Vodič za implementaciju"], stripe: "Sigurno plaćanje putem Stripe • Automatska konverzija", noReturn: "Važno: Bez povrata", noReturnDesc: "Naši proizvodi se ne mogu vratiti. To je logično za digitalne dokumente." },
  sr: { badge: "Цене", title: "Основни правни документи за фотографе", desc: "Комплетан пакет правних докумената за ваше фотографско пословање.", cardTitle: "Комплетан правни пакет за фотографе", cardDesc: "Сви основни правни документи за неограничену употребу", items: ["Услови коришћења за фотографе", "Уговор о делу са шаблонима", "Политика приватности (GDPR)", "Политика колачића (GDPR)", "Одрицање од одговорности", "Одрицање за моделе", "Заштита ауторских права", "Водич за имплементацију"], stripe: "Сигурно плаћање путем Stripe • Аутоматска конверзија", noReturn: "Важно: Без поврата", noReturnDesc: "Наши производи се не могу вратити. То је логично за дигиталне документе." },
  sl: { badge: "Cenik", title: "Bistveni pravni dokumenti za fotografe", desc: "Celoten paket z vsemi pravnimi dokumenti za vašo fotografsko dejavnost.", cardTitle: "Celoten pravni paket za fotografe", cardDesc: "Vsi bistveni pravni dokumenti za neomejeno uporabo", items: ["Pogoji uporabe za fotografe", "Pogodba o naročilu s predlogami", "Pravilnik o zasebnosti (GDPR)", "Pravilnik o piškotkih (GDPR)", "Omejitev odgovornosti", "Odpoved za modele", "Zaščita avtorskih pravic", "Vodnik za implementacijo"], stripe: "Varno plačilo prek Stripe • Samodejna pretvorba", noReturn: "Pomembno: Brez vračila", noReturnDesc: "Naših izdelkov ni mogoče vrniti. To je logično za digitalne dokumente." },
  tr: { badge: "Fiyatlandırma", title: "Fotoğrafçılar için temel yasal belgeler", desc: "Fotoğrafçılık işiniz için tüm yasal belgeleri içeren eksiksiz paket.", cardTitle: "Fotoğrafçılar için eksiksiz yasal paket", cardDesc: "Sınırsız kullanım için tüm temel yasal belgeler", items: ["Fotoğrafçılar için şartlar ve koşullar", "Şablonlarla görev sözleşmesi", "Gizlilik politikası (GDPR)", "Çerez politikası (GDPR)", "Sorumluluk reddi", "Model feragat", "Telif hakkı koruması", "Uygulama kılavuzu"], stripe: "Stripe ile güvenli ödeme • Otomatik döviz dönüşümü", noReturn: "Önemli: İade yok", noReturnDesc: "Ürünlerimiz iade edilemez. Dijital belgeler için bu mantıklıdır." },
};

interface Props { lang: string; }

const PricingPhotographyMulti = ({ lang }: Props) => {
  const t = translations[lang];
  return (
    <section id="pricing" className="py-20 bg-primary/5">
      <div className="container">
        <div className="text-center mb-12">
          <Badge variant="outline" className="mb-4">{t.badge}</Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">{t.title}</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">{t.desc}</p>
        </div>
        <div className="max-w-2xl mx-auto">
          <Card className="border-primary shadow-xl">
            <CardHeader className="text-center pb-8">
              <CardTitle className="text-2xl md:text-3xl mb-3">{t.cardTitle}</CardTitle>
              <CardDescription className="text-base md:text-lg">{t.cardDesc}</CardDescription>
              <div className="flex justify-center mt-6">
                <img src="/images/iaee-logo.png" alt="IAEE - Essential Legal Documents for Photography" className="h-20 w-20 object-contain" loading="eager" />
              </div>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-3">
                {t.items.map((item, index) => (
                  <div key={index} className="flex items-center gap-3">
                    <div className="h-5 w-5 rounded-full bg-red-600 flex items-center justify-center flex-shrink-0">
                      <Check className="h-3 w-3 text-white" />
                    </div>
                    <span className="text-foreground">{item}</span>
                  </div>
                ))}
              </div>
              <div className="pt-6 border-t flex justify-center"><StripeBuyButton /></div>
              <div className="flex items-center justify-center gap-2 mt-4">
                <img src={stripeLogo} alt="Stripe" className="h-5 w-5" />
                <p className="text-sm font-medium text-muted-foreground">{t.stripe}</p>
              </div>
              <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-3 text-base font-medium">
                <div className="flex gap-2">
                  <AlertTriangle className="h-4 w-4 text-destructive flex-shrink-0 mt-0.5" />
                  <div>
                    <h4 className="font-semibold text-sm text-foreground mb-0.5">{t.noReturn}</h4>
                    <p className="text-xs text-muted-foreground">{t.noReturnDesc}</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
};

export default PricingPhotographyMulti;
