import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Shield, FileText, AlertCircle, ScrollText, Cookie, BookOpen, Camera } from "lucide-react";

const serviceIcons = [ScrollText, FileText, Shield, Cookie, AlertCircle, Camera, BookOpen];

const translations: Record<string, {
  badge: string; title: string; desc: string;
  services: { title: string; desc: string; details: string[] }[];
  cards: { title: string; desc: string }[];
}> = {
  sv: { badge: "Tjänster", title: "Väsentliga juridiska dokument för fotografer", desc: "För en professionell fotograferingsverksamhet behöver du dessa juridiska dokument för din webbplats.", services: [{ title: "Villkor", desc: "Omfattande villkor för fotografer", details: ["Avgifter och betalningsvillkor", "Uppdragsgenomförande och leverans", "Upphovsrätt och porträtträttigheter", "Avboknings- och ombokningspolicyer"] }, { title: "Uppdragsavtal (Offerte)", desc: "Professionell kontraktsmall", details: ["Färdig mall", "Exempelavtal", "E-postmallar", "Anpassningsbar"] }, { title: "Integritetspolicy", desc: "GDPR-kompatibel", details: ["Kontaktformulärsskydd", "Kundhantering", "Fotografispecifika villkor", "Obligatoriskt för kontaktformulär"] }, { title: "Cookiepolicy", desc: "Fullständig GDPR-efterlevnad", details: ["Specifikt för fotografer", "Komplett GDPR", "Cookieanvändning", "Samtyckeshantering"] }, { title: "Ansvarsfriskrivning", desc: "Skydda foton och innehåll", details: ["Foto- och innehållsskydd", "Äganderättsuttalanden", "Varningar för upphovsrättsintrång", "Användningsbegränsningar"] }, { title: "Frisläppning", desc: "Juridiskt skydd med modeller", details: ["Juridiskt skydd före fotografering", "Tydliga avtal med modeller", "Modellrelease", "Porträtträttsskydd"] }, { title: "Upphovsrättsskydd", desc: "Internationella upphovsrättsvillkor", details: ["Världsomspännande skydd", "Licensriktlinjer", "Attributionskrav", "Verkställande"] }], cards: [{ title: "Perfekt för alla fotografer", desc: "Oavsett om du är porträtt-, bröllops-, kommersiell eller eventfotograf." }, { title: "För ALLA dina webbplatser", desc: "Använd för alla webbplatser utan separata licenser!" }, { title: "Skydda ditt arbete", desc: "Dessa dokument minskar risker och ger maximalt skydd." }] },
  pl: { badge: "Usługi", title: "Niezbędne dokumenty prawne dla fotografów", desc: "Dla profesjonalnej działalności fotograficznej potrzebujesz tych dokumentów prawnych na swojej stronie.", services: [{ title: "Regulamin", desc: "Kompleksowy regulamin dla fotografów", details: ["Opłaty i warunki płatności", "Realizacja i dostawa zleceń", "Prawa autorskie i portretowe", "Polityka anulowania"] }, { title: "Umowa zlecenia (Offerte)", desc: "Profesjonalny szablon umowy", details: ["Gotowy szablon", "Przykładowa umowa", "Szablony e-maili", "Dostosowywalny"] }, { title: "Polityka prywatności", desc: "Zgodna z RODO", details: ["Ochrona formularzy kontaktowych", "Obsługa danych klientów", "Specyficzne dla fotografii", "Obowiązkowa"] }, { title: "Polityka cookies", desc: "Pełna zgodność z RODO", details: ["Dla fotografów", "Kompletna RODO", "Wyjaśnienie cookies", "Zarządzanie zgodami"] }, { title: "Zastrzeżenie", desc: "Ochrona zdjęć i treści", details: ["Ochrona zdjęć", "Oświadczenia własności", "Ostrzeżenia o naruszeniu", "Ograniczenia użytkowania"] }, { title: "Zrzeczenie się roszczeń", desc: "Ochrona prawna umów z modelami", details: ["Ochrona przed sesją", "Jasne umowy z modelami", "Release modela", "Ochrona praw portretowych"] }, { title: "Ochrona praw autorskich", desc: "Międzynarodowe warunki", details: ["Światowa ochrona", "Wytyczne licencyjne", "Wymogi atrybucji", "Egzekwowanie"] }], cards: [{ title: "Idealne dla wszystkich fotografów", desc: "Niezależnie czy zajmujesz się portretami, ślubami czy eventami." }, { title: "Dla WSZYSTKICH Twoich stron", desc: "Używaj na wszystkich stronach bez dodatkowych licencji!" }, { title: "Chroń swoją pracę", desc: "Te dokumenty minimalizują ryzyko i zapewniają maksymalną ochronę." }] },
  el: { badge: "Υπηρεσίες", title: "Βασικά νομικά έγγραφα για φωτογράφους", desc: "Για μια επαγγελματική φωτογραφική επιχείρηση χρειάζεστε αυτά τα νομικά έγγραφα.", services: [{ title: "Όροι χρήσης", desc: "Ολοκληρωμένοι όροι για φωτογράφους", details: ["Αμοιβές και όροι πληρωμής", "Εκτέλεση και παράδοση", "Πνευματικά δικαιώματα", "Πολιτική ακύρωσης"] }, { title: "Σύμβαση ανάθεσης", desc: "Επαγγελματικό πρότυπο", details: ["Έτοιμο πρότυπο", "Παράδειγμα σύμβασης", "Πρότυπα email", "Προσαρμόσιμο"] }, { title: "Πολιτική απορρήτου", desc: "Συμμόρφωση GDPR", details: ["Προστασία φόρμας", "Χειρισμός δεδομένων", "Ειδικό για φωτογραφία", "Υποχρεωτικό"] }, { title: "Πολιτική cookies", desc: "Πλήρης συμμόρφωση GDPR", details: ["Για φωτογράφους", "Πλήρες GDPR", "Εξήγηση cookies", "Διαχείριση συγκατάθεσης"] }, { title: "Αποποίηση ευθύνης", desc: "Προστασία φωτογραφιών", details: ["Προστασία περιεχομένου", "Δηλώσεις ιδιοκτησίας", "Προειδοποιήσεις", "Περιορισμοί"] }, { title: "Παραίτηση", desc: "Νομική κάλυψη μοντέλων", details: ["Νομική κάλυψη", "Σαφείς συμφωνίες", "Αδεια μοντέλου", "Δικαιώματα πορτρέτου"] }, { title: "Προστασία πνευματικών δικαιωμάτων", desc: "Διεθνής κάλυψη", details: ["Παγκόσμια προστασία", "Αδειοδότηση", "Απαιτήσεις", "Επιβολή"] }], cards: [{ title: "Ιδανικό για όλους τους φωτογράφους", desc: "Είτε είστε πορτρέτο, γάμου ή εκδήλωσης." }, { title: "Για ΟΛΕΣ τις ιστοσελίδες σας", desc: "Χρησιμοποιήστε χωρίς ξεχωριστές άδειες!" }, { title: "Προστατέψτε τη δουλειά σας", desc: "Αυτά τα έγγραφα μειώνουν κινδύνους και παρέχουν μέγιστη προστασία." }] },
  da: { badge: "Tjenester", title: "Vigtige juridiske dokumenter til fotografer", desc: "For en professionel fotografivirksomhed har du brug for disse dokumenter.", services: [{ title: "Vilkår", desc: "Omfattende vilkår for fotografer", details: ["Gebyrer og betalingsvilkår", "Opgavegennemførelse", "Ophavsret og portrætrettigheder", "Afbestillingspolitik"] }, { title: "Opgaveaftale (Offerte)", desc: "Professionel kontraktskabelon", details: ["Færdig skabelon", "Eksempelaftale", "E-mailskabeloner", "Tilpasselig"] }, { title: "Privatlivspolitik", desc: "GDPR-kompatibel", details: ["Kontaktformularbeskyttelse", "Kundedatahåndtering", "Fotografispecifik", "Obligatorisk"] }, { title: "Cookiepolitik", desc: "Fuld GDPR-overholdelse", details: ["Til fotografer", "Komplet GDPR", "Cookieforklaring", "Samtykkeforvaltning"] }, { title: "Ansvarsfraskrivelse", desc: "Beskyt fotos og indhold", details: ["Foto- og indholdsbeskyttelse", "Ejerskabserklæringer", "Krænkelsesadvarsler", "Brugsbegrænsninger"] }, { title: "Fraskrivelse", desc: "Juridisk dækning for modeller", details: ["Forhåndsdækning", "Klare aftaler", "Modelrelease", "Portrætrettigheder"] }, { title: "Ophavsretsbeskyttelse", desc: "Internationale vilkår", details: ["Verdensomspændende beskyttelse", "Licensretningslinjer", "Kreditkrav", "Håndhævelse"] }], cards: [{ title: "Perfekt til alle fotografer", desc: "Uanset om du er portræt-, bryllups- eller eventfotograf." }, { title: "Til ALLE dine websteder", desc: "Brug til alle websteder uden separate licenser!" }, { title: "Beskyt dit arbejde", desc: "Disse dokumenter reducerer risici og giver maksimal beskyttelse." }] },
  no: { badge: "Tjenester", title: "Viktige juridiske dokumenter for fotografer", desc: "For en profesjonell fotografivirksomhet trenger du disse dokumentene.", services: [{ title: "Vilkår", desc: "Omfattende vilkår for fotografer", details: ["Honorarer og betalingsvilkår", "Oppdragsgjennomføring", "Opphavsrett og portrettrettigheter", "Avbestillingspolicy"] }, { title: "Oppdragsavtale (Offerte)", desc: "Profesjonell kontraktsmal", details: ["Ferdig mal", "Eksempelavtale", "E-postmaler", "Tilpassbar"] }, { title: "Personvernregler", desc: "GDPR-kompatibel", details: ["Kontaktskjemabeskyttelse", "Kundedatahåndtering", "Fotografispesifikk", "Obligatorisk"] }, { title: "Informasjonskapselregler", desc: "Full GDPR-overholdelse", details: ["For fotografer", "Komplett GDPR", "Informasjonskapsler", "Samtykkehåndtering"] }, { title: "Ansvarsfraskrivelse", desc: "Beskytt bilder og innhold", details: ["Bilde- og innholdsbeskyttelse", "Eierskapsuttalelser", "Krenkelsesadvarsler", "Bruksbegrensninger"] }, { title: "Fraskrivelse", desc: "Juridisk dekning for modeller", details: ["Forhåndsdekning", "Klare avtaler", "Modellrelease", "Portrettrettigheter"] }, { title: "Opphavsrettsbeskyttelse", desc: "Internasjonale vilkår", details: ["Verdensomspennende beskyttelse", "Lisensretningslinjer", "Kredittkrav", "Håndhevelse"] }], cards: [{ title: "Perfekt for alle fotografer", desc: "Uansett om du er portrett-, bryllups- eller eventfotograf." }, { title: "For ALLE dine nettsteder", desc: "Bruk for alle nettsteder uten separate lisenser!" }, { title: "Beskytt arbeidet ditt", desc: "Disse dokumentene reduserer risiko og gir maksimal beskyttelse." }] },
  ro: { badge: "Servicii", title: "Documente juridice esențiale pentru fotografi", desc: "Pentru o afacere profesională de fotografie aveți nevoie de aceste documente.", services: [{ title: "Termeni și condiții", desc: "Termeni pentru fotografi", details: ["Tarife și plăți", "Execuție și livrare", "Drepturi de autor", "Politica de anulare"] }, { title: "Contract de atribuire", desc: "Șablon profesional", details: ["Șablon gata", "Exemplu contract", "Șabloane email", "Personalizabil"] }, { title: "Politica de confidențialitate", desc: "Conformă GDPR", details: ["Protecție formular", "Gestionare date", "Specific foto", "Obligatoriu"] }, { title: "Politica de cookies", desc: "Conformitate GDPR", details: ["Pentru fotografi", "GDPR complet", "Explicație cookies", "Consimțământ"] }, { title: "Declinare", desc: "Protecție fotografii", details: ["Protecție conținut", "Declarații proprietate", "Avertismente", "Restricții"] }, { title: "Renunțare", desc: "Acoperire juridică modele", details: ["Acoperire pre-sesiune", "Acorduri clare", "Release model", "Drepturi portret"] }, { title: "Protecția drepturilor de autor", desc: "Acoperire internațională", details: ["Protecție mondială", "Licențiere", "Atribuire", "Aplicare"] }], cards: [{ title: "Perfect pentru toți fotografii", desc: "Indiferent de specialitate." }, { title: "Pentru TOATE site-urile", desc: "Utilizare nelimitată fără licențe separate!" }, { title: "Protejați-vă munca", desc: "Aceste documente reduc riscurile și oferă protecție maximă." }] },
  bg: { badge: "Услуги", title: "Основни правни документи за фотографи", desc: "За професионален фотографски бизнес ви трябват тези документи.", services: [{ title: "Общи условия", desc: "За фотографи", details: ["Такси и плащания", "Изпълнение и доставка", "Авторски права", "Политика за отмяна"] }, { title: "Договор за възлагане", desc: "Професионален шаблон", details: ["Готов шаблон", "Пример за договор", "Шаблони за имейл", "Персонализируем"] }, { title: "Политика за поверителност", desc: "GDPR съвместима", details: ["Защита на форми", "Управление на данни", "Специфично за фото", "Задължително"] }, { title: "Политика за бисквитки", desc: "Пълно GDPR съответствие", details: ["За фотографи", "Пълно GDPR", "Обяснение", "Съгласие"] }, { title: "Отказ от отговорност", desc: "Защита на снимки", details: ["Защита на съдържание", "Декларации за собственост", "Предупреждения", "Ограничения"] }, { title: "Отказ от претенции", desc: "Правна защита за модели", details: ["Предварителна защита", "Ясни споразумения", "Разрешение за модел", "Портретни права"] }, { title: "Защита на авторски права", desc: "Международно покритие", details: ["Световна защита", "Лицензиране", "Изисквания", "Прилагане"] }], cards: [{ title: "Перфектно за всички фотографи", desc: "Независимо от специалността." }, { title: "За ВСИЧКИ ваши сайтове", desc: "Използвайте без отделни лицензи!" }, { title: "Защитете работата си", desc: "Тези документи намаляват рисковете." }] },
  fi: { badge: "Palvelut", title: "Olennaiset oikeudelliset asiakirjat valokuvaajille", desc: "Ammattimaiseen valokuvausliiketoimintaan tarvitset nämä asiakirjat.", services: [{ title: "Käyttöehdot", desc: "Valokuvaajille suunnatut", details: ["Maksut ja ehdot", "Toteutus ja toimitus", "Tekijänoikeudet", "Peruutuskäytäntö"] }, { title: "Toimeksiantosopimus", desc: "Ammattimainen malli", details: ["Valmis malli", "Esimerkkisopimus", "Sähköpostimallit", "Muokattavissa"] }, { title: "Tietosuojakäytäntö", desc: "GDPR-yhteensopiva", details: ["Lomakesuoja", "Tietojenkäsittely", "Valokuvakohtainen", "Pakollinen"] }, { title: "Evästekäytäntö", desc: "Täysi GDPR-vaatimustenmukaisuus", details: ["Valokuvaajille", "Täysi GDPR", "Evästeet", "Suostumuksen hallinta"] }, { title: "Vastuuvapauslauseke", desc: "Kuvien suoja", details: ["Sisällön suoja", "Omistajuus", "Varoitukset", "Rajoitukset"] }, { title: "Oikeuksista luopuminen", desc: "Mallien oikeudellinen suoja", details: ["Ennakkosuoja", "Selkeät sopimukset", "Mallin lupa", "Muotokuva"] }, { title: "Tekijänoikeussuoja", desc: "Kansainvälinen kattavuus", details: ["Maailmanlaajuinen", "Lisensointi", "Vaatimukset", "Täytäntöönpano"] }], cards: [{ title: "Täydellinen kaikille valokuvaajille", desc: "Riippumatta erikoistumisestasi." }, { title: "KAIKILLE sivustoillesi", desc: "Käytä kaikilla sivustoilla ilman erillisiä lisenssejä!" }, { title: "Suojaa työsi", desc: "Nämä asiakirjat vähentävät riskejä." }] },
  ru: { badge: "Услуги", title: "Основные юридические документы для фотографов", desc: "Для профессионального фотобизнеса вам нужны эти документы.", services: [{ title: "Условия использования", desc: "Для фотографов", details: ["Гонорары и оплата", "Выполнение и доставка", "Авторские права", "Политика отмены"] }, { title: "Договор на работу", desc: "Профессиональный шаблон", details: ["Готовый шаблон", "Пример договора", "Шаблоны email", "Настраиваемый"] }, { title: "Политика конфиденциальности", desc: "Соответствует GDPR", details: ["Защита форм", "Обработка данных", "Для фотографии", "Обязательно"] }, { title: "Политика cookies", desc: "Полное соответствие GDPR", details: ["Для фотографов", "Полный GDPR", "Описание cookies", "Управление согласием"] }, { title: "Отказ от ответственности", desc: "Защита фотографий", details: ["Защита контента", "Заявления о собственности", "Предупреждения", "Ограничения"] }, { title: "Отказ от претензий", desc: "Юридическая защита моделей", details: ["Предварительная защита", "Чёткие соглашения", "Релиз модели", "Портретные права"] }, { title: "Защита авторских прав", desc: "Международная защита", details: ["Мировая защита", "Лицензирование", "Требования", "Исполнение"] }], cards: [{ title: "Идеально для всех фотографов", desc: "Независимо от специализации." }, { title: "Для ВСЕХ ваших сайтов", desc: "Используйте без отдельных лицензий!" }, { title: "Защитите свою работу", desc: "Эти документы снижают риски и обеспечивают максимальную защиту." }] },
  zh: { badge: "服务", title: "摄影师必备法律文件", desc: "专业摄影业务需要这些法律文件。", services: [{ title: "条款与条件", desc: "摄影师专用条款", details: ["费用和付款条件", "执行和交付", "版权和肖像权", "取消政策"] }, { title: "委托协议", desc: "专业合同模板", details: ["现成模板", "示例协议", "邮件模板", "可定制"] }, { title: "隐私政策", desc: "符合GDPR", details: ["表单保护", "数据处理", "摄影专用", "必需"] }, { title: "Cookie政策", desc: "完全GDPR合规", details: ["摄影师专用", "完整GDPR", "Cookie说明", "同意管理"] }, { title: "免责声明", desc: "保护照片和内容", details: ["内容保护", "所有权声明", "侵权警告", "使用限制"] }, { title: "权利放弃", desc: "模特法律保护", details: ["拍摄前保护", "明确协议", "模特授权", "肖像权"] }, { title: "版权保护", desc: "国际覆盖", details: ["全球保护", "许可指南", "署名要求", "执行"] }], cards: [{ title: "适合所有摄影师", desc: "无论您的专业领域是什么。" }, { title: "适用于所有网站", desc: "无需单独许可证！" }, { title: "保护您的作品", desc: "这些文件降低风险并提供最大保护。" }] },
  hi: { badge: "सेवाएं", title: "फ़ोटोग्राफ़रों के लिए आवश्यक कानूनी दस्तावेज़", desc: "पेशेवर फ़ोटोग्राफ़ी व्यवसाय के लिए ये दस्तावेज़ आवश्यक हैं।", services: [{ title: "नियम और शर्तें", desc: "फ़ोटोग्राफ़रों के लिए", details: ["शुल्क और भुगतान", "निष्पादन और वितरण", "कॉपीराइट", "रद्दीकरण नीति"] }, { title: "असाइनमेंट अनुबंध", desc: "पेशेवर टेम्पलेट", details: ["तैयार टेम्पलेट", "उदाहरण अनुबंध", "ईमेल टेम्पलेट", "अनुकूलन योग्य"] }, { title: "गोपनीयता नीति", desc: "GDPR अनुपालक", details: ["फ़ॉर्म सुरक्षा", "डेटा प्रबंधन", "फ़ोटोग्राफ़ी विशिष्ट", "अनिवार्य"] }, { title: "कुकी नीति", desc: "पूर्ण GDPR अनुपालन", details: ["फ़ोटोग्राफ़रों के लिए", "पूर्ण GDPR", "कुकी विवरण", "सहमति प्रबंधन"] }, { title: "अस्वीकरण", desc: "फ़ोटो सुरक्षा", details: ["सामग्री सुरक्षा", "स्वामित्व घोषणाएं", "चेतावनियां", "प्रतिबंध"] }, { title: "छूट", desc: "मॉडल कानूनी सुरक्षा", details: ["पूर्व सुरक्षा", "स्पष्ट समझौते", "मॉडल रिलीज़", "पोर्ट्रेट अधिकार"] }, { title: "कॉपीराइट सुरक्षा", desc: "अंतर्राष्ट्रीय कवरेज", details: ["विश्वव्यापी सुरक्षा", "लाइसेंसिंग", "आवश्यकताएं", "प्रवर्तन"] }], cards: [{ title: "सभी फ़ोटोग्राफ़रों के लिए उपयुक्त", desc: "आपकी विशेषता चाहे जो भी हो।" }, { title: "आपकी सभी वेबसाइटों के लिए", desc: "अलग लाइसेंस के बिना उपयोग करें!" }, { title: "अपने काम की रक्षा करें", desc: "ये दस्तावेज़ जोखिम कम करते हैं।" }] },
  ja: { badge: "サービス", title: "写真家に必要な法的文書", desc: "プロの写真ビジネスにはこれらの法的文書が必要です。", services: [{ title: "利用規約", desc: "写真家向けの条件", details: ["料金と支払い条件", "実行と納品", "著作権と肖像権", "キャンセルポリシー"] }, { title: "業務委託契約", desc: "プロフェッショナルテンプレート", details: ["テンプレート", "契約例", "メールテンプレート", "カスタマイズ可能"] }, { title: "プライバシーポリシー", desc: "GDPR準拠", details: ["フォーム保護", "データ管理", "写真固有", "必須"] }, { title: "Cookieポリシー", desc: "完全GDPR準拠", details: ["写真家向け", "完全GDPR", "Cookie説明", "同意管理"] }, { title: "免責事項", desc: "写真保護", details: ["コンテンツ保護", "所有権宣言", "警告", "制限"] }, { title: "権利放棄", desc: "モデルの法的保護", details: ["事前保護", "明確な合意", "モデルリリース", "肖像権"] }, { title: "著作権保護", desc: "国際的カバレッジ", details: ["世界的保護", "ライセンス", "要件", "執行"] }], cards: [{ title: "すべての写真家に最適", desc: "専門分野を問わず。" }, { title: "すべてのサイトに対応", desc: "個別ライセンス不要！" }, { title: "あなたの作品を守る", desc: "リスクを軽減し最大限の保護を提供。" }] },
  ar: { badge: "الخدمات", title: "الوثائق القانونية الأساسية للمصورين", desc: "لأعمال التصوير المهنية تحتاج هذه الوثائق.", services: [{ title: "الشروط والأحكام", desc: "شاملة للمصورين", details: ["الرسوم والدفع", "التنفيذ والتسليم", "حقوق النشر", "سياسة الإلغاء"] }, { title: "اتفاقية التكليف", desc: "قالب احترافي", details: ["قالب جاهز", "مثال عقد", "قوالب بريد", "قابل للتخصيص"] }, { title: "سياسة الخصوصية", desc: "متوافقة مع GDPR", details: ["حماية النماذج", "إدارة البيانات", "خاص بالتصوير", "إلزامي"] }, { title: "سياسة ملفات تعريف الارتباط", desc: "امتثال كامل GDPR", details: ["للمصورين", "GDPR كامل", "شرح الكوكيز", "إدارة الموافقة"] }, { title: "إخلاء المسؤولية", desc: "حماية الصور", details: ["حماية المحتوى", "بيانات الملكية", "تحذيرات", "قيود"] }, { title: "التنازل", desc: "حماية قانونية للنماذج", details: ["حماية مسبقة", "اتفاقيات واضحة", "إذن النموذج", "حقوق الصورة"] }, { title: "حماية حقوق النشر", desc: "تغطية دولية", details: ["حماية عالمية", "ترخيص", "متطلبات", "تنفيذ"] }], cards: [{ title: "مثالي لجميع المصورين", desc: "بغض النظر عن تخصصك." }, { title: "لجميع مواقعك", desc: "استخدم بدون تراخيص منفصلة!" }, { title: "احمِ عملك", desc: "هذه الوثائق تقلل المخاطر." }] },
  ko: { badge: "서비스", title: "사진작가를 위한 필수 법적 문서", desc: "전문 사진 비즈니스에 이 문서들이 필요합니다.", services: [{ title: "이용약관", desc: "사진작가를 위한 조건", details: ["수수료 및 결제", "실행 및 배송", "저작권", "취소 정책"] }, { title: "위탁 계약", desc: "전문 템플릿", details: ["준비된 템플릿", "계약 예시", "이메일 템플릿", "맞춤화 가능"] }, { title: "개인정보 보호정책", desc: "GDPR 준수", details: ["폼 보호", "데이터 관리", "사진 전용", "필수"] }, { title: "쿠키 정책", desc: "완전한 GDPR 준수", details: ["사진작가용", "완전 GDPR", "쿠키 설명", "동의 관리"] }, { title: "면책조항", desc: "사진 보호", details: ["콘텐츠 보호", "소유권 선언", "경고", "제한"] }, { title: "권리 포기", desc: "모델 법적 보호", details: ["사전 보호", "명확한 합의", "모델 릴리스", "초상권"] }, { title: "저작권 보호", desc: "국제적 보호", details: ["세계적 보호", "라이선스", "요구사항", "집행"] }], cards: [{ title: "모든 사진작가에게 적합", desc: "전문 분야에 상관없이." }, { title: "모든 웹사이트에 사용", desc: "별도 라이선스 없이!" }, { title: "작품을 보호하세요", desc: "이 문서는 위험을 줄이고 최대 보호를 제공합니다." }] },
  cs: { badge: "Služby", title: "Základní právní dokumenty pro fotografy", desc: "Pro profesionální fotografické podnikání potřebujete tyto dokumenty.", services: [{ title: "Obchodní podmínky", desc: "Pro fotografy", details: ["Poplatky a platby", "Realizace a dodání", "Autorská práva", "Storno podmínky"] }, { title: "Smlouva o dílo", desc: "Profesionální šablona", details: ["Hotová šablona", "Příklad smlouvy", "Emailové šablony", "Přizpůsobitelná"] }, { title: "Zásady ochrany osobních údajů", desc: "GDPR kompatibilní", details: ["Ochrana formulářů", "Správa dat", "Pro fotografii", "Povinné"] }, { title: "Zásady cookies", desc: "Plný soulad s GDPR", details: ["Pro fotografy", "Kompletní GDPR", "Popis cookies", "Správa souhlasu"] }, { title: "Prohlášení", desc: "Ochrana fotografií", details: ["Ochrana obsahu", "Vlastnická prohlášení", "Varování", "Omezení"] }, { title: "Vzdání se nároku", desc: "Právní ochrana modelů", details: ["Předchozí ochrana", "Jasné dohody", "Release modelu", "Portrétní práva"] }, { title: "Ochrana autorských práv", desc: "Mezinárodní pokrytí", details: ["Celosvětová ochrana", "Licencování", "Požadavky", "Vymáhání"] }], cards: [{ title: "Ideální pro všechny fotografy", desc: "Bez ohledu na specializaci." }, { title: "Pro VŠECHNY vaše weby", desc: "Bez samostatných licencí!" }, { title: "Chraňte svou práci", desc: "Tyto dokumenty snižují rizika." }] },
  hu: { badge: "Szolgáltatások", title: "Alapvető jogi dokumentumok fotósoknak", desc: "Professzionális fotóvállalkozáshoz szüksége van ezekre a dokumentumokra.", services: [{ title: "Általános feltételek", desc: "Fotósoknak", details: ["Díjak és fizetés", "Végrehajtás és szállítás", "Szerzői jogok", "Lemondási feltételek"] }, { title: "Megbízási szerződés", desc: "Professzionális sablon", details: ["Kész sablon", "Példa szerződés", "Email sablonok", "Testreszabható"] }, { title: "Adatvédelmi irányelvek", desc: "GDPR-kompatibilis", details: ["Űrlapvédelem", "Adatkezelés", "Fotóspecifikus", "Kötelező"] }, { title: "Cookie szabályzat", desc: "Teljes GDPR megfelelőség", details: ["Fotósoknak", "Teljes GDPR", "Cookie leírás", "Hozzájárulás kezelés"] }, { title: "Felelősségkizárás", desc: "Fotók védelme", details: ["Tartalomvédelem", "Tulajdonnyilatkozatok", "Figyelmeztetések", "Korlátozások"] }, { title: "Lemondó nyilatkozat", desc: "Modellek jogi védelme", details: ["Előzetes védelem", "Világos megállapodások", "Modell release", "Portréjogok"] }, { title: "Szerzői jogi védelem", desc: "Nemzetközi lefedettség", details: ["Világszintű védelem", "Licencelés", "Követelmények", "Érvényesítés"] }], cards: [{ title: "Tökéletes minden fotósnak", desc: "Szakterülettől függetlenül." }, { title: "MINDEN weboldalához", desc: "Külön licenc nélkül!" }, { title: "Védje munkáját", desc: "Ezek a dokumentumok csökkentik a kockázatokat." }] },
  uk: { badge: "Послуги", title: "Основні юридичні документи для фотографів", desc: "Для професійного фотобізнесу вам потрібні ці документи.", services: [{ title: "Умови використання", desc: "Для фотографів", details: ["Гонорари та оплата", "Виконання та доставка", "Авторські права", "Політика скасування"] }, { title: "Договір на роботу", desc: "Професійний шаблон", details: ["Готовий шаблон", "Приклад договору", "Шаблони email", "Налаштовуваний"] }, { title: "Політика конфіденційності", desc: "Відповідає GDPR", details: ["Захист форм", "Управління даними", "Для фотографії", "Обов'язково"] }, { title: "Політика cookies", desc: "Повна відповідність GDPR", details: ["Для фотографів", "Повний GDPR", "Опис cookies", "Управління згодою"] }, { title: "Застереження", desc: "Захист фотографій", details: ["Захист контенту", "Заяви про власність", "Попередження", "Обмеження"] }, { title: "Відмова від претензій", desc: "Юридичний захист моделей", details: ["Попередній захист", "Чіткі угоди", "Реліз моделі", "Портретні права"] }, { title: "Захист авторських прав", desc: "Міжнародне покриття", details: ["Світова захист", "Ліцензування", "Вимоги", "Виконання"] }], cards: [{ title: "Ідеально для всіх фотографів", desc: "Незалежно від спеціалізації." }, { title: "Для ВСІХ ваших сайтів", desc: "Без окремих ліцензій!" }, { title: "Захистіть свою роботу", desc: "Ці документи знижують ризики." }] },
  sk: { badge: "Služby", title: "Základné právne dokumenty pre fotografov", desc: "Pre profesionálne fotografické podnikanie potrebujete tieto dokumenty.", services: [{ title: "Obchodné podmienky", desc: "Pre fotografov", details: ["Poplatky a platby", "Realizácia a dodanie", "Autorské práva", "Storno podmienky"] }, { title: "Zmluva o dielo", desc: "Profesionálna šablóna", details: ["Hotová šablóna", "Príklad zmluvy", "Emailové šablóny", "Prispôsobiteľná"] }, { title: "Zásady ochrany súkromia", desc: "GDPR kompatibilné", details: ["Ochrana formulárov", "Správa údajov", "Pre fotografiu", "Povinné"] }, { title: "Zásady cookies", desc: "Plný súlad s GDPR", details: ["Pre fotografov", "Kompletné GDPR", "Popis cookies", "Správa súhlasu"] }, { title: "Vyhlásenie", desc: "Ochrana fotografií", details: ["Ochrana obsahu", "Vlastnícke vyhlásenia", "Varovania", "Obmedzenia"] }, { title: "Vzdanie sa nároku", desc: "Právna ochrana modelov", details: ["Predbežná ochrana", "Jasné dohody", "Release modelu", "Portrétne práva"] }, { title: "Ochrana autorských práv", desc: "Medzinárodné pokrytie", details: ["Celosvetová ochrana", "Licencovanie", "Požiadavky", "Vymáhanie"] }], cards: [{ title: "Ideálne pre všetkých fotografov", desc: "Bez ohľadu na špecializáciu." }, { title: "Pre VŠETKY vaše weby", desc: "Bez samostatných licencií!" }, { title: "Chráňte svoju prácu", desc: "Tieto dokumenty znižujú riziká." }] },
  hr: { badge: "Usluge", title: "Osnovni pravni dokumenti za fotografe", desc: "Za profesionalnu fotografsku djelatnost trebate ove dokumente.", services: [{ title: "Uvjeti korištenja", desc: "Za fotografe", details: ["Naknade i plaćanja", "Izvršenje i isporuka", "Autorska prava", "Politika otkazivanja"] }, { title: "Ugovor o zadatku", desc: "Profesionalni predložak", details: ["Gotov predložak", "Primjer ugovora", "Email predlošci", "Prilagodljiv"] }, { title: "Politika privatnosti", desc: "GDPR kompatibilna", details: ["Zaštita obrazaca", "Upravljanje podacima", "Za fotografiju", "Obvezno"] }, { title: "Politika kolačića", desc: "Potpuna GDPR usklađenost", details: ["Za fotografe", "Potpuni GDPR", "Opis kolačića", "Upravljanje pristankom"] }, { title: "Odricanje od odgovornosti", desc: "Zaštita fotografija", details: ["Zaštita sadržaja", "Izjave o vlasništvu", "Upozorenja", "Ograničenja"] }, { title: "Odricanje", desc: "Pravna zaštita modela", details: ["Prethodna zaštita", "Jasni dogovori", "Release modela", "Prava na portret"] }, { title: "Zaštita autorskih prava", desc: "Međunarodna pokrivenost", details: ["Svjetska zaštita", "Licenciranje", "Zahtjevi", "Provedba"] }], cards: [{ title: "Savršeno za sve fotografe", desc: "Bez obzira na specijalizaciju." }, { title: "Za SVE vaše stranice", desc: "Bez zasebnih licenci!" }, { title: "Zaštitite svoj rad", desc: "Ovi dokumenti smanjuju rizike." }] },
  sr: { badge: "Услуге", title: "Основни правни документи за фотографе", desc: "За професионално фотографско пословање потребни су вам ови документи.", services: [{ title: "Услови коришћења", desc: "За фотографе", details: ["Накнаде и плаћања", "Извршење и испорука", "Ауторска права", "Политика отказивања"] }, { title: "Уговор о делу", desc: "Професионални шаблон", details: ["Готов шаблон", "Пример уговора", "Email шаблони", "Прилагодљив"] }, { title: "Политика приватности", desc: "GDPR компатибилна", details: ["Заштита формулара", "Управљање подацима", "За фотографију", "Обавезно"] }, { title: "Политика колачића", desc: "Потпуна GDPR усклађеност", details: ["За фотографе", "Потпуни GDPR", "Опис колачића", "Управљање сагласношћу"] }, { title: "Одрицање од одговорности", desc: "Заштита фотографија", details: ["Заштита садржаја", "Изјаве о власништву", "Упозорења", "Ограничења"] }, { title: "Одрицање", desc: "Правна заштита модела", details: ["Претходна заштита", "Јасни договори", "Дозвола модела", "Права на портрет"] }, { title: "Заштита ауторских права", desc: "Међународно покриће", details: ["Светска заштита", "Лиценцирање", "Захтеви", "Спровођење"] }], cards: [{ title: "Савршено за све фотографе", desc: "Без обзира на специјализацију." }, { title: "За СВЕ ваше сајтове", desc: "Без засебних лиценци!" }, { title: "Заштитите свој рад", desc: "Ови документи смањују ризике." }] },
  sl: { badge: "Storitve", title: "Bistveni pravni dokumenti za fotografe", desc: "Za profesionalno fotografsko dejavnost potrebujete te dokumente.", services: [{ title: "Pogoji uporabe", desc: "Za fotografe", details: ["Pristojbine in plačila", "Izvedba in dostava", "Avtorske pravice", "Pravilnik o odpovedi"] }, { title: "Pogodba o naročilu", desc: "Profesionalna predloga", details: ["Pripravljena predloga", "Primer pogodbe", "Email predloge", "Prilagodljiva"] }, { title: "Pravilnik o zasebnosti", desc: "Skladen z GDPR", details: ["Zaščita obrazcev", "Upravljanje podatkov", "Za fotografijo", "Obvezno"] }, { title: "Pravilnik o piškotkih", desc: "Popolna skladnost z GDPR", details: ["Za fotografe", "Celoten GDPR", "Opis piškotkov", "Upravljanje soglasja"] }, { title: "Omejitev odgovornosti", desc: "Zaščita fotografij", details: ["Zaščita vsebine", "Izjave o lastništvu", "Opozorila", "Omejitve"] }, { title: "Odpoved", desc: "Pravna zaščita modelov", details: ["Predhodna zaščita", "Jasni dogovori", "Dovoljenje modela", "Pravice portreta"] }, { title: "Zaščita avtorskih pravic", desc: "Mednarodna pokritost", details: ["Svetovna zaščita", "Licenciranje", "Zahteve", "Uveljavljanje"] }], cards: [{ title: "Popolno za vse fotografe", desc: "Ne glede na specializacijo." }, { title: "Za VSE vaše strani", desc: "Brez ločenih licenc!" }, { title: "Zaščitite svoje delo", desc: "Ti dokumenti zmanjšujejo tveganja." }] },
  tr: { badge: "Hizmetler", title: "Fotoğrafçılar için temel yasal belgeler", desc: "Profesyonel fotoğrafçılık işiniz için bu belgelere ihtiyacınız var.", services: [{ title: "Şartlar ve Koşullar", desc: "Fotoğrafçılar için", details: ["Ücretler ve ödeme", "Yürütme ve teslimat", "Telif hakları", "İptal politikası"] }, { title: "Görev Sözleşmesi", desc: "Profesyonel şablon", details: ["Hazır şablon", "Örnek sözleşme", "E-posta şablonları", "Özelleştirilebilir"] }, { title: "Gizlilik Politikası", desc: "GDPR uyumlu", details: ["Form koruması", "Veri yönetimi", "Fotoğrafa özel", "Zorunlu"] }, { title: "Çerez Politikası", desc: "Tam GDPR uyumu", details: ["Fotoğrafçılar için", "Tam GDPR", "Çerez açıklaması", "Onay yönetimi"] }, { title: "Sorumluluk Reddi", desc: "Fotoğraf koruması", details: ["İçerik koruması", "Mülkiyet beyanları", "Uyarılar", "Kısıtlamalar"] }, { title: "Feragat", desc: "Model yasal koruması", details: ["Ön koruma", "Net anlaşmalar", "Model izni", "Portre hakları"] }, { title: "Telif Hakkı Koruması", desc: "Uluslararası kapsam", details: ["Dünya çapında koruma", "Lisanslama", "Gereksinimler", "Uygulama"] }], cards: [{ title: "Tüm fotoğrafçılar için mükemmel", desc: "Uzmanlık alanınız ne olursa olsun." }, { title: "TÜM web siteleriniz için", desc: "Ayrı lisans gerekmez!" }, { title: "Çalışmanızı koruyun", desc: "Bu belgeler riskleri azaltır." }] },
};

interface Props { lang: string; }

const ServicesPhotographyMulti = ({ lang }: Props) => {
  const t = translations[lang];
  return (
    <section id="services" className="py-20 bg-primary/5">
      <div className="container">
        <div className="text-center mb-12">
          <Badge variant="outline" className="mb-4">{t.badge}</Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">{t.title}</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">{t.desc}</p>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {t.services.map((service, index) => {
            const Icon = serviceIcons[index];
            return (
              <Card key={index} className="hover:shadow-lg transition-shadow bg-card text-foreground border-border">
                <CardHeader>
                  <div className="h-12 w-12 rounded-lg bg-red-600 flex items-center justify-center mb-4">
                    <Icon className="h-6 w-6 text-white" />
                  </div>
                  <CardTitle className="text-xl">{service.title}</CardTitle>
                  <CardDescription>{service.desc}</CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {service.details.map((detail, idx) => (
                      <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                        <span className="text-red-600 mt-1">•</span>
                        <span>{detail}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            );
          })}
        </div>
        <div className="mt-16 grid md:grid-cols-3 gap-8">
          {t.cards.map((card, index) => (
            <Card key={index} className="bg-primary border-primary text-primary-foreground">
              <CardHeader><CardTitle className="text-lg text-primary-foreground">{card.title}</CardTitle></CardHeader>
              <CardContent><p className="text-sm text-primary-foreground/90">{card.desc}</p></CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ServicesPhotographyMulti;
