import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Check, Shield } from "lucide-react";
import nicoleProfile from "@/assets/nicole-photography.png";

const scrollToSection = (id: string) => {
  document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
};

const translations: Record<string, {
  sectionTitle: string; sectionDesc: string;
  aboutTitle: string; aboutRole: string; aboutP1: string; aboutP2: string;
  packageTitle: string; packageDesc: string;
  items: string[];
  whyTitle: string; whyItems: string[];
  price: string; priceLabel: string; priceDesc: string; priceCta: string;
}> = {
  sv: { sectionTitle: "Varför juridiska dokument är avgörande för fotografer", sectionDesc: "Som professionell fotograf behöver du juridiskt skydd för din verksamhet, ditt kreativa arbete och dina kunder.", aboutTitle: "Om Nicole Henderson", aboutRole: "Juridisk specialist för kreativa yrkesverksamma", aboutP1: "Med års erfarenhet av att hjälpa fotografer att skydda sina verksamheter förstår jag de unika juridiska utmaningarna du möter.", aboutP2: "Dessa dokument är utformade för att vara enkelt anpassningsbara och ge maximalt juridiskt skydd.", packageTitle: "Komplett juridiskt paket för fotografer", packageDesc: "Allt du behöver för att juridiskt skydda din fotograferingsverksamhet", items: ["Villkor - specifikt utformade för fotografer", "Uppdragsavtal (Offerte) - med mallar och e-postexempel", "Integritetspolicy - GDPR-kompatibel", "Cookiepolicy - fullständig GDPR-efterlevnad", "Ansvarsfriskrivning - skydda dina foton och innehåll", "Frisläppning - juridiskt skydd för avtal med modeller", "Upphovsrättsskydd (Auteursrecht) - internationellt skydd"], whyTitle: "Varför välja detta paket?", whyItems: ["Redo att använda på minuter", "För alla dina fotografiwebbplatser", "Internationellt skydd", "Enkelt anpassningsbart"], price: "€79", priceLabel: "engångsbetalning", priceDesc: "Komplett juridiskt skydd för din fotograferingsverksamhet. Använd för obegränsat antal webbplatser. Inga återkommande avgifter.", priceCta: "Hämta komplett paket nu" },
  pl: { sectionTitle: "Dlaczego dokumenty prawne są niezbędne dla fotografów", sectionDesc: "Jako profesjonalny fotograf potrzebujesz ochrony prawnej dla swojej działalności, pracy twórczej i klientów.", aboutTitle: "O Nicole Henderson", aboutRole: "Specjalista prawny dla profesjonalistów kreatywnych", aboutP1: "Z wieloletnim doświadczeniem w pomaganiu fotografom w ochronie ich działalności rozumiem unikalne wyzwania prawne.", aboutP2: "Te dokumenty są zaprojektowane tak, aby były łatwo dostosowywalne i zapewniały maksymalną ochronę prawną.", packageTitle: "Kompletny pakiet prawny dla fotografów", packageDesc: "Wszystko, czego potrzebujesz do prawnej ochrony swojej działalności fotograficznej", items: ["Regulamin - specjalnie zaprojektowany dla fotografów", "Umowa zlecenia (Offerte) - z szablonami i przykładami e-maili", "Polityka prywatności - zgodna z RODO", "Polityka cookies - pełna zgodność z RODO", "Zastrzeżenie - ochrona zdjęć i treści", "Zrzeczenie się roszczeń - ochrona prawna umów z modelami", "Ochrona praw autorskich (Auteursrecht) - międzynarodowa ochrona"], whyTitle: "Dlaczego wybrać ten pakiet?", whyItems: ["Gotowy do użycia w minuty", "Dla wszystkich Twoich stron fotograficznych", "Międzynarodowa ochrona", "Łatwo dostosowywalny"], price: "€79", priceLabel: "jednorazowo", priceDesc: "Kompletna ochrona prawna dla Twojej działalności fotograficznej. Używaj dla nieograniczonej liczby stron.", priceCta: "Pobierz kompletny pakiet" },
  el: { sectionTitle: "Γιατί τα νομικά έγγραφα είναι απαραίτητα για φωτογράφους", sectionDesc: "Ως επαγγελματίας φωτογράφος, χρειάζεστε νομική προστασία για την επιχείρησή σας και τη δημιουργική σας δουλειά.", aboutTitle: "Σχετικά με τη Nicole Henderson", aboutRole: "Νομική ειδικός για δημιουργικούς επαγγελματίες", aboutP1: "Με χρόνια εμπειρίας στη βοήθεια φωτογράφων, κατανοώ τις μοναδικές νομικές προκλήσεις.", aboutP2: "Αυτά τα έγγραφα είναι σχεδιασμένα για εύκολη προσαρμογή με μέγιστη νομική προστασία.", packageTitle: "Πλήρες νομικό πακέτο για φωτογράφους", packageDesc: "Όλα όσα χρειάζεστε για τη νομική προστασία της φωτογραφικής σας επιχείρησης", items: ["Όροι χρήσης - ειδικά σχεδιασμένοι για φωτογράφους", "Σύμβαση ανάθεσης (Offerte) - με πρότυπα και παραδείγματα email", "Πολιτική απορρήτου - συμμόρφωση GDPR", "Πολιτική cookies - πλήρης συμμόρφωση GDPR", "Αποποίηση ευθύνης - προστασία φωτογραφιών και περιεχομένου", "Παραίτηση - νομική κάλυψη για συμφωνίες με μοντέλα", "Προστασία πνευματικών δικαιωμάτων - διεθνής κάλυψη"], whyTitle: "Γιατί να επιλέξετε αυτό το πακέτο;", whyItems: ["Έτοιμο σε λεπτά", "Για όλες τις ιστοσελίδες φωτογραφίας", "Διεθνής κάλυψη", "Εύκολα προσαρμόσιμο"], price: "€79", priceLabel: "εφάπαξ", priceDesc: "Πλήρης νομική προστασία. Χρήση σε απεριόριστες ιστοσελίδες. Χωρίς πάγιες χρεώσεις.", priceCta: "Αποκτήστε το πλήρες πακέτο" },
  da: { sectionTitle: "Hvorfor juridiske dokumenter er afgørende for fotografer", sectionDesc: "Som professionel fotograf har du brug for juridisk beskyttelse af din virksomhed, dit kreative arbejde og dine kunder.", aboutTitle: "Om Nicole Henderson", aboutRole: "Juridisk specialist for kreative professionelle", aboutP1: "Med års erfaring i at hjælpe fotografer forstår jeg de unikke juridiske udfordringer.", aboutP2: "Disse dokumenter er designet til at være nemme at tilpasse med maksimal juridisk beskyttelse.", packageTitle: "Komplet juridisk pakke til fotografer", packageDesc: "Alt du behøver for at beskytte din fotografivirksomhed juridisk", items: ["Vilkår - specifikt designet til fotografer", "Opgaveaftale (Offerte) - med skabeloner og e-maileksempler", "Privatlivspolitik - GDPR-kompatibel", "Cookiepolitik - fuld GDPR-overholdelse", "Ansvarsfraskrivelse - beskyt dine fotos og indhold", "Fraskrivelse - juridisk dækning for aftaler med modeller", "Ophavsretsbeskyttelse (Auteursrecht) - international dækning"], whyTitle: "Hvorfor vælge denne pakke?", whyItems: ["Klar til brug på minutter", "Til alle dine fotografiwebsteder", "International dækning", "Nem at tilpasse"], price: "€79", priceLabel: "engangsbetaling", priceDesc: "Komplet juridisk beskyttelse. Brug til ubegrænset antal websteder. Ingen løbende gebyrer.", priceCta: "Hent komplet pakke nu" },
  no: { sectionTitle: "Hvorfor juridiske dokumenter er essensielle for fotografer", sectionDesc: "Som profesjonell fotograf trenger du juridisk beskyttelse for din virksomhet, ditt kreative arbeid og dine kunder.", aboutTitle: "Om Nicole Henderson", aboutRole: "Juridisk spesialist for kreative profesjonelle", aboutP1: "Med års erfaring i å hjelpe fotografer forstår jeg de unike juridiske utfordringene.", aboutP2: "Disse dokumentene er designet for å være enkle å tilpasse med maksimal juridisk beskyttelse.", packageTitle: "Komplett juridisk pakke for fotografer", packageDesc: "Alt du trenger for å beskytte din fotografivirksomhet juridisk", items: ["Vilkår - spesielt designet for fotografer", "Oppdragsavtale (Offerte) - med maler og e-posteksempler", "Personvernregler - GDPR-kompatibel", "Informasjonskapselregler - full GDPR-overholdelse", "Ansvarsfraskrivelse - beskytt bildene og innholdet ditt", "Fraskrivelse - juridisk dekning for avtaler med modeller", "Opphavsrettsbeskyttelse (Auteursrecht) - internasjonal dekning"], whyTitle: "Hvorfor velge denne pakken?", whyItems: ["Klar til bruk på minutter", "For alle dine fotografi-nettsteder", "Internasjonal dekning", "Enkel å tilpasse"], price: "€79", priceLabel: "engangsbetaling", priceDesc: "Komplett juridisk beskyttelse. Bruk for ubegrenset antall nettsteder. Ingen løpende gebyrer.", priceCta: "Hent komplett pakke nå" },
  ro: { sectionTitle: "De ce documentele juridice sunt esențiale pentru fotografi", sectionDesc: "Ca fotograf profesionist, aveți nevoie de protecție juridică pentru afacerea, munca creativă și clienții dumneavoastră.", aboutTitle: "Despre Nicole Henderson", aboutRole: "Specialist juridic pentru profesioniști creativi", aboutP1: "Cu ani de experiență în ajutarea fotografilor, înțeleg provocările juridice unice.", aboutP2: "Aceste documente sunt concepute pentru a fi ușor personalizabile cu protecție juridică maximă.", packageTitle: "Pachet juridic complet pentru fotografi", packageDesc: "Tot ce aveți nevoie pentru a vă proteja juridic afacerea de fotografie", items: ["Termeni și condiții - special concepute pentru fotografi", "Contract de atribuire (Offerte) - cu șabloane și exemple de email", "Politica de confidențialitate - conformă GDPR", "Politica de cookies - conformitate completă GDPR", "Declinare de responsabilitate - protejați fotografiile și conținutul", "Renunțare - acoperire juridică pentru acorduri cu modele", "Protecția drepturilor de autor (Auteursrecht) - acoperire internațională"], whyTitle: "De ce să alegeți acest pachet?", whyItems: ["Gata de utilizare în câteva minute", "Pentru toate site-urile dvs. de fotografie", "Acoperire internațională", "Ușor de personalizat"], price: "€79", priceLabel: "plată unică", priceDesc: "Protecție juridică completă. Utilizare pentru site-uri nelimitate. Fără taxe recurente.", priceCta: "Obțineți pachetul complet" },
  bg: { sectionTitle: "Защо правните документи са от съществено значение за фотографите", sectionDesc: "Като професионален фотограф се нуждаете от правна защита за вашия бизнес и творческа работа.", aboutTitle: "За Nicole Henderson", aboutRole: "Правен специалист за творчески професионалисти", aboutP1: "С години опит в помощта на фотографи, разбирам уникалните правни предизвикателства.", aboutP2: "Тези документи са проектирани за лесно персонализиране с максимална правна защита.", packageTitle: "Пълен правен пакет за фотографи", packageDesc: "Всичко необходимо за правна защита на вашия фотографски бизнес", items: ["Общи условия - специално за фотографи", "Договор за възлагане (Offerte) - с шаблони и примери за имейли", "Политика за поверителност - съвместима с GDPR", "Политика за бисквитки - пълно съответствие с GDPR", "Отказ от отговорност - защита на снимки и съдържание", "Отказ от претенции - правна защита за договори с модели", "Защита на авторски права (Auteursrecht) - международно покритие"], whyTitle: "Защо да изберете този пакет?", whyItems: ["Готов за минути", "За всички ваши фотографски сайтове", "Международно покритие", "Лесно персонализируем"], price: "€79", priceLabel: "еднократно", priceDesc: "Пълна правна защита. Неограничено използване. Без повтарящи се такси.", priceCta: "Вземете пълния пакет" },
  fi: { sectionTitle: "Miksi oikeudelliset asiakirjat ovat välttämättömiä valokuvaajille", sectionDesc: "Ammattivalokuvaajana tarvitset oikeudellista suojaa liiketoiminnallesi, luovalle työllesi ja asiakkaillesi.", aboutTitle: "Tietoa Nicole Hendersonista", aboutRole: "Oikeudellinen asiantuntija luoville ammattilaisille", aboutP1: "Vuosien kokemuksella valokuvaajien auttamisessa ymmärrän ainutlaatuiset oikeudelliset haasteet.", aboutP2: "Nämä asiakirjat on suunniteltu helposti muokattaviksi ja tarjoamaan maksimaalisen oikeudellisen suojan.", packageTitle: "Täydellinen oikeudellinen paketti valokuvaajille", packageDesc: "Kaikki mitä tarvitset valokuvausliiketoimintasi oikeudelliseen suojaamiseen", items: ["Käyttöehdot - erityisesti valokuvaajille", "Toimeksiantosopimus (Offerte) - malleilla ja sähköpostiesimerkeillä", "Tietosuojakäytäntö - GDPR-yhteensopiva", "Evästekäytäntö - täydellinen GDPR-vaatimustenmukaisuus", "Vastuuvapauslauseke - suojaa kuvasi ja sisältösi", "Oikeuksista luopuminen - oikeudellinen suoja mallien kanssa", "Tekijänoikeussuoja (Auteursrecht) - kansainvälinen kattavuus"], whyTitle: "Miksi valita tämä paketti?", whyItems: ["Käyttövalmis minuuteissa", "Kaikille valokuvaussivustoillesi", "Kansainvälinen kattavuus", "Helposti muokattavissa"], price: "€79", priceLabel: "kertamaksu", priceDesc: "Täydellinen oikeudellinen suoja. Rajoittamaton käyttö. Ei toistuvia maksuja.", priceCta: "Hanki täydellinen paketti" },
  ru: { sectionTitle: "Почему юридические документы необходимы фотографам", sectionDesc: "Как профессиональный фотограф, вам нужна юридическая защита для вашего бизнеса, творческой работы и клиентов.", aboutTitle: "О Nicole Henderson", aboutRole: "Юридический специалист для творческих профессионалов", aboutP1: "С многолетним опытом помощи фотографам я понимаю уникальные юридические проблемы.", aboutP2: "Эти документы разработаны для легкой настройки и максимальной юридической защиты.", packageTitle: "Полный юридический пакет для фотографов", packageDesc: "Всё необходимое для юридической защиты вашего фотобизнеса", items: ["Условия использования - специально для фотографов", "Договор на выполнение работ (Offerte) - с шаблонами и примерами email", "Политика конфиденциальности - соответствует GDPR", "Политика cookies - полное соответствие GDPR", "Отказ от ответственности - защита фотографий и контента", "Отказ от претензий - юридическая защита договоров с моделями", "Защита авторских прав (Auteursrecht) - международная защита"], whyTitle: "Почему выбрать этот пакет?", whyItems: ["Готов к использованию за минуты", "Для всех ваших фотосайтов", "Международная защита", "Легко настраиваемый"], price: "€79", priceLabel: "единоразово", priceDesc: "Полная юридическая защита. Неограниченное использование. Без подписки.", priceCta: "Получить полный пакет" },
  zh: { sectionTitle: "为什么法律文件对摄影师至关重要", sectionDesc: "作为专业摄影师，您需要法律保护来保障您的业务、创意作品和客户。", aboutTitle: "关于Nicole Henderson", aboutRole: "创意专业人士法律专家", aboutP1: "凭借多年帮助摄影师的经验，我了解您面临的独特法律挑战。", aboutP2: "这些文件设计为易于定制，同时提供最大的法律保护。", packageTitle: "摄影师完整法律套餐", packageDesc: "您保护摄影业务所需的一切法律文件", items: ["条款与条件 - 专为摄影师设计", "委托协议 (Offerte) - 附模板和邮件示例", "隐私政策 - 符合GDPR", "Cookie政策 - 完全符合GDPR", "免责声明 - 保护您的照片和内容", "权利放弃 - 模特协议的法律保障", "版权保护 (Auteursrecht) - 国际覆盖"], whyTitle: "为什么选择此套餐？", whyItems: ["几分钟即可使用", "适用于所有摄影网站", "国际覆盖", "易于定制"], price: "€79", priceLabel: "一次性付款", priceDesc: "完整法律保护。无限使用。无重复费用。", priceCta: "立即获取完整套餐" },
  hi: { sectionTitle: "फ़ोटोग्राफ़रों के लिए कानूनी दस्तावेज़ क्यों आवश्यक हैं", sectionDesc: "एक पेशेवर फ़ोटोग्राफ़र के रूप में, आपको अपने व्यवसाय, रचनात्मक कार्य और ग्राहकों के लिए कानूनी सुरक्षा की आवश्यकता है।", aboutTitle: "Nicole Henderson के बारे में", aboutRole: "रचनात्मक पेशेवरों के लिए कानूनी विशेषज्ञ", aboutP1: "फ़ोटोग्राफ़रों की मदद करने के वर्षों के अनुभव के साथ, मैं अद्वितीय कानूनी चुनौतियों को समझती हूँ।", aboutP2: "ये दस्तावेज़ अधिकतम कानूनी सुरक्षा के साथ आसानी से अनुकूलित करने योग्य हैं।", packageTitle: "फ़ोटोग्राफ़रों के लिए पूर्ण कानूनी पैकेज", packageDesc: "अपनी फ़ोटोग्राफ़ी व्यवसाय की कानूनी सुरक्षा के लिए आवश्यक सब कुछ", items: ["नियम और शर्तें - विशेष रूप से फ़ोटोग्राफ़रों के लिए", "असाइनमेंट अनुबंध (Offerte) - टेम्पलेट और ईमेल उदाहरणों के साथ", "गोपनीयता नीति - GDPR अनुपालक", "कुकी नीति - पूर्ण GDPR अनुपालन", "अस्वीकरण - अपनी तस्वीरों और सामग्री की रक्षा करें", "छूट - मॉडल समझौतों के लिए कानूनी सुरक्षा", "कॉपीराइट सुरक्षा (Auteursrecht) - अंतर्राष्ट्रीय कवरेज"], whyTitle: "यह पैकेज क्यों चुनें?", whyItems: ["मिनटों में उपयोग के लिए तैयार", "आपकी सभी फ़ोटोग्राफ़ी वेबसाइटों के लिए", "अंतर्राष्ट्रीय कवरेज", "आसानी से अनुकूलन योग्य"], price: "€79", priceLabel: "एक बार भुगतान", priceDesc: "पूर्ण कानूनी सुरक्षा। असीमित उपयोग। कोई आवर्ती शुल्क नहीं।", priceCta: "पूर्ण पैकेज प्राप्त करें" },
  ja: { sectionTitle: "なぜ法的文書が写真家に不可欠なのか", sectionDesc: "プロの写真家として、ビジネス、クリエイティブワーク、クライアントの法的保護が必要です。", aboutTitle: "Nicole Hendersonについて", aboutRole: "クリエイティブ専門家向け法律スペシャリスト", aboutP1: "写真家を長年支援してきた経験から、独自の法的課題を理解しています。", aboutP2: "これらの文書は、最大限の法的保護を提供しながら、簡単にカスタマイズできるよう設計されています。", packageTitle: "写真家向け完全法的パッケージ", packageDesc: "写真ビジネスの法的保護に必要なすべて", items: ["利用規約 - 写真家向けに特別設計", "業務委託契約 (Offerte) - テンプレートとメール例付き", "プライバシーポリシー - GDPR準拠", "Cookieポリシー - 完全なGDPR準拠", "免責事項 - 写真とコンテンツの保護", "権利放棄 - モデルとの契約の法的保護", "著作権保護 (Auteursrecht) - 国際的な保護"], whyTitle: "このパッケージを選ぶ理由", whyItems: ["数分で使用可能", "すべての写真サイトに対応", "国際的な保護", "簡単にカスタマイズ可能"], price: "€79", priceLabel: "一回払い", priceDesc: "完全な法的保護。無制限使用。定期料金なし。", priceCta: "完全パッケージを入手" },
  ar: { sectionTitle: "لماذا الوثائق القانونية ضرورية للمصورين", sectionDesc: "كمصور محترف، تحتاج إلى حماية قانونية لعملك وإبداعك وعملائك.", aboutTitle: "عن Nicole Henderson", aboutRole: "متخصصة قانونية للمحترفين المبدعين", aboutP1: "بسنوات من الخبرة في مساعدة المصورين، أفهم التحديات القانونية الفريدة.", aboutP2: "هذه الوثائق مصممة لتكون سهلة التخصيص مع أقصى حماية قانونية.", packageTitle: "حزمة قانونية كاملة للمصورين", packageDesc: "كل ما تحتاجه لحماية أعمال التصوير قانونياً", items: ["الشروط والأحكام - مصممة خصيصاً للمصورين", "اتفاقية التكليف (Offerte) - مع قوالب وأمثلة بريد إلكتروني", "سياسة الخصوصية - متوافقة مع GDPR", "سياسة ملفات تعريف الارتباط - امتثال كامل لـ GDPR", "إخلاء المسؤولية - حماية صورك ومحتواك", "التنازل - تغطية قانونية لاتفاقيات النماذج", "حماية حقوق النشر (Auteursrecht) - تغطية دولية"], whyTitle: "لماذا تختار هذه الحزمة؟", whyItems: ["جاهز للاستخدام في دقائق", "لجميع مواقع التصوير الخاصة بك", "تغطية دولية", "سهل التخصيص"], price: "€79", priceLabel: "دفعة واحدة", priceDesc: "حماية قانونية كاملة. استخدام غير محدود. بدون رسوم متكررة.", priceCta: "احصل على الحزمة الكاملة" },
  ko: { sectionTitle: "왜 법적 문서가 사진작가에게 필수적인가", sectionDesc: "전문 사진작가로서 비즈니스, 창작물, 고객을 위한 법적 보호가 필요합니다.", aboutTitle: "Nicole Henderson 소개", aboutRole: "크리에이티브 전문가를 위한 법률 전문가", aboutP1: "수년간 사진작가를 도운 경험으로 고유한 법적 과제를 이해합니다.", aboutP2: "이 문서는 최대한의 법적 보호와 함께 쉽게 맞춤화할 수 있도록 설계되었습니다.", packageTitle: "사진작가를 위한 완전한 법적 패키지", packageDesc: "사진 비즈니스를 법적으로 보호하는 데 필요한 모든 것", items: ["이용약관 - 사진작가를 위해 특별 설계", "위탁 계약 (Offerte) - 템플릿 및 이메일 예시 포함", "개인정보 보호정책 - GDPR 준수", "쿠키 정책 - 완전한 GDPR 준수", "면책조항 - 사진 및 콘텐츠 보호", "권리 포기 - 모델 계약의 법적 보호", "저작권 보호 (Auteursrecht) - 국제적 보호"], whyTitle: "이 패키지를 선택해야 하는 이유", whyItems: ["몇 분 안에 사용 가능", "모든 사진 웹사이트에 사용", "국제적 보호", "쉽게 맞춤화 가능"], price: "€79", priceLabel: "일회성 결제", priceDesc: "완전한 법적 보호. 무제한 사용. 정기 요금 없음.", priceCta: "완전한 패키지 받기" },
  cs: { sectionTitle: "Proč jsou právní dokumenty nezbytné pro fotografy", sectionDesc: "Jako profesionální fotograf potřebujete právní ochranu pro své podnikání, tvůrčí práci a klienty.", aboutTitle: "O Nicole Henderson", aboutRole: "Právní specialistka pro kreativní profesionály", aboutP1: "S letitými zkušenostmi s pomocí fotografům rozumím jedinečným právním výzvám.", aboutP2: "Tyto dokumenty jsou navrženy pro snadné přizpůsobení s maximální právní ochranou.", packageTitle: "Kompletní právní balíček pro fotografy", packageDesc: "Vše potřebné pro právní ochranu vašeho fotografického podnikání", items: ["Obchodní podmínky - speciálně pro fotografy", "Smlouva o dílo (Offerte) - se šablonami a příklady emailů", "Zásady ochrany osobních údajů - GDPR kompatibilní", "Zásady cookies - plný soulad s GDPR", "Prohlášení - ochrana fotografií a obsahu", "Vzdání se nároku - právní ochrana smluv s modely", "Ochrana autorských práv (Auteursrecht) - mezinárodní pokrytí"], whyTitle: "Proč zvolit tento balíček?", whyItems: ["Připraveno k použití za minuty", "Pro všechny vaše fotografické weby", "Mezinárodní pokrytí", "Snadno přizpůsobitelné"], price: "€79", priceLabel: "jednorázově", priceDesc: "Kompletní právní ochrana. Neomezené použití. Žádné opakující se poplatky.", priceCta: "Získat kompletní balíček" },
  hu: { sectionTitle: "Miért nélkülözhetetlenek a jogi dokumentumok fotósoknak", sectionDesc: "Professzionális fotósként jogi védelemre van szüksége vállalkozásához, alkotó munkájához és ügyfeleihez.", aboutTitle: "Nicole Hendersonról", aboutRole: "Jogi szakértő kreatív szakembereknek", aboutP1: "Évek tapasztalatával a fotósok segítésében megértem az egyedi jogi kihívásokat.", aboutP2: "Ezek a dokumentumok könnyen testreszabhatóak maximális jogi védelemmel.", packageTitle: "Teljes jogi csomag fotósoknak", packageDesc: "Minden, amire szüksége van fotóvállalkozása jogi védelméhez", items: ["Általános feltételek - speciálisan fotósoknak", "Megbízási szerződés (Offerte) - sablonokkal és email példákkal", "Adatvédelmi irányelvek - GDPR-kompatibilis", "Cookie szabályzat - teljes GDPR megfelelőség", "Felelősségkizárás - fotók és tartalom védelme", "Lemondó nyilatkozat - modellek szerződéseinek jogi védelme", "Szerzői jogi védelem (Auteursrecht) - nemzetközi lefedettség"], whyTitle: "Miért válassza ezt a csomagot?", whyItems: ["Percek alatt használatra kész", "Minden fotós weboldalához", "Nemzetközi lefedettség", "Könnyen testreszabható"], price: "€79", priceLabel: "egyszeri díj", priceDesc: "Teljes jogi védelem. Korlátlan használat. Nincsenek ismétlődő díjak.", priceCta: "Teljes csomag beszerzése" },
  uk: { sectionTitle: "Чому юридичні документи необхідні фотографам", sectionDesc: "Як професійний фотограф, вам потрібен юридичний захист для вашого бізнесу, творчої роботи та клієнтів.", aboutTitle: "Про Nicole Henderson", aboutRole: "Юридичний спеціаліст для творчих професіоналів", aboutP1: "З багаторічним досвідом допомоги фотографам я розумію унікальні юридичні виклики.", aboutP2: "Ці документи розроблені для легкого налаштування з максимальним юридичним захистом.", packageTitle: "Повний юридичний пакет для фотографів", packageDesc: "Все необхідне для юридичного захисту вашого фотобізнесу", items: ["Умови використання - спеціально для фотографів", "Договір на виконання робіт (Offerte) - з шаблонами та прикладами email", "Політика конфіденційності - відповідає GDPR", "Політика cookies - повна відповідність GDPR", "Застереження - захист фотографій та контенту", "Відмова від претензій - юридичний захист договорів з моделями", "Захист авторських прав (Auteursrecht) - міжнародне покриття"], whyTitle: "Чому обрати цей пакет?", whyItems: ["Готовий за лічені хвилини", "Для всіх ваших фотосайтів", "Міжнародне покриття", "Легко налаштовується"], price: "€79", priceLabel: "одноразово", priceDesc: "Повний юридичний захист. Необмежене використання. Без повторних платежів.", priceCta: "Отримати повний пакет" },
  sk: { sectionTitle: "Prečo sú právne dokumenty nevyhnutné pre fotografov", sectionDesc: "Ako profesionálny fotograf potrebujete právnu ochranu pre svoje podnikanie, tvorivú prácu a klientov.", aboutTitle: "O Nicole Henderson", aboutRole: "Právna špecialistka pre kreatívnych profesionálov", aboutP1: "S rokmi skúseností s pomocou fotografom rozumiem jedinečným právnym výzvam.", aboutP2: "Tieto dokumenty sú navrhnuté pre jednoduché prispôsobenie s maximálnou právnou ochranou.", packageTitle: "Kompletný právny balíček pre fotografov", packageDesc: "Všetko potrebné pre právnu ochranu vášho fotografického podnikania", items: ["Obchodné podmienky - špeciálne pre fotografov", "Zmluva o dielo (Offerte) - so šablónami a príkladmi emailov", "Zásady ochrany súkromia - GDPR kompatibilné", "Zásady cookies - plný súlad s GDPR", "Vyhlásenie - ochrana fotografií a obsahu", "Vzdanie sa nároku - právna ochrana zmlúv s modelmi", "Ochrana autorských práv (Auteursrecht) - medzinárodné pokrytie"], whyTitle: "Prečo zvoliť tento balíček?", whyItems: ["Pripravené za minúty", "Pre všetky vaše fotografické weby", "Medzinárodné pokrytie", "Ľahko prispôsobiteľné"], price: "€79", priceLabel: "jednorázovo", priceDesc: "Kompletná právna ochrana. Neobmedzené použitie. Žiadne opakujúce sa poplatky.", priceCta: "Získať kompletný balíček" },
  hr: { sectionTitle: "Zašto su pravni dokumenti neophodni za fotografe", sectionDesc: "Kao profesionalni fotograf trebate pravnu zaštitu za svoju djelatnost, kreativni rad i klijente.", aboutTitle: "O Nicole Henderson", aboutRole: "Pravna stručnjakinja za kreativne profesionalce", aboutP1: "S godinama iskustva u pomaganju fotografima razumijem jedinstvene pravne izazove.", aboutP2: "Ovi dokumenti su dizajnirani za jednostavnu prilagodbu s maksimalnom pravnom zaštitom.", packageTitle: "Kompletan pravni paket za fotografe", packageDesc: "Sve što trebate za pravnu zaštitu vašeg fotografskog poslovanja", items: ["Uvjeti korištenja - posebno za fotografe", "Ugovor o zadatku (Offerte) - s predlošcima i primjerima emaila", "Politika privatnosti - GDPR kompatibilna", "Politika kolačića - potpuna GDPR usklađenost", "Odricanje od odgovornosti - zaštita fotografija i sadržaja", "Odricanje - pravna zaštita za ugovore s modelima", "Zaštita autorskih prava (Auteursrecht) - međunarodna pokrivenost"], whyTitle: "Zašto odabrati ovaj paket?", whyItems: ["Spreman za korištenje u minutama", "Za sve vaše fotografske stranice", "Međunarodna pokrivenost", "Jednostavno prilagodljiv"], price: "€79", priceLabel: "jednokratno", priceDesc: "Potpuna pravna zaštita. Neograničena uporaba. Bez ponavljajućih naknada.", priceCta: "Nabavite kompletan paket" },
  sr: { sectionTitle: "Зашто су правни документи неопходни за фотографе", sectionDesc: "Као професионални фотограф потребна вам је правна заштита за ваш бизнис, креативни рад и клијенте.", aboutTitle: "О Nicole Henderson", aboutRole: "Правни стручњак за креативне професионалце", aboutP1: "Са годинама искуства у помагању фотографима разумем јединствене правне изазове.", aboutP2: "Ови документи су дизајнирани за лако прилагођавање уз максималну правну заштиту.", packageTitle: "Комплетан правни пакет за фотографе", packageDesc: "Све што вам је потребно за правну заштиту фотографског пословања", items: ["Услови коришћења - посебно за фотографе", "Уговор о делу (Offerte) - са шаблонима и примерима emaila", "Политика приватности - GDPR компатибилна", "Политика колачића - потпуна GDPR усклађеност", "Одрицање од одговорности - заштита фотографија и садржаја", "Одрицање - правна заштита за уговоре са моделима", "Заштита ауторских права (Auteursrecht) - међународно покриће"], whyTitle: "Зашто одабрати овај пакет?", whyItems: ["Спреман за коришћење за минуте", "За све ваше фотографске сајтове", "Међународно покриће", "Лако прилагодљив"], price: "€79", priceLabel: "једнократно", priceDesc: "Потпуна правна заштита. Неограничена употреба. Без понављајућих накнада.", priceCta: "Набавите комплетан пакет" },
  sl: { sectionTitle: "Zakaj so pravni dokumenti bistveni za fotografe", sectionDesc: "Kot profesionalni fotograf potrebujete pravno zaščito za svojo dejavnost, ustvarjalno delo in stranke.", aboutTitle: "O Nicole Henderson", aboutRole: "Pravna strokovnjakinja za ustvarjalne strokovnjake", aboutP1: "Z leti izkušenj pri pomoči fotografom razumem edinstvene pravne izzive.", aboutP2: "Ti dokumenti so zasnovani za enostavno prilagajanje z maksimalno pravno zaščito.", packageTitle: "Celoten pravni paket za fotografe", packageDesc: "Vse, kar potrebujete za pravno zaščito vaše fotografske dejavnosti", items: ["Pogoji uporabe - posebej za fotografe", "Pogodba o naročilu (Offerte) - s predlogami in primeri elektronske pošte", "Pravilnik o zasebnosti - skladen z GDPR", "Pravilnik o piškotkih - popolna skladnost z GDPR", "Omejitev odgovornosti - zaščita fotografij in vsebine", "Odpoved - pravna zaščita za dogovore z modeli", "Zaščita avtorskih pravic (Auteursrecht) - mednarodna pokritost"], whyTitle: "Zakaj izbrati ta paket?", whyItems: ["Pripravljen v minutah", "Za vse vaše fotografske strani", "Mednarodna pokritost", "Enostavno prilagodljiv"], price: "€79", priceLabel: "enkratno", priceDesc: "Popolna pravna zaščita. Neomejena uporaba. Brez ponavljajočih se stroškov.", priceCta: "Pridobite celoten paket" },
  tr: { sectionTitle: "Fotoğrafçılar için yasal belgeler neden gereklidir", sectionDesc: "Profesyonel bir fotoğrafçı olarak işiniz, yaratıcı çalışmalarınız ve müşterileriniz için yasal korumaya ihtiyacınız var.", aboutTitle: "Nicole Henderson Hakkında", aboutRole: "Yaratıcı profesyoneller için hukuk uzmanı", aboutP1: "Fotoğrafçılara yardım etme konusunda yıllarca deneyimle benzersiz yasal zorlukları anlıyorum.", aboutP2: "Bu belgeler, maksimum yasal koruma ile kolay özelleştirme için tasarlanmıştır.", packageTitle: "Fotoğrafçılar için eksiksiz yasal paket", packageDesc: "Fotoğrafçılık işinizi yasal olarak korumak için ihtiyacınız olan her şey", items: ["Şartlar ve Koşullar - fotoğrafçılar için özel tasarım", "Görev Sözleşmesi (Offerte) - şablonlar ve e-posta örnekleriyle", "Gizlilik Politikası - GDPR uyumlu", "Çerez Politikası - tam GDPR uyumu", "Sorumluluk Reddi - fotoğraflarınızı ve içeriğinizi koruyun", "Feragat - modeller ile anlaşmalar için yasal koruma", "Telif Hakkı Koruması (Auteursrecht) - uluslararası kapsam"], whyTitle: "Bu paketi neden seçmelisiniz?", whyItems: ["Dakikalar içinde kullanıma hazır", "Tüm fotoğraf web siteleriniz için", "Uluslararası kapsam", "Kolayca özelleştirilebilir"], price: "€79", priceLabel: "tek seferlik ödeme", priceDesc: "Tam yasal koruma. Sınırsız kullanım. Tekrarlayan ücret yok.", priceCta: "Tam paketi alın" },
};

interface Props { lang: string; }

const ValuePropositionPhotographyMulti = ({ lang }: Props) => {
  const t = translations[lang];
  return (
    <section id="about-me" className="py-20 bg-background">
      <div className="container">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">{t.sectionTitle}</h2>
            <p className="text-lg text-muted-foreground">{t.sectionDesc}</p>
          </div>

          <Card className="mb-12 bg-card border-border">
            <CardHeader>
              <div className="flex items-center gap-4">
                <img src={nicoleProfile} alt="Nicole Henderson - Legal Specialist" className="w-20 h-20 rounded-full object-cover" />
                <div>
                  <CardTitle className="text-2xl text-foreground">{t.aboutTitle}</CardTitle>
                  <CardDescription>{t.aboutRole}</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground mb-4">{t.aboutP1}</p>
              <p className="text-muted-foreground">{t.aboutP2}</p>
            </CardContent>
          </Card>

          <Card className="border-primary bg-primary/5">
            <CardHeader>
              <div className="flex items-center gap-3 mb-4">
                <div className="h-12 w-12 rounded-lg bg-red-600 flex items-center justify-center">
                  <Shield className="h-6 w-6 text-white" />
                </div>
                <CardTitle className="text-2xl text-foreground">{t.packageTitle}</CardTitle>
              </div>
              <CardDescription className="text-base">{t.packageDesc}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-3">
                {t.items.map((item, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <Check className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                    <span className="text-foreground">{item}</span>
                  </div>
                ))}
              </div>

              <div className="pt-6 border-t border-border">
                <h3 className="font-semibold text-lg mb-3 text-foreground">{t.whyTitle}</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  {t.whyItems.map((item, index) => (
                    <div key={index} className="flex items-start gap-2">
                      <Check className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                      <span className="text-sm text-muted-foreground">{item}</span>
                    </div>
                  ))}
                </div>
              </div>

              <Card className="bg-card border-primary">
                <CardContent className="pt-6">
                  <div className="text-center space-y-4">
                    <div>
                      <span className="text-4xl font-bold text-primary">{t.price}</span>
                      <span className="text-muted-foreground ml-2">{t.priceLabel}</span>
                    </div>
                    <p className="text-sm text-muted-foreground">{t.priceDesc}</p>
                    <Button size="lg" onClick={() => scrollToSection("pricing")} className="w-full bg-primary hover:bg-primary/90">
                      {t.priceCta}
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
};

export default ValuePropositionPhotographyMulti;
