import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

const faqContent = {
  title: "Häufig gestellte Fragen zu Rechtsdokumenten für Fotografen",
  description: "Häufige Fragen von Fotografen zum Rechtsschutz und zur Dokumentation",
  questions: [
    { question: "Wie kann ich Musik oder Video in meinen Fotoinhalten legal verwenden?", answer: "Stellen Sie immer sicher, dass Sie Rechte oder Lizenzen für Musik- oder Videoclips haben, die in Ihren Diashows oder sozialen Medien verwendet werden. Nutzen Sie lizenzfreie Plattformen wie Epidemic Sound, Artlist oder Pexels. Verwenden Sie niemals urheberrechtlich geschütztes Material ohne ausdrückliche Genehmigung, da dies zu Löschaufforderungen oder Geldstrafen führen kann." },
    { question: "Was ist eine Verzichtserklärung in der Fotografie?", answer: "Eine Verzichtserklärung ist eine unterschriebene Freigabe, bei der ein Model oder Eigentümer alle Rechte oder zukünftigen Ansprüche auf Bilder abtritt und dem Fotografen volle Nutzungsrechte gewährt. Sie ist unerlässlich für kommerzielle Shootings, Werbung oder jedes Projekt, bei dem Bilder international verkauft oder veröffentlicht werden könnten." },
    { question: "Was ist eine Objektfreigabe und wann brauche ich eine?", answer: "Eine Objektfreigabe erteilt die Genehmigung, Privateigentum für kommerzielle Zwecke zu fotografieren. Sie ist erforderlich für Standorte wie Häuser, Büros oder erkennbare Wahrzeichen. Ohne diese Freigabe können Sie bei der kommerziellen Lizenzierung oder dem Verkauf dieser Bilder auf rechtliche Einschränkungen stoßen." },
    { question: "Wie sollten Fotografen mit geistigem Eigentum umgehen?", answer: "Beanspruchen Sie immer das Urheberrecht in Ihren Verträgen und Metadaten. Registrieren Sie Ihre Bilder wenn möglich bei einem Urheberrechtsamt. Fügen Sie Wasserzeichen, EXIF-Daten hinzu und führen Sie klare Lizenzaufzeichnungen. Vermeiden Sie die Verwendung fremder Werke ohne Erlaubnis, auch nur als Inspiration." },
    { question: "Was sind Urheberpersönlichkeitsrechte in der Fotografie?", answer: "Urheberpersönlichkeitsrechte schützen die Integrität und den Ruf eines Fotografen. Sie umfassen das Recht auf Namensnennung und das Recht, gegen Verzerrung oder Missbrauch Ihrer Bilder Einspruch zu erheben. Diese Rechte bestehen in vielen Ländern automatisch und sollten von Kunden und Mitarbeitern respektiert werden." },
    { question: "Darf ich Menschen an öffentlichen Orten legal fotografieren?", answer: "In den meisten Ländern ist das Fotografieren von Menschen in der Öffentlichkeit für redaktionelle oder künstlerische Zwecke erlaubt, aber die kommerzielle Nutzung dieser Bilder erfordert ein Model-Release. Prüfen Sie immer die lokalen Datenschutzgesetze – sie variieren stark je nach Region." },
    { question: "Was ist eine Vertraulichkeitsvereinbarung (NDA) für Fotografen?", answer: "Eine NDA verhindert, dass Kunden oder Mitarbeiter vertrauliche Informationen über Ihr Shooting, Ihre Preise oder Ihren kreativen Prozess weitergeben. Sie ist in der Mode-, Werbe- und Unternehmensfotografie üblich, um Geschäftsgeheimnisse und Markenstrategien zu schützen." },
    { question: "Wie kann ich mein Online-Portfolio vor Diebstahl schützen?", answer: "Versehen Sie Ihre Bilder dezent mit Wasserzeichen, deaktivieren Sie das Speichern per Rechtsklick und betten Sie Metadaten in Ihre Dateien ein. Verwenden Sie Vorschauen mit niedriger Auflösung für die Webdarstellung. Dienste wie Pixsy oder Digimarc helfen bei der weltweiten Verfolgung und Durchsetzung unbefugter Bildnutzung." },
    { question: "Wie kann ich einen starken Fotografie-Haftungsausschluss schreiben?", answer: "Ihr Haftungsausschluss sollte festlegen, dass alle Fotos dem Fotografen gehören und nicht ohne schriftliche Zustimmung kopiert oder verbreitet werden dürfen. Fügen Sie einen Hinweis hinzu, dass Farben und Erscheinungsbild je nach Gerät oder Bildschirmeinstellungen variieren können, um Ansprüche wegen Falschdarstellung zu vermeiden." },
    { question: "Wie wichtig ist Branding für Fotografen?", answer: "Starkes Branding baut Wiedererkennung und Vertrauen auf. Es umfasst ein einheitliches Logo, eine Farbpalette, einen Tonfall und einen Bearbeitungsstil. Eine klare Markenidentität hilft Kunden, sich an Sie zu erinnern, und positioniert Sie als Profi in Ihrer Nische." },
    { question: "Wie können Fotografen ein internationales Publikum aufbauen?", answer: "Nutzen Sie Social-Media-Plattformen strategisch (Instagram, Pinterest, Behance). Schreiben Sie mehrsprachige Bildunterschriften und verwenden Sie internationale Hashtags. Arbeiten Sie mit globalen Kreativen zusammen, nehmen Sie an Online-Ausstellungen teil und optimieren Sie Ihre Website für mehrere Sprachen und Währungen." },
    { question: "Wie erzähle ich eine Geschichte durch meine Fotografie?", answer: "Jedes Bild sollte Emotion, Kontext oder Erzählung vermitteln. Verwenden Sie Komposition, Beleuchtung und Motive bewusst. Bildsequenzen können visuelles Storytelling aufbauen – ideal für redaktionelle und dokumentarische Arbeiten." },
    { question: "Wie gehe ich ethisch mit Bildmanipulation um?", answer: "Fotobearbeitung sollte verbessern, aber nicht irreführen. Vermeiden Sie die Veränderung von Körpermerkmalen auf eine Weise, die die Realität verzerrt, es sei denn, es geschieht aus künstlerischer Absicht. Geben Sie immer an, wenn Composites oder KI-generierte Elemente verwendet werden, um Transparenz und Vertrauen zu wahren." },
    { question: "Was ist KI-generierte Fotografie und ist sie legal?", answer: "KI-Tools können Bilder erstellen oder modifizieren, aber die Urheberrechtszugehörigkeit ist komplex. Die Gesetze unterscheiden sich je nach Region – in den meisten Fällen sind nur von Menschen geschaffene Elemente urheberrechtlich schützbar. Legen Sie die KI-Beteiligung gegenüber Kunden klar offen und vermeiden Sie die Erzeugung von Ähnlichkeiten ohne Zustimmung." },
    { question: "Wie kann ich als Fotograf mit Marken zusammenarbeiten?", answer: "Erstellen Sie ein professionelles Media Kit mit Ihrem Portfolio, Publikumsstatistiken und Preisen. Sprechen Sie Marken mit maßgeschneiderten Vorschlägen an, die den gegenseitigen Nutzen zeigen. Schließen Sie klare Verträge mit Angaben zu Leistungen, Zahlung, Exklusivität und Lizenzrechten ab." },
    { question: "Was sollte ich in eine Fotografie-Datenschutzerklärung aufnehmen?", answer: "Erklären Sie, wie Kundendaten (Namen, Fotos, Kontaktinformationen) erfasst, gespeichert und verwendet werden. Geben Sie an, wie lange Daten aufbewahrt werden und wie Kunden die Löschung beantragen können. Stellen Sie die Einhaltung der DSGVO, CCPA oder lokaler Datenschutzgesetze sicher." },
    { question: "Wie kann ich kulturelle Sensibilität in der Fotografie berücksichtigen?", answer: "Recherchieren Sie immer lokale Bräuche und holen Sie eine Einwilligung ein, bevor Sie Personen oder religiöse Stätten fotografieren. Vermeiden Sie die Verstärkung von Stereotypen. Ethische Darstellung stärkt Ihren Ruf und unterstützt verantwortungsvolles visuelles Storytelling." },
    { question: "Was sind die Risiken von KI-Bildverbesserungstools?", answer: "KI kann überbearbeiten oder wichtige Details verändern und so die Authentizität verringern. Einige Tools speichern möglicherweise hochgeladene Bilder, was die Datensicherheit gefährdet. Verwenden Sie vertrauenswürdige Software, lesen Sie die Nutzungsbedingungen und bewahren Sie Originale als Nachweis der Urheberschaft auf." },
    { question: "Wie mache ich mein Fotografieunternehmen zukunftssicher?", answer: "Diversifizieren Sie Einkommensströme (Prints, Workshops, Online-Kurse, Stock-Lizenzen). Bauen Sie eine starke Online-Präsenz auf und passen Sie sich neuen Technologien wie KI und NFTs an. Lernen Sie kontinuierlich weiter und aktualisieren Sie Ihre Verträge, Ihr Branding und Ihre Ausrüstung regelmäßig." },
    { question: "Welche Rechte behalte ich als Fotograf beim Verkauf von Bildern?", answer: "Als Fotograf behalten Sie standardmäßig das Urheberrecht an Ihren Bildern gemäß internationaler Verträge wie der Berner Konvention. Sie können Nutzungsrechte (Lizenzen) an Kunden übertragen und gleichzeitig die zugrunde liegenden Rechte schützen. Definieren Sie klar in Ihrem Vertrag, was der Kunde tun darf (Print, Digital, Kommerziell) und behalten Sie den Rest vor." },
    { question: "Wann sollte ich ein Verzichts- oder Freigabeformular in der Fotografie verwenden?", answer: "Verwenden Sie ein Verzichts- oder Freigabeformular, wenn Sie Bilder liefern und sicherstellen möchten, dass der Kunde auf zukünftige Ansprüche verzichtet (z.B. Model-Release für kommerzielle Nutzung). Es schützt Sie vor Haftung, begrenzt zukünftige Streitigkeiten und stellt klar, dass der Kunde die Rechte wie im Vertrag festgelegt akzeptiert." },
    { question: "Wie fotografiere ich ethisch korrekt in öffentlichen oder privaten Räumen?", answer: "Respektieren Sie die Privatsphäre und lokale Gesetze. In den meisten Rechtsordnungen dürfen Sie in öffentlichen Räumen ohne ausdrückliche Erlaubnis fotografieren, aber für erkennbare Personen oder private Standorte benötigen Sie eine Einwilligung oder Freigabe. Legen Sie immer offen, wie Sie die Bilder verwenden werden, und ermöglichen Sie es den Personen, sich abzumelden, wenn es angemessen ist." },
    { question: "Was sollte ich beim Branding meines Fotografieunternehmens beachten?", answer: "Branding sollte Ihren Stil, Ihre Nische und Ihren Zielmarkt widerspiegeln. Verwenden Sie ein einheitliches Logo, eine Farbpalette, Typografie und Stimme. Präsentieren Sie Ihre besten Arbeiten, Referenzen und ein klares Wertversprechen. Eine starke Marke hilft Ihnen, sich abzuheben und Kunden anzuziehen, die zu Ihrer Ästhetik passen." },
    { question: "Wie erzähle ich überzeugende visuelle Geschichten durch Fotografie?", answer: "Konzentrieren Sie sich auf die Erzählung: Was passiert, wer ist das Subjekt, welche Emotion oder Botschaft möchten Sie vermitteln? Verwenden Sie Komposition, Beleuchtung, Farbe und Kontext zur Unterstützung Ihrer Geschichte. Zeigen Sie einen Anfang, eine Mitte und ein Ende in einer Serie, um Betrachter zu fesseln und die Wirkung zu vertiefen." },
    { question: "Welche ethischen Überlegungen gelten für Fotobearbeitung und Retusche?", answer: "Seien Sie transparent darüber, was verändert wurde, insbesondere bei Porträt- oder kommerzieller Arbeit. Vermeiden Sie die Verfälschung der Realität (z.B. erhebliche Körpermodifikation), es sei denn, der Auftrag erlaubt dies ausdrücklich. Ethische Bearbeitung schafft Vertrauen bei Personen und Kunden." },
    { question: "Wie navigiere ich das Urheberrecht in verschiedenen Ländern?", answer: "Das Urheberrecht ist in den meisten Ländern gemäß der Berner Konvention automatisch geschützt. Dennoch sollten Sie Ihr Werk wenn möglich registrieren (z.B. US Copyright Office) für eine stärkere Durchsetzung. Verwenden Sie Verträge mit Angabe des anwendbaren Rechts und der Gerichtsbarkeit, um Unsicherheiten bei internationalen Kunden zu reduzieren." },
    { question: "Wie kann ich bei Fotografie-Beleuchtung ohne Blitz arbeiten?", answer: "Verwenden Sie eine große Blendenöffnung (f/1.8–f/2.8), eine langsamere Verschlusszeit und erhöhen Sie den ISO-Wert vorsichtig, um Rauschen zu vermeiden. Stabilisieren Sie Ihre Kamera auf einem Stativ oder einer festen Oberfläche. Das Aufnehmen in RAW ermöglicht bessere Nachbearbeitung in Programmen wie Lightroom oder Photoshop für Rauschreduzierung und Farbkorrektur." },
    { question: "Welches ist das beste Objektiv für Porträtfotografie?", answer: "Ein Festbrennweitenobjektiv mit großer Blendenöffnung, wie 50mm f/1.8 oder 85mm f/1.4, ist ideal für Porträts. Diese Objektive erzeugen schöne Hintergrundunschärfe (Bokeh) und schmeichelhafte Kompression für Gesichtszüge. Wählen Sie Vollformatobjektive für professionelle Qualität und gleichmäßige Schärfe." },
    { question: "Wie mache ich großartige Landschaftsfotos?", answer: "Verwenden Sie eine kleine Blendenöffnung (f/8–f/16) für eine große Schärfentiefe, fokussieren Sie ein Drittel in die Szene hinein und verwenden Sie ein Stativ für Stabilität. Die besten Zeiten für Landschaftsaufnahmen sind Sonnenaufgang und Sonnenuntergang. Fügen Sie Vordergrundinteresse für Tiefe hinzu und verwenden Sie einen Polarisationsfilter, um den Himmel zu verbessern." },
    { question: "Was ist Weißabgleich in der Fotografie?", answer: "Der Weißabgleich passt die Farbtemperatur an, damit Weißtöne unter verschiedenen Beleuchtungsbedingungen neutral erscheinen. Gängige Einstellungen sind Tageslicht, Bewölkt, Kunstlicht und Leuchtstoffröhre. Ein korrekter Weißabgleich verhindert, dass Fotos zu blau oder orange aussehen, und sorgt für einheitliche Farbtöne." },
    { question: "Wie kann ich sich schnell bewegende Motive fotografieren?", answer: "Verwenden Sie die Blendenpriorität und stellen Sie eine schnelle Verschlusszeit ein (1/500s oder höher). Aktivieren Sie den kontinuierlichen Autofokus (AF-C) und den Serienmodus, um mehrere Bilder aufzunehmen. Sport-, Wildtier- und Eventfotografen verlassen sich auf diese Einstellungen für gestochen scharfe, dynamische Aufnahmen." },
    { question: "Was ist Makrofotografie?", answer: "Makrofotografie erfasst extreme Nahaufnahmen kleiner Motive wie Insekten, Schmuck oder Blumen. Verwenden Sie ein Makroobjektiv (1:1-Verhältnis) und stellen Sie eine stabile Fokussierung mit einem Stativ oder Focus Stacking sicher. Gute Beleuchtung und geringe Schärfentiefe heben filigrane Details hervor." },
    { question: "Wie kann ich bessere Kompositionen erstellen?", answer: "Wenden Sie Kompositionstechniken wie die Drittelregel, Symmetrie, Führungslinien und Rahmen an. Vermeiden Sie es, jedes Motiv zu zentrieren. Verwenden Sie Vordergrund- und Hintergrundebenen, um visuelle Tiefe zu erzeugen. Studieren Sie Meisterfotografen für kreative Kompositionsinspiration." },
    { question: "Was ist der Unterschied zwischen Vollformat- und Crop-Sensor-Kameras?", answer: "Vollformatkameras haben größere Sensoren, bessere Leistung bei wenig Licht und geringere Schärfentiefe. Crop-Sensoren (APS-C) sind günstiger und leichter, reduzieren aber leicht die Bildqualität und das Sichtfeld. Beide können mit den richtigen Objektiven professionelle Ergebnisse liefern." },
    { question: "Wie kann ich meine Fotos wie ein Profi bearbeiten?", answer: "Verwenden Sie Bearbeitungssoftware wie Adobe Lightroom oder Capture One. Passen Sie Belichtung, Kontrast, Weißabgleich und Color Grading konsistent an. Vermeiden Sie Überbearbeitung – Dezenz bewahrt den Realismus. Verwenden Sie Voreinstellungen oder benutzerdefinierte Stile für eine zusammenhängende Portfolio-Ästhetik." },
    { question: "Was sind die besten Kameraeinstellungen für Nachtfotografie?", answer: "Verwenden Sie den manuellen Modus, ein Stativ, ISO 800–1600, große Blende (f/2.8) und eine langsame Verschlusszeit (10–30s). Fotografieren Sie in RAW, um Schattendetails wiederherzustellen. Ein Fernauslöser oder Selbstauslöser hilft, Verwacklungen zu vermeiden." },
    { question: "Wie mache ich professionelle Produktfotos?", answer: "Verwenden Sie weiches, gleichmäßiges Licht und einen neutralen Hintergrund. Eine Lichtbox oder ein Diffusor eliminiert harte Schatten. Halten Sie den ISO-Wert niedrig für Klarheit und fotografieren Sie mit einem Stativ. Passen Sie den Weißabgleich für genaue Farben an und retuschieren Sie Staub oder Reflexionen in der Nachbearbeitung." },
    { question: "Was ist Bokeh und wie erzeuge ich es?", answer: "Bokeh ist die ästhetische Qualität der Hintergrundunschärfe, die von einem Objektiv mit großer Blendenöffnung (f/1.2–f/2.8) erzeugt wird. Verwenden Sie eine lange Brennweite und halten Sie Ihr Motiv weit vom Hintergrund entfernt. Festbrennweiten und runde Blendenlamellen erzeugen weichere Bokeh-Effekte." },
    { question: "Wie mache ich großartige Schwarz-Weiß-Fotos?", answer: "Konzentrieren Sie sich auf Beleuchtung, Textur und Kontrast statt auf Farbe. Fotografieren Sie in RAW und konvertieren Sie in der Nachbearbeitung für bessere Tonwertsteuerung. Vermeiden Sie flaches Licht; dramatische Schatten verstärken Stimmung und Storytelling in der Monochromfotografie." },
    { question: "Was sind die besten Apps für Fotobearbeitung auf dem Handy?", answer: "Beliebte professionelle Apps sind Lightroom Mobile, Snapseed, VSCO und Adobe Photoshop Express. Diese Tools ermöglichen feine Kontrolle über Belichtung, Kontrast und Farbe. Für schnelle Bearbeitung sind Canva oder Pixlr gute Alternativen." },
    { question: "Was ist Komposition in der Fotografie?", answer: "Komposition bezieht sich darauf, wie Elemente in einem Bild angeordnet sind. Eine starke Komposition lenkt den Blick des Betrachters und schafft Ausgewogenheit. Techniken umfassen die Drittelregel, Führungslinien, Symmetrie und negativen Raum für wirkungsvolle Bilder." },
    { question: "Wie fotografiere ich Silhouetten?", answer: "Positionieren Sie Ihr Motiv vor einer hellen Lichtquelle wie dem Sonnenuntergang. Belichten Sie für den Hintergrund statt für das Motiv. Verwenden Sie eine kleine Blende und den manuellen Modus. Silhouetten betonen Form und Gestalt und machen sie zu kraftvollen Storytelling-Werkzeugen." }
  ]
};

const FAQPhotographyDE = () => {
  return (
    <section className="py-20 bg-secondary/30">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto">
          <Badge className="mb-4">Fragen & Antworten</Badge>
          <h1 className="text-4xl font-bold mb-4">Häufig gestellte Fragen</h1>
          <p className="text-xl text-muted-foreground mb-12">Häufige Fragen von Fotografen zum Rechtsschutz und zur Dokumentation für Ihre Website</p>

          <Accordion type="single" collapsible className="space-y-4">
            <AccordionItem value="faq-all" className="border rounded-lg px-6 py-2">
              <AccordionTrigger className="hover:no-underline">
                <h2 className="text-xl font-semibold text-left">{faqContent.title}</h2>
              </AccordionTrigger>
              <AccordionContent className="pt-4 space-y-6">
                {faqContent.questions.map((item, index) => (
                  <div key={index} className="space-y-2">
                    <h2 className="text-lg font-semibold">{item.question}</h2>
                    <p className="text-muted-foreground">{item.answer}</p>
                  </div>
                ))}
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default FAQPhotographyDE;
